lingui/js-lingui

.flowconfig
packages/example-usecase/package.json
packages/example-usecase/src/Usecases/Children.js
packages/example-usecase/src/Usecases/ElementAttributes.js
packages/example-usecase/src/Usecases/__snapshots__/Children.test.js.snap
packages/example-usecase/src/Usecases/__snapshots__/Formats.test.js.snap
packages/example-usecase/yarn.lock
packages/lingui-formats/package.json
packages/lingui-formats/src/date.js
packages/lingui-i18n/package.json
packages/lingui-i18n/src/compile.js
packages/lingui-i18n/src/i18n.js
packages/lingui-react/package.json
packages/lingui-react/src/createFormat.js
packages/lingui-react/src/index.js
yarn.lock

Fix flow types

---

docs/guides/migration-1.md
packages/example-usecase/CHANGELOG.md
packages/example-usecase/package.json
packages/lingui-i18n/CHANGELOG.md
packages/lingui-i18n/package.json
packages/lingui-i18n/src/i18n.js
packages/lingui-i18n/src/i18n.test.js
packages/lingui-i18n/src/index.js
packages/lingui-react/CHANGELOG.md
packages/lingui-react/package.json

Add named export of i18n instance

---

.flowconfig
package.json
packages/lingui-cli/src/lingui-add-locale.js
packages/lingui-cli/test/lingui-add-locale.test.js
packages/lingui-cli/test/utils.js
packages/lingui-i18n/src/dev/loadLanguageData.js
packages/lingui-i18n/src/i18n.test.js
yarn.lock

Support country-specific locales

---

packages/babel-plugin-lingui-extract-messages/src/index.js
packages/babel-plugin-lingui-extract-messages/test/fixtures/jsx/deep/all.js
packages/babel-plugin-lingui-extract-messages/test/fixtures/jsx/without-lingui.js
packages/babel-plugin-lingui-extract-messages/test/index.js
packages/babel-plugin-lingui-transform-react/src/index.js
packages/babel-plugin-lingui-transform-react/test/fixtures/imports-without-lingui/actual.js
packages/babel-plugin-lingui-transform-react/test/fixtures/imports-without-lingui/expected.js
packages/lingui-cli/test/fixtures/extract/src/App.js
packages/lingui-cli/test/fixtures/extract/src/deep/App.js

Ignore files without lingui imports

---

packages/babel-plugin-lingui-extract-messages/CHANGELOG.md
packages/babel-plugin-lingui-extract-messages/package.json
packages/babel-plugin-lingui-transform-react/CHANGELOG.md
packages/babel-plugin-lingui-transform-react/package.json
packages/babel-plugin-lingui-transform-react/src/index.js
packages/babel-plugin-lingui-transform-react/test/__snapshots__/index.js.snap
packages/babel-plugin-lingui-transform-react/test/fixtures/component-plural/actual.js
packages/babel-plugin-lingui-transform-react/test/fixtures/component-plural/expected.js
packages/babel-plugin-lingui-transform-react/test/fixtures/component-select/actual.js
packages/babel-plugin-lingui-transform-react/test/fixtures/component-select/expected.js
packages/babel-plugin-lingui-transform-react/test/fixtures/component-selectordinal/actual.js
packages/babel-plugin-lingui-transform-react/test/fixtures/component-selectordinal/expected.js
packages/babel-plugin-lingui-transform-react/test/index.js
packages/babel-preset-lingui-react/CHANGELOG.md
packages/babel-preset-lingui-react/package.json
packages/example-usecase/CHANGELOG.md
packages/example-usecase/package.json
packages/lingui-cli/CHANGELOG.md
packages/lingui-cli/package.json

Transform this
```js
<Plural value={items.count} one={'# book'} other={'# books'} />
```
into this:
`{0, plural, one {# book} other {# books}}`

Allow expressions as component values

---

docs/guides/plurals.rst

for issue #85 
There were some Sphinx specific errors and small spelling mistakes which are fixed.

Updated plurals.rst with sphinx syntax errors

---

docs/ref/lingui-react.rst

Grammar fixes to lingui-react

---

packages/lingui-react/src/Render.js
packages/lingui-react/src/Render.test.js
packages/lingui-react/src/__snapshots__/Render.test.js.snap

PR for issue #90 
Please review 🍰

#90 Forward compatibility with React 16

---

examples/webpack-react/CHANGELOG.md
examples/webpack-react/package.json
packages/lingui-cli/CHANGELOG.md
packages/lingui-cli/package.json
packages/lingui-cli/src/lingui-extract.js

Create _build dir when no messages are extracted

---

packages/lingui-cli/CHANGELOG.md
packages/lingui-cli/package.json
packages/lingui-cli/src/api/formats/lingui.js

Fix lingui extract/compile on windows

---

circle.yml
docs/guides/optimized-components.rst
docs/index.rst
docs/ref/lingui-react.rst
examples/webpack-react/CHANGELOG.md
examples/webpack-react/package.json
examples/webpack-react/src/Usecases/PureComponent.js
examples/webpack-react/src/Usecases/PureComponent.test.js
examples/webpack-react/src/Usecases/__snapshots__/Children.test.js.snap
examples/webpack-react/src/Usecases/__snapshots__/Formats.test.js.snap
packages/lingui-loader/src/index.js
packages/lingui-react/CHANGELOG.md
packages/lingui-react/package.json
packages/lingui-react/src/I18nProvider.js
packages/lingui-react/src/withI18n.js
packages/lingui-react/src/withI18n.test.js
packages/lingui-react/yarn.lock

Add forPure option for withI18n

---

packages/cli/package.json
packages/cli/src/api/extractors/typescript.js

This is a copy of the `babel` extractor with the addition of the TypeScript plugin to support `.ts` and `.tsx` files. I've tested it locally but wasn't able to fully build the CLI to make sure it works in every situation.
(Some tests will probably be needed before moving forward with this).

Typescript extractor

---

docs/tutorials/react.rst

- JSX syntax error in react tutorial

JSX syntax  error in react doc

---

docs/ref/core.rst
docs/ref/react.rst
packages/cli/src/api/formats/lingui.js
packages/cli/src/api/formats/lingui.test.js
packages/cli/src/api/formats/utils/locales.js
packages/core/src/i18n.js
packages/core/src/i18n.test.js
packages/core/src/i18nMark.test.js
packages/react/src/I18nProvider.js
packages/react/src/I18nProvider.test.js
packages/react/src/Trans.test.js
scripts/build/index.js

Allow customize message for missing translations

---

docs/misc/showroom.rst

Hi, I'm Jinhyeok Lee working at MyMusicTaste.
Since we have already mentioned that we're using js-lingui in our [Frontend job description document](https://github.com/MyMusicTaste/recruit/blob/master/frontend.md) that had been [available to public](https://github.com/MyMusicTaste/recruit/blob/master/README_EN.md) long ago, I went ahead and added the service.
We've been using js-lingui on typescript before any TS support was available so I had to make up some workarounds to extract and transform ts/tsx files as expected. (by putting files through a set of tsc & babel plugins, basically `yarn i18n:scrap` to build js catalogs and `yarn i18n:merge` to update translations from transifex dump)
Time well spent, here we are, Thanks to your project.
commit messages may be a bit different than …

add item in projects using js-lingui document

---

packages/cli/src/api/formats/__snapshots__/po.test.js.snap
packages/cli/src/api/formats/fixtures/messages.po
packages/cli/src/api/formats/po.js

Output multiple origins on separate lines

---

packages/cli/src/mocks.js
packages/conf/src/index.js

@tricoder42  It should work much better now :)

fix: Correctly handle config validation

---

CONTRIBUTING.md
README.md
package.json
packages/cli/package.json
yarn.lock

Hi, I'm making updates for Open Collective. Either you or a supporter signed this repo up for Open Collective. This pull request adds backers and sponsors from your Open Collective https://opencollective.com/js-lingui ❤️
It adds two badges at the top to show the latest number of backers and sponsors. It also adds placeholders so that the avatar/logo of new backers/sponsors can automatically be shown without having to update your README.md. [[more info](https://github.com/opencollective/opencollective/wiki/Github-banner)]. See how it looks on [this repo](https://github.com/apex/apex#backers).
We have also added a `postinstall` script to let people know after `npm|yarn install` that you are welcoming donations (optional). [[More info](https://github.com/OpenCollective/opencollective-cli)] …

Activating Open Collective

---

package.json
scripts/build/index.js
yarn.lock

Copy source files with flow types

---

.circleci/config.yml
appveyor.yml
package.json
packages/babel-plugin-extract-messages/package.json
packages/babel-plugin-transform-js/package.json
packages/babel-plugin-transform-react/package.json
packages/cli/package.json
packages/conf/package.json
packages/core/package.json
packages/loader/package.json
packages/macro/package.json
packages/react/package.json

Update required NodeJS version

---

docs/releases/migration-3.rst
docs/tutorials/react.rst

follow-up on https://github.com/lingui/js-lingui/pull/352
I'll take a look at the other tutorials later, and open separate PRs for those to keep things easy to review. 
By the way, I like `withI18n` more than the `<I18n>` render prop. The HOC is definitely cleaner and less verbose. I'm just saying this because I saw the render prop a lot in the docs.

review react tutorial for v3

---

docs/misc/react-intl.rst

fixed typo

---

docs/tutorials/setup-react.rst

Fix babel-plugin-macros name

---

docs/guides/typescript.rst

Typescript docs: compileNamespace explanation

---

scripts/build/rollup.js

fix: disable Google Clojure Compiler rewritePolyfills behavior

---

packages/babel-plugin-extract-messages/src/index.js
packages/babel-plugin-extract-messages/test/__snapshots__/index.js.snap
packages/babel-plugin-extract-messages/test/fixtures/jsx/integration-without-trans.js
packages/babel-plugin-extract-messages/test/index.js

Extract messages when Trans component is missing

---

.gitignore
packages/cli/src/api/catalog.js
packages/cli/src/api/compile.js
packages/cli/src/lingui-compile.js

Fixes the issue brought up in https://gitter.im/lingui/js-lingui at https://gitter.im/lingui/js-lingui?at=5bfefd9f958fc5389504d577

Allow pseudolocales which don't start with a known language

---

docs/tutorials/setup-cra.rst

This one bit us when getting started :)

Include sourceLocale in .linguirc example

---

packages/cli/src/api/help.js

[Bug Fix]Add empty check for process.env.npm_config_user_agent

---

docs/misc/showroom.rst

* Your company name: Staycation
* Link to your website: https://www.staycation.co
* Does the website is open sourced? If so, please share a link: No :( 
* What's the size of the website? How many languages do you use, how many message do you have? : Size is approx. 150 000 lines of code, for now 2 languages are use (french & english), but a lot more are to come during the year :)

Add Staycation to Lingui's showroom

---

docs/misc/react-intl.rst

Just a quick typo fix in the docs!

Minor typo fix, "popural" -> "popular"

---

docs/misc/showroom.rst

- Your company name: Monitora Media s.r.o.
- Link to your website: https://monitora.cz/
- Is the website open sourced? Nope.
- What's the size of the website? Currently about 38k lines of JS.
- How many languages do you use, how many messages do you have? Currently 3
languages (Czech, Slovak, English) and about 460 messages.

docs: Add Monitora to Lingui's showroom

---

docs/misc/showroom.rst

Another thankful "client" of Lingui :)

Add Turisto to the showroom

---

docs/misc/showroom.rst

Thanks for this great library!

Add Nolt to showroom

---

docs/misc/showroom.rst

We've been using LinguIJS with LocalEthereum for some time now to support 12 languages.
Thank you for the great project.

Documentation - Add "LocalEthereum" to list of projects using LinguiJS

---

packages/core/src/dev/compile.test.js

Fixes a typo that makes the test fail.

fix typo in test

---

packages/macro/test/fixtures/js-t-var/.babelrc
packages/macro/test/fixtures/js-t-var/js-t-var.expected.js
packages/macro/test/fixtures/js-t-var/js-t-var.js
packages/macro/test/index.ts
packages/macro/test/js-t.ts

Add test case for scoped variables

---

packages/cli/src/lingui-compile.js

fix: compile strict skips pseudo locale

---

README.md

Fix link to Gitter room in readme

---

packages/cli/package.json
packages/cli/src/api/__snapshots__/catalog.test.ts.snap
packages/cli/src/api/catalog.test.ts
packages/cli/src/api/catalog.ts
yarn.lock

Use micromatch to handle Win path sep

---

packages/cli/src/api/formats/lingui.ts
packages/cli/src/api/formats/minimal.ts
packages/cli/src/api/formats/po.ts
packages/cli/src/api/utils.ts

Don't write unchanged extract files

---

packages/macro/package.json

Required here: https://github.com/lingui/js-lingui/blob/next/packages/macro/src/index.ts#L2

Adds missing dependency

---

examples/next-js/package.json
examples/next-js/yarn.lock

add typescript to dependencies

next.js example - added typescript

---

packages/cli/src/api/catalog.test.ts
packages/cli/src/api/catalog.ts
packages/cli/src/lingui-compile.ts

#731 Hi this PR attempts to solve this issue.

File extension of ES modules will be .mjs

---

docs/misc/showroom.rst

Thanks a lot for Lingui, I have been using it for I18n on the frontend for some time, replacing i18next, and it has been a nice improvement.
Will try to update to 3.0 soon, it seems even better!

Add Notos to showroom

---

docs/releases/migration-3.rst
packages/react/src/I18nProvider.test.tsx
packages/react/src/I18nProvider.tsx

For an easier migration to v3.0.0, i've introduced a little hoc for an easy migration to big codebases where withI18n it's used a lot!
On master branch, this hoc accepts some configuration, should we accept that configuration?
Feel free to request changes

feat: introduced withI18n

---

docs/tutorials/cli.rst
packages/cli/src/api/catalog.test.ts
packages/cli/src/api/catalog.ts
packages/cli/src/lingui-compile.ts
packages/conf/index.d.ts
packages/conf/src/index.ts

Resolves #568
Continuation of https://github.com/lingui/js-lingui/pull/658 - I have no write access ofc so I started a new PR
Just thinking if we want to apply this proposition https://github.com/lingui/js-lingui/pull/658#issuecomment-706675746

568 merge catalogs

---

docs/ref/react.rst
docs/releases/migration-2.rst
docs/releases/migration-3.rst
docs/tutorials/react-native.rst
package.json
packages/macro/index.d.ts
packages/react/src/I18nProvider.tsx
packages/react/src/Trans.test.tsx
packages/react/src/Trans.tsx

fix: render from prop 

---

packages/cli/src/lingui-compile.ts

return true is currently inside forEach by mistake, moved outside of it

[766] compile should return true correctly if everything was fine

---

docs/guides/testing.rst

add testing-information with react testing library

---

docs/releases/migration-3.rst
examples/next-js/yarn.lock
packages/macro/src/macroJsx.ts
packages/macro/test/jsx-trans.ts

Closes #780 
@semoal There's a small change in migration docs. Does it affect your codemod? I guess not, but I wanted to check with yout.

Keep decoded html entities

---

packages/macro/src/index.ts
packages/macro/test/index.ts
packages/macro/test/jsx-trans.ts

fix: import type declaration overrides @lingui/react

---

packages/cli/src/api/catalog.test.ts
packages/cli/src/api/catalog.ts

Fix catalog include path on Windows

---

packages/cli/src/api/__snapshots__/catalog.test.ts.snap
packages/cli/src/api/catalog.test.ts
packages/cli/src/api/catalog.ts
packages/cli/src/api/fixtures/collect/componentA/componentA.js
packages/cli/src/api/fixtures/collect/componentB.js

Allow multiple paths in catalog.include

---

docs/ref/cli.rst
packages/cli/src/api/__snapshots__/catalog.test.ts.snap
packages/cli/src/api/catalog.test.ts
packages/cli/src/api/catalog.ts
packages/cli/src/api/formats/po.ts
packages/cli/src/lingui-extract-template.ts
packages/cli/src/lingui.ts
packages/cli/src/tests.ts

closes #793 which also contains details about why this is useful

Add `lingui extract-template` command

---

packages/cli/src/api/help.ts

Will close #727
Super easy feature, but will help a lot the introduction to not soo much experienced users on lingui

feat: lingui commands suggestion looks package.json

---

packages/cli/src/lingui-compile.ts

fix: exit 1 on strict mode of compile

---

docs/ref/loader.rst
examples/create-react-app/package.json
examples/create-react-app/src/i18n.ts
packages/loader/src/index.js

fix: mandatory ext on @lingui/loader

---

packages/core/src/i18n.ts

fix: MessageDescriptor values type

---

docs/tutorials/cli.rst

docs: update cli.rst react link

---

.github/workflows/deploy-main-docs.yml
.gitignore
lerna.json
package.json
packages/babel-plugin-extract-messages/package.json
packages/cli/package.json
packages/conf/package.json
packages/core/package.json
packages/detect-locale/package.json
packages/loader/package.json
packages/macro/package.json
packages/react/package.json
scripts/build/packaging.js
scripts/integration.js
scripts/jest/config.integration.js
scripts/jest/config.unit.js
scripts/release.js

I don't why but I get used to see the build/ folder on rootDir and didn't though that lerna deploys dist folder of each package. `
I changed the scripts to build the pack inside each package, and adjusted integration testing to provide from there.

chore: deploy from build inside each package

---

packages/cli/src/api/catalog.ts
packages/conf/src/index.test.ts
packages/conf/src/index.ts

fix: locale not present in catalogs warn

---

packages/babel-plugin-extract-messages/src/index.ts
packages/core/src/dev/loadLocaleData.test.ts

chore: improve dx warn on undefined id

---

packages/react/src/I18nProvider.tsx

fix: withI18n HOC typescript inference

---

packages/cli/src/api/formats/csv.ts
packages/cli/src/api/formats/lingui.ts
packages/cli/src/api/formats/minimal.ts
packages/cli/src/api/formats/po.ts

fix: formatters exceptions throw error

---

CONTRIBUTING.md

Added restore default registry description to CONTRIBUTING.md

chore: add information how to restore default registry

---

packages/macro/src/macroJs.ts
packages/macro/src/macroJsx.ts
packages/macro/test/js-t.ts

fix: scaped literals double backslash formatting

---

packages/detect-locale/npm/esm/index.js
packages/detect-locale/npm/esm/package.json

fix(detect-locale): ESM import not published

---

docs/ref/conf.rst

Should have been part of #941, but oh well :)

docs: Add info about TS based config

---

packages/conf/package.json

closes https://github.com/lingui/js-lingui/issues/948

add lodash.get to @lingui/conf as dependency

---

packages/react/src/I18nProvider.tsx

not sure why this is not picked up in tests, but I believe the typing is wrong here. I might be wrong here but I tested locally and it seems fine
BTW I noticed that when running the code through prettier, it comes up with many more changes, the prettier config is probably not followed...

fix: defaultComponent typing

---

docs/guides/typescript.rst
packages/macro/global.d.ts
packages/macro/package.json
scripts/build/babel.js

fix: @lingui/macro types for global environments

---

docs/ref/conf.rst

amend docs to clarify locale codes

---

docs/ref/conf.rst
packages/cli/src/api/catalog.ts
packages/cli/src/api/formats/lingui.test.ts
packages/cli/src/api/formats/lingui.ts
packages/cli/src/api/formats/po.test.ts
packages/cli/src/api/formats/po.ts
packages/conf/index.d.ts
packages/conf/src/__snapshots__/index.test.ts.snap
packages/conf/src/index.ts

feat: allow to disable lineNumbers

---

packages/core/src/eventEmitter.test.ts
packages/core/src/eventEmitter.ts
packages/core/src/i18n.ts
packages/react/src/I18nProvider.test.tsx
packages/react/src/I18nProvider.tsx

This reverts commit a7aa6a6cae302c9ff595abe4f60b67e930a11b89.

fix: event emitter refactor (reverted)

---

examples/next-js/.babelrc
examples/next-js/lingui-example/i18n.ts
examples/next-js/next.config.js
examples/next-js/package.json
examples/next-js/tsconfig.json
examples/next-js/yarn.lock
packages/loader/src/index.js

fix: loader works smoothly on webpack 5 & 4

---

packages/cli/src/api/formats/lingui.ts
packages/cli/src/api/formats/po.ts

fix: lineNumbers false was removing the entire origin

---

docs/misc/showroom.rst

We've been using Lingui for several months to get our desktop and mobile website internationalized / localized, so we want to add ourselves to the showroom!

chore: Add OkCupid to the showroom

---

docs/misc/react-intl.rst

Fix minor mistake in the discussion section

docs: minor correction to react-intl

---

docs/ref/macro.rst

This PR updates transformation result of macros and remove usage of date macro in the reference.

docs: Update macro references

---

docs/ref/core.rst

This PR adds missing documentations of I18n.date and I18n.number.

docs: Add reference of I18n.date and I18n.number

---

packages/cli/src/api/extractors/index.ts
packages/conf/src/__snapshots__/index.test.ts.snap
packages/conf/src/index.ts

fix(): extractors CLI validation and accept require and require.resolve

---

packages/cli/src/api/formats/__snapshots__/po-gettext.test.ts.snap
packages/cli/src/api/formats/fixtures/messages_plural-4-letter.po
packages/cli/src/api/formats/po-gettext.test.ts
packages/cli/src/api/formats/po-gettext.ts

fix(): country-coded language breaks plurals with po-gettext

---

docs/tools/introduction.rst
docs/tools/translation-io.rst

Someone proofread the text of my previous documentation PR.
That's not much but it's still some improvement 🙂

docs: Proofread documentation (`introduction.rst` and `translation-io.rst`)

---

docs/misc/showroom.rst

Add mapflow.ai to projects list

docs: add mapflow.ai

---

docs/misc/showroom.rst

We're using lingui for the adventure booking portal Ascendero.com. Great tool, helps a lot, thanks.

docs: Update showroom.rst

---

packages/core/src/i18n.test.ts
packages/core/src/i18n.ts
packages/react/src/I18nProvider.test.tsx

fix: i18n.activate should load instantly new messages

---

packages/cli/src/lingui-extract-template.ts

If you don't have a *.pot file on the disk the command will fail with:
```
catalogStats[catalog.templateFile] = Object.keys(catalog.readTemplate()).length;
TypeError: Cannot convert undefined or null to object
```
If you create a file manually (just empty file), the command will complete successfully but catalog statistics will show outdated info. 
> Catalog statistics for /translates/messages.pot: 0 messages
Both problems caused by `catalog.makeTemplate` which is async function, but code don't await for its execution. 
This PR tackle this issue, and adds await for these async calls.

fix: extract-template command

---

packages/cli/src/api/formats/minimal.ts

https://github.com/lingui/js-lingui/issues/1259

fix: Try to add a trailing newline if the file had one

---

.github/codecov.yml
docs/Pipfile.lock

- Regenerate the `docs/Pipfile.lock` using the `pipenv lock` command
- Add `codecov.yml` configuration

docs: fix Vercel deployment

---

scripts/verdaccio-release.js

This closes #1326 by implementing a command specific for Windows to do the `git update-index` marking and unmarking files magic.
Furthermore, I had to change the `LERNA_COMMAND` to plain `npx lerna` to get it working on Windows.

fix: Local development not working on Windows

---

.github/workflows/main-suite.yml
package.json
packages/cli/package.json
scripts/test-node-api.js

Fixes https://github.com/lingui/js-lingui/issues/1348

fix(build): explicitly expose api/extractors

---

package.json
packages/cli/package.json
packages/core/src/compile/compileMessage.test.ts
yarn.lock

No breaking changes for the lib, just update typescript which we can use in the tests and tooling scripts.

chore(build): update typescript in tooling

---

packages/vite-plugin/package.json

This PR adds the [`files`](https://docs.npmjs.com/cli/v9/configuring-npm/package-json#files) property to the Vite-plugin's `package.json` to avoid publishing unnecessary files to the registry.

chore: define package files for vite-plugin

---

packages/cli/src/api/formats/po-gettext.ts
packages/core/src/i18n.test.ts
packages/detect-locale/src/utils/query-string.ts
scripts/test.ts
tsconfig.json

Set `"noUnusedLocals": true` for typescript compiler

chore: set "noUnusedLocals": true

---

website/docs/introduction.md
website/docs/ref/macro.md
website/docs/ref/swc-plugin.md
website/docs/tutorials/react-patterns.md
website/docs/tutorials/react.md
website/docs/tutorials/setup-react.md
website/sidebars.ts

docs: add info about SWC Plugin

---

.github/codecov.yml

This PR updates the `coverage.range` since the actual coverage was changed after #1406.
> coverage.range
> The value range where you want the value to be green

ci: update Codecov configuration

---

.github/workflows/main-suite.yml

`verbose` - Specify whether the Codecov output should be verbose

ci: add 'verbose' option to 'codecov/codecov-action'

---

website/docs/ref/macro.md

Fixes docs for https://github.com/lingui/js-lingui/issues/1324
Also we need to fix typings in v4 (will come in next PRs)

docs(macro): update select example

---

README.md
website/docs/introduction.md

Update info about bundle size for `@lingui/core` and `@lingui/react` packages

docs: update bundle size info

---

website/docs/guides/optimized-components.md

docs(): fix misusage in docs

---

website/package.json
website/src/components/Code.module.scss
website/src/components/Code.tsx
website/src/components/Features.module.scss
website/src/components/Header.module.scss
website/src/pages/index.tsx
website/yarn.lock

- Update Docusaurus to the latest version
- Fix header title for mobile devices
- Add the "Example" section

docs: main page improvements

---

website/docs/ref/swc-plugin.md

docs(swc-plugin): Fix `.swcrc` `jsc.experimental.plugins` structure

---

packages/cli/src/lingui-extract-template.ts
packages/cli/src/lingui-extract.ts
packages/conf/src/getConfig.ts
packages/macro/src/index.ts

fix: always honor `process.env.LINGUI_CONFIG`

---

packages/cli/src/lingui-extract.ts

fix: fix build after merge

---

website/docs/misc/resources.md
website/docs/tools/crowdin.md
website/docs/tools/introduction.md

docs: update Crowdin links

---

website/docs/ref/catalog-formats.md
website/docs/ref/macro.md
website/docs/releases/migration-4.md

Little bit updated and restructured the info about the context

docs: enhance the info about the context

---

.github/workflows/main-suite.yml
package.json
packages/babel-plugin-extract-messages/package.json
packages/cli/package.json
packages/conf/package.json
packages/core/package.json
packages/detect-locale/package.json
packages/loader/package.json
packages/macro/package.json
packages/react/package.json
packages/remote-loader/package.json
packages/snowpack-plugin/package.json
packages/vite-plugin/package.json
website/docs/releases/migration-4.md

- Set Node v16 engine for packages
- CI: Remove v14 and add v16 to the test matrix

chore: set the minimum required node version to 16

---

package.json
yarn.lock

chore(): update nodejs typings

---

package.json
packages/cli/package.json
packages/cli/src/api/catalog.test.ts
packages/cli/src/tests.ts
yarn.lock

chore(): use native FS methods instead of fs-extra

---

package.json
yarn.lock

Checked all the Lerna releases after the 3.22.1 version and it seems that there weren't any breaking changes affecting us.
https://github.com/lerna/lerna/releases

chore: upgrade lerna to v6.5.1

---

website/docusaurus.config.js

https://docusaurus.io/docs/api/themes/configuration#announcement-bar

docs: add announcement bar about the v4 pre-release

---

packages/macro/src/macroJs.ts
packages/macro/test/js-t.ts

fix(macro): more precise check for macro with custom i18n

---

website/docs/ref/vite-plugin.md
website/docs/tutorials/setup-react.md
website/docs/tutorials/setup-vite.md
website/sidebars.ts

docs: Add Vite Setup guide

---

packages/babel-plugin-extract-messages/test/__snapshots__/index.ts.snap
packages/babel-plugin-extract-messages/test/fixtures/js-with-macros.js
packages/macro/__typetests__/index.test-d.tsx
packages/macro/index.d.ts
packages/macro/src/index.ts
packages/macro/src/macroJs.ts
packages/macro/test/js-defineMessage.ts
packages/macro/test/js-t.ts
website/docs/ref/macro.md
website/docs/tutorials/react-patterns.md

```ts
import {defineMessage, msg} from "@lingui/macro"
const msg = defineMessage`Refresh inbox`
// or alias
const msg = msg`Refresh inbox`
```
Rust Version is coming soon (probably by the end of today)

feat(macro): support tagged templates in defineMessage + short alias

---

website/docusaurus.config.js

docs: update v4 announcement link

---

scripts/build/bundles.ts

Fix `packageName` for JSON bundle

fix: correct json bundle packageName

---

packages/format-csv/__typetests__/index.test-d.ts
packages/format-csv/__typetests__/tsconfig.json
packages/format-csv/package.json
packages/format-json/__typetests__/index.test-d.ts
packages/format-json/__typetests__/tsconfig.json
packages/format-json/package.json
packages/format-po-gettext/__typetests__/index.test-d.ts
packages/format-po-gettext/__typetests__/tsconfig.json
packages/format-po-gettext/package.json
packages/format-po-gettext/src/po-gettext.test.ts
packages/format-po-gettext/src/po-gettext.ts
packages/format-po/__typetests__/index.test-d.ts
packages/format-po/__typetests__/tsconfig.json
packages/format-po/package.json
packages/format-po/src/po.test.ts
packages/format-po/src/po.ts
yarn.lock

fixes: https://github.com/lingui/js-lingui/pull/1546

fix(formatters): fix typing inconsistency and add tsd test for each package

---

website/docs/guides/custom-formatter.md
website/docs/ref/catalog-formats.md
website/docs/ref/conf.md

Improved the formats docs a bit

docs: improve formats documentation

---

website/docs/guides/custom-extractor.md

docs: update custom extractor docs

---

.github/workflows/release.yml

Tests now require built packages

ci: fix release WF

---

packages/cli/package.json
packages/cli/src/api/pseudoLocalize.ts
yarn.lock

https://github.com/MartinCerny-awin/pseudolocale/issues/17
Package updated, now it has own TS typings, and build using modern tooling. 

refactor(cli/api): update pseudolocale package

---

website/docs/ref/cli.md
website/docs/tutorials/cli.md

Add references to the 'Message Extraction' guide

docs: add references to the 'Message Extraction' guide

---

packages/cli/src/lingui.ts

fix https://github.com/lingui/js-lingui/issues/1596

fix: resolve package.json with relative path

---

.github/ISSUE_TEMPLATE/bug_report.md

chore: add macro options to issue template

---

packages/extractor-vue/package.json

fix: specify vue-extractor files to be included in the npm package

---

packages/extractor-vue/README.md

fix: vue-extractor readme badges

---

website/docs/guides/custom-formatter.md

docs(custom-formatter): update MessageType

---

README.md
website/blog/2023-04-26-announcing-lingui-4.0/index.md
website/docs/introduction.md
website/docs/misc/resources.md

docs: enhance the announcement blog post and other minor improvements

---

website/docs/misc/react-intl.md

docs: slightly update the 'Comparison with react-intl' article

---

website/docs/misc/i18next.md
website/sidebars.ts

By analogy to an existing article about react-intl

docs: i18next comparison

---

packages/react/src/Trans.test.tsx
packages/react/src/Trans.tsx
website/docs/ref/react.md

minor updated to docs, tests, impl of Trans component

chore: trans improvements

---

packages/babel-plugin-extract-messages/package.json
packages/cli/package.json
packages/core/package.json
packages/detect-locale/package.json
packages/extractor-vue/package.json
packages/format-csv/package.json
packages/format-json/package.json
packages/format-po-gettext/package.json
packages/format-po/package.json
packages/loader/package.json
packages/macro/package.json
packages/react/package.json
packages/vite-plugin/package.json

Trying to improve traffic from npm

chore: extend the npm keywords

---

examples/create-react-app/src/App.tsx
examples/nextjs-swc/README.md
examples/nextjs-swc/package.json
examples/nextjs-swc/src/components/Developers.tsx
examples/nextjs-swc/src/locales/en.po
examples/nextjs-swc/src/locales/es.po
examples/nextjs-swc/src/locales/pseudo.po
examples/nextjs-swc/src/locales/sr.po
examples/nextjs-swc/src/pages/index.tsx
examples/nextjs-swc/yarn.lock

Some of examples get outdated after updating to v4. This PR migrates them to latest version. 
https://github.com/lingui/js-lingui/issues/1673

docs: migrate examples to v4

---

website/docs/releases/migration-4.md

docs(format-po): fix import in v4 migration

---

package.json
packages/core/package.json
packages/core/src/interpolate.test.ts
packages/core/src/interpolate.ts
yarn.lock

Fixes. Unfortunately, it slightly increases a bundle size (for 800bytes) 
https://github.com/lingui/js-lingui/issues/1691

fix(core): don't crash on escaped unicode symbols in messages

---

examples/react-native/.eslintrc.js
examples/react-native/package.json
examples/react-native/yarn.lock
website/docs/tutorials/react-patterns.md

docs: memoization docs update

---

packages/react/package.json
yarn.lock

this doesn't really do much, but it's a preparation for other stuff to come, which I want to bring in gradually.

chore: update react package deps

---

website/docs/misc/resources.md
website/docs/tutorials/react-native.md

docs: minor improvements to RN docs

---

website/docs/tools/crowdin.md
website/docs/tools/introduction.md
website/docs/tools/translation-io.md

docs: update Tools section

---

website/docs/ref/catalog-formats.md
website/docs/releases/migration-4.md

docs: add a note about lingui and raw format IDs in the migration guide

---

website/docs/guides/plurals.md

docs: improve plural docs

---

examples/react-native/package.json
examples/react-native/yarn.lock

chore: update deps in RN example

---

packages/react/src/Trans.tsx
packages/react/src/index.ts

feat(react): export TransNoContext component

---

website/docs/tools/crowdin.md

[New Crowdin logo](https://crowdin.com/blog/2023/07/31/what-is-new-at-crowdin-july-2023#updated-crowdin-logo-unveiled)

docs: new Crowdin logo

---

package.json

chore(size-limit): increase bundle-size budget for react package

---

website/docs/ref/eslint-plugin.md
website/sidebars.ts

docs: add the ESLint plugin info

---

website/docusaurus.config.js

Add the ESLint plugin announcement

docs: add the ESLint plugin announcement

---

website/docs/ref/eslint-plugin.md
website/docs/ref/swc-plugin.md
website/docs/ref/vite-plugin.md
website/docs/tutorials/setup-cra.md
website/docs/tutorials/setup-react.md
website/docs/tutorials/setup-vite.md

docs: enhance plugins' documentation

---

website/docs/tools/crowdin.md

- [Lingui tutorial - Crowdin OTA JS Client](https://crowdin.github.io/ota-client-js/tutorials/lingui/)
- [Lingui String Exporter - Crowdin Marketplace](https://store.crowdin.com/lingui-string-exporter)

docs: add info about Crowdin OTA

---

website/docusaurus.config.js

This reverts commit 398ae58b48926e83a3e09da14595f5aa577c2adf.

revert: "docs: add the ESLint plugin announcement (#1759)"

---

packages/cli/src/extract-experimental/buildExternalizeFilter.ts
packages/cli/test/index.test.ts

Use fs.readFile instead of native import. Adding import assertion to the native import call currently not as easy because requires switching TS nodules compilation to esnext or node16 which is bringing a lot of issues. 
fixes: https://github.com/lingui/js-lingui/issues/1771
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …

fix(experimental-extractor): fix ERR_IMPORT_ASSERTION_TYPE_MISSING issue

---

website/docs/tutorials/react-patterns.md

just a follow up on the recent PR which I didn't get to comment in time :D

docs: wording in react-patterns.md

---

website/docs/ref/core.md

docs: fix typo in `i18n.load()` example

---

website/docs/tutorials/cli.md

While I already believe your documentation is very comprehensive, I added some suggestions to rephrase certain sentences so that missunderstandings are less likely to happen (in my opinion).

docs: suggestive improvements on cli

---

website/docs/tutorials/react-patterns.md

I wish to mention again that the docs are very comprehensive already. Here I added some suggestions to help you improve your docs even more.

docs: suggestive improvements on react patterns

---

website/docs/tutorials/explicit-vs-generated-ids.md

Hereby more suggestive changes to the documentation to help improve them.

docs: suggestive improvements on explicit-vs-generated-ids

---

package.json
yarn.lock

chore: fix build

---

website/src/components/Features.module.scss
website/src/components/PartnerBanner.module.scss
website/src/components/PartnerBanner.tsx
website/src/pages/index.tsx
website/tsconfig.json

docs: add partner banner

---

.github/workflows/docs-suite.yml
.github/workflows/main-suite.yml
.github/workflows/next-sync.yml
.github/workflows/release-docs.yml
.github/workflows/release.yml
packages/cli/src/api/utils.ts

For many of the CI jobs we're using Node 16 which has gotten quite old now.
I updated some jobs to using node LTS (where it's unlikely those jobs would break when the LTS version changes), and bumped some other ones to an explicit node version so that we have the version under our control.

chore: update node in ci

---

packages/format-po/README.md

The "Using custom ID" section was moved to a separate article.

docs: fix link in the format-po readme

---

website/docusaurus.config.js
website/package.json
website/yarn.lock

Add pnpm code blocks to docs
Fixes #1788 

docs: add pnpm code blocks

---

website/docs/misc/resources.md
website/docs/misc/showroom.md
website/docs/misc/tooling.md
website/sidebars.ts

docs: update resources and tooling sections

---

packages/core/src/interpolate.ts

fixes: https://github.com/lingui/js-lingui/issues/1836#issuecomment-1895382633

fix(core): use named instead of default export for unraw lib

---

examples/nextjs-swc/README.md
examples/nextjs-swc/package.json
examples/nextjs-swc/yarn.lock
examples/rspack/README.md

fixes: https://github.com/lingui/js-lingui/issues/1846

chore: update examples

---

website/docs/tutorials/react-native.md
website/docusaurus.config.ts

RN docs changes: Just reacting to something I noticed in discord.
config changes: this makes the config a little stricter than the default

docs: minor update to RN docs

---

packages/react/src/I18nProvider.tsx
packages/react/src/Trans.test.tsx
packages/react/src/Trans.tsx

This is inspired by a question on discord. With an improved error message I hope such questions won't be asked.

refactor: improve error message in Trans

---

packages/cli/src/api/catalog/getCatalogs.test.ts
packages/cli/src/api/catalog/getCatalogs.ts

fix: allow parentheses in catalog pathnames

---

.github/workflows/main-suite.yml
.github/workflows/release-test.yml
.github/workflows/size-limit.yml

Upgrade actions used in workflows, as the node versions below 20 are deprecated. The only `andresz1/size-limit-action` remains with a warning because there is no corresponding release ([andresz1/size-limit-action#110](https://github.com/andresz1/size-limit-action/issues/110))
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …

ci: upgrade actions

---

packages/react/build.config.ts

Add "use client" to the whole react entrypoint with `Trans` and `I18nProvider` (`TransNoContext` is included in another bundle)
https://github.com/lingui/js-lingui/pull/1899

feat(react): add "use client" for react bundle

---

website/docs/misc/showroom.md

* Remove 3 dead links from showroom
* Add [lefun.fun][0] to showroom. It's an online board game platform. The platform itself is multi-language but game developers can also make their games multi-language; the games (along with their translations) remain decoupled from the platform. I had to bend lingui a little to make it work but it succeeded where other more popular i18n frameworks failed!
[0]: https://lefun.fun

docs: add https://lefun.fun to showroom

---

packages/react/src/TransRsc.tsx
packages/react/src/index-rsc.ts
packages/react/src/server.ts

This is a refactor of the recently added RSC functionality. It makes some small changes:
1) memory efficiency: previously, every call  to `useLingui` and `TransRsc` would allocate memory. With this change, the necessary memory is allocated once (well, depends on how many times `setI18n` is called, but it won't be much) for each request and reused across all `useLingui` and `TransRsc`
2) it appears `defaultComponent` was not considered by RSC so I added it. I still need to test it but if we ignore it, I'm afraid some users would get hydration mismatches
[//]: # (_Put …

refactor: minor improvements to RSC

---

website/package.json
website/src/components/Header.tsx
website/yarn.lock

docs: update docusaurus

---

packages/cli/src/api/catalog/extractFromFiles.ts
packages/cli/test/extract-po-format/expected/en.po
packages/cli/test/extract-po-format/expected/pl.po
packages/cli/test/extract-po-format/fixtures/file-a.ts
packages/cli/test/index.test.ts

Fix default message extraction
Fixes #1921

fix: default message extraction

---

website/docs/tutorials/setup-vite.md

docs: add missing dependency @lingui/vite-plugin in instruction

---

examples/remix-vite-babel/README.md
website/docs/misc/resources.md

docs: add more info about Remix.run

---

website/docs/releases/migration-5.md
website/sidebars.ts

This first draft covers some of the most important parts of the **v5 release**. The description may be inaccurate and needs further polishing.

docs: initial draft of the Lingui v5 migration guide

---

packages/cli/package.json
yarn.lock

Upgrade `cli-table` version in `@linqui/cli` to MIT licensed version
Fixes #1966

chore(cli): updgrade cli-table version to licensed version

---

examples/nextjs-swc/src/app/[lang]/layout.tsx
examples/nextjs-swc/src/appRouterI18n.ts
examples/nextjs-swc/src/withLingui.tsx

Changing the current code to `getI18nInstance` which prints a warning for unexpected cases helps with debugging in case of issues

chore: introduce getI18nInstance to nextjs example

---

packages/babel-plugin-extract-messages/src/index.ts
packages/babel-plugin-extract-messages/test/index.ts

fixes https://github.com/lingui/js-lingui/issues/1974

fix(extractor): fix warning when `key` used on Trans macro

---

packages/cli/src/api/help.ts

When using pnpm the cli still suggests npm:
This PR adds support for pnpm:

fix(cli): add pnpm detection to command suggestions

---

website/docs/ref/extractor-vue.md

docs: Update extractor-vue.md

---

website/docs/ref/cli.md
website/docs/tutorials/react-native.md
website/docs/tutorials/react-rsc.md
website/src/components/Header.tsx

minor improvements to docs
- RSC: align more with the example app change from https://github.com/lingui/js-lingui/pull/1987
- React Native improvement, performance recommendation

docs: minor tweaks and improvements

---

website/docs/tutorials/setup-vite.md

docs: add SWC compatibility note for Vite guide

---

packages/cli/src/api/catalog/getCatalogs.test.ts
packages/cli/src/api/catalog/getCatalogs.ts

fix: escape nested brackets

---

website/docs/misc/showroom.md

Add [Rove.me](https://rove.me) to showroom.
Our team chose Lingui to localize the website for travelers all around the world. We support 6 languages: English (source), German, French, Spanish, Portuguese and Italian. Hundreds of messages are translated including plurals and date formatting. It's easy to manage extracted strings exporting PO files to Crowdin. Although Lingui is handy and quite obvious to integrate into "classic" React SPA, it took some effort to us using the lib in combination with React Server Components. Hopefully, there is a working project …

docs: Add Rove.me to showroom

---

packages/babel-plugin-lingui-macro/src/macroJs.ts
packages/babel-plugin-lingui-macro/test/__snapshots__/js-useLingui.test.ts.snap
packages/babel-plugin-lingui-macro/test/js-useLingui.test.ts

related: https://github.com/lingui/swc-plugin/issues/106#issuecomment-2295951277

feat: allow to use useLingui with only i18n

---

website/docs/ref/eslint-plugin.md

The ESLint plugin now supports Flat Config.

docs: update ESLint plugin documentation

---

website/src/components/Features.module.scss
website/src/components/Features.tsx
website/src/components/Header.module.scss
website/src/components/Header.tsx
website/src/components/PartnerBanner.module.scss
website/src/components/PartnerBanner.tsx
website/src/components/Users.module.scss
website/src/components/Users.tsx
website/src/css/custom.scss
website/src/pages/index.tsx

- removed a bunch of custom CSS
- updated some texts on the main page

style(docs): minor refreshment of documentation styles

---

packages/conf/src/__snapshots__/index.test.ts.snap
packages/conf/src/index.test.ts
packages/conf/src/makeConfig.ts

feat: remove deprecated extractBabelOptions

---

website/docs/ref/macro.mdx

In this PR I have reorganized the `@lingui/macro` article. Some parts have been rearranged, rewritten or paraphrased. A few duplicates have been merged.
In the context of the recent changes (React and Core macros moved to their respective packages), I think the next step would be to split the content of this page between Introduction (Describing the concept in general), `@lingui/core` and `@lingui/react`.
🖼️ See the [Deployment Preview](https://js-lingui-git-docs-macro-article-refinement-crowdin.vercel.app/ref/macro).
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …

docs: `@lingui/macro` article refinement

---

packages/cli/src/api/extractors/babel.ts
website/docs/guides/custom-extractor.md

Fixes https://github.com/lingui/js-lingui/issues/2057 and improve documentation to shed a light on some previously taken decision. 

feat(extractor): support `decoratorAutoAccessors` and improve docs

---

website/docs/tutorials/react-native.md

closes #2066
this makes the guide in line with example code

docs: update react native guide according to example

---

website/docs/guides/dynamic-loading-catalogs.md
website/docs/guides/explicit-vs-generated-ids.md
website/docs/guides/message-extraction.md
website/docs/guides/message-format.md
website/docs/guides/plurals.md
website/docs/guides/pseudolocalization.md
website/docs/guides/testing.md
website/docs/releases/migration-4.md

🖼️ [Deployment Preview](https://js-lingui-git-docs-guides-crowdin.vercel.app/)

docs: Guides section improvements

---

website/docs/misc/community.md
website/docs/misc/i18next.md
website/docs/misc/react-intl.md
website/docs/misc/resources.md
website/docs/misc/showroom.md
website/docs/misc/tooling.md
website/docusaurus.config.ts
website/src/components/Users.tsx

🖼️ [Deployment Preview](https://js-lingui-git-docs-resources-crowdin.vercel.app/)

docs: Resources section improvements

---

README.md
packages/cli/README.md
packages/conf/README.md
packages/core/README.md
packages/detect-locale/README.md
packages/extractor-vue/README.md
packages/format-csv/README.md
packages/format-json/README.md
packages/format-po-gettext/README.md
packages/format-po/README.md
packages/loader/README.md
packages/macro/README.md
packages/message-utils/README.md
packages/metro-transformer/README.md
packages/react/README.md
packages/vite-plugin/README.md

Just a small cleanup and normalization.

chore: update README files

---

.prettierignore
lerna.json
package.json
yarn.lock

build(deps): use the latest Lerna version (8.x)

---

website/docs/releases/migration-5.md

Was slightly confused to see `msg` was no longer in the macro API.
Sections below imply it still is.
Re-adding it here for completeness.

docs: re-add `msg` to v4 -> v5 migration docs

---

packages/cli/src/api/stats.ts
packages/cli/test/index.test.ts

Closes https://github.com/lingui/js-lingui/issues/2093
The test is fairly basic, I skipped the directory compare since I only care about the console output.

fix: don't report statistics for pseudo locale 

---

packages/metro-transformer/package.json
yarn.lock

build(deps): fix metro transformer deps

---

website/docs/releases/migration-5.md

docs: add v4 documentation link

---

packages/react/package.json
yarn.lock

feat(react): add support for React 19

---

packages/core/package.json
packages/macro/package.json
packages/react/package.json
yarn.lock

build(deps): fix peerDependencies

---

packages/babel-plugin-extract-messages/src/index.ts

Fixes: https://github.com/lingui/js-lingui/issues/2105

fix: don't use anything from "@babel/types" in runtime

---

package.json
packages/cli/src/lingui-compile.ts
packages/cli/src/test/compile.test.ts

chore: fix prettier and eslint warnings

---

package.json
yarn.lock

chore(deps): update size-limit

---

website/docs/tutorials/react.md

docs: fix import statement in the code sample

---

examples/create-react-app/.babelrc
examples/create-react-app/package.json
examples/create-react-app/src/locales/cs.po
examples/create-react-app/src/locales/en.po
examples/create-react-app/yarn.lock

Updates create react app dependencies for lingui v5

docs(examples): Updates create react app to use lingui v5

---

examples/nextjs-swc/next.config.ts
examples/nextjs-swc/package.json
examples/nextjs-swc/src/app/[lang]/app-router-demo/page.tsx
examples/nextjs-swc/src/app/[lang]/layout.tsx
examples/nextjs-swc/src/app/[lang]/page.tsx
examples/nextjs-swc/src/components/HomePage.tsx
examples/nextjs-swc/src/locales/en.po
examples/nextjs-swc/src/locales/es.po
examples/nextjs-swc/src/locales/pseudo.po
examples/nextjs-swc/src/locales/sr.po
examples/nextjs-swc/yarn.lock

- Makes the example buildable - adds the webpack loader, fixes lint issues preventing the build 
- Replaces deprecated code - usage of the v4 macros in head instead of lazy translations and message descritptors
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

docs(examples): make example buildable and replace deprecated code

---

website/src/components/Header.tsx

Fixes a small typo in the home page of Lingui

chore(docs): fix 'internalization' typo on home page

---

packages/cli/src/lingui-compile.ts
packages/cli/src/test/__snapshots__/compile.test.ts.snap
packages/cli/src/test/compile.test.ts

fix(cli): catalogsMergePath generates only one compiled locale

---

package.json
packages/babel-plugin-extract-messages/package.json
packages/babel-plugin-lingui-macro/package.json
packages/cli/package.json
packages/conf/package.json
packages/core/package.json
packages/detect-locale/package.json
packages/extractor-vue/package.json
packages/format-csv/package.json
packages/format-json/package.json
packages/format-po-gettext/package.json
packages/format-po/package.json
packages/jest-mocks/package.json
packages/loader/package.json
packages/macro/package.json
packages/message-utils/package.json
packages/metro-transformer/package.json
packages/react/package.json
packages/remote-loader/package.json
packages/vite-plugin/package.json

This PR standardizes the `repository` field format across all `package.json` files in the monorepo to follow npm best practices https://docs.npmjs.com/cli/v10/configuring-npm/package-json#repository
- Updated repository URLs from `https://` to `git+https://` format
- Added `directory` field to all package repository objects  
- Converted string-format repositories to proper object format
- Ensures consistency across all 20+ packages
[//]: # (_Put an `x` …

fix: standardize repository field format across all packages

---

README.md
website/docusaurus.config.ts
website/package.json
website/yarn.lock

This PR adds an `llms.txt` file to the Lingui documentation to provide context for AI/LLM tools and improve their understanding of the project. This file will help AI assistants provide more accurate and relevant responses when users ask questions about Lingui.
- [llms.txt](https://js-lingui-git-docs-llms-txt-crowdin.vercel.app/llms.txt)
- [llms-full.txt](https://js-lingui-git-docs-llms-txt-crowdin.vercel.app/llms-full.txt)
- [The /llms.txt file](https://llmstxt.org/)
- [`signalwire/docusaurus-plugin-llms-txt`](https://www.npmjs.com/package/@signalwire/docusaurus-plugin-llms-txt)

docs: add llms.txt and llms-full.txt support

---

packages/cli/src/api/catalog.test.ts
packages/cli/src/api/catalog/extractFromFiles.ts
packages/cli/src/api/fixtures/collect-placeholders-sorting/a.ts
packages/cli/src/api/fixtures/collect-placeholders-sorting/b.ts
packages/cli/test/extract-po-format/expected/en.po
packages/cli/test/extract-po-format/expected/pl.po

Added sorting and test for placeholders
Fixes https://github.com/lingui/js-lingui/issues/2306

fix(extractor): sort placeholders to keep them stable between runs
