- packages/lingui-cli/src/lingui-compile.js
> fix: Return empty string when fallbackLaguage is empty

- packages/lingui-react/src/I18nProvider.js
Now with react 16 it is possible to return a string from a component and lingui supports it by accepting `null` as a value of the `defaultRender` param on `I18nProvider`.
However, if you pass `null`, you will receive a warning, saying "Failed child context type: The child context `linguiDefaultRender` is marked as required in `I18nProvider`, but its value is `null`."
This PR removes the .isRequired param, which would prevent this warning when `defaultRender` is `null`
> Remove .isRequired flag on linguiDefaultRender context type

- docs/guides/dynamic-loading-catalogs.rst
- `newProps` -> `nextProps`
- remove `data` from folder path.
Also there's another thing that I had to change to get the example working:
``` js
// Doc version
loadCatalog = async (language) => {/* ... */}
// My version
async loadCatalog(language) {/* ... */}
```
The reason for that change is that in the doc version, the arrow function doesn't have any `this` bound to it. I can also change that in the PR if you also experienced some troubles with it.
> Fix doc typos

- docs/tutorials/cli.rst
The folder is named `ref`, not `refs`
Dead links are [here](https://lingui.github.io/js-lingui/tutorials/cli.html#further-reading)
> Fix dead links

- docs/guides/dynamic-loading-catalogs.rst
Documentation still mentions the old `lingui-loader` which uses <2.0.0 version of lingui-cli.
It fails to work completely if installed like `npm install --save lingui-loader` and that's very likely what many people will do when reading about "The recommended way is compile messages on-the-fly using lingui-loader".
> Correcting documentation on the lingui-loader module

- docs/guides/plurals.rst
Using `count` will throw an error from the babel plugin `Value argument is missing.`
> Update plural documentation to use value instead of count

- packages/cli/src/lingui-compile.js
my locale files are written with an hyphen, thanks to #219.
unfortunately `lingui compile` doesn't support them yet,
this fixed it on my project. 😄 
---
this was the log emitted before the changes.
```
Error: Invalid locale en-US (missing plural rules)!
Error: Invalid locale pt-BR (missing plural rules)!
Error: Invalid locale zh-CN (missing plural rules)!
```
they are all supported by `make-plural` package.
> support locales with hyphens in cli compile

- packages/cli/src/api/__snapshots__/extract.test.js.snap
- packages/cli/src/api/extract.js
- packages/cli/src/api/extract.test.js
- packages/cli/src/lingui-extract.js
This is my try to implement #229.
- I did not work with ramda before, so I am sure there is a better way to implement `orderByMessageId`.
- Only a part of the tests ran locally for me, so I'm going to see what CI says
- I also did not test the actual output of the built command, since the build failed for me locally
- Feel free to completely discard this if there is a better way to implement it 😄
> Order extracted messages alphabetically by message ID

- packages/babel-plugin-extract-messages/src/index.js
- packages/cli/src/api/formats/utils/locales.js
> Remove obsolete files when extracting messages

- packages/babel-plugin-extract-messages/src/index.js
- packages/babel-plugin-extract-messages/test/index.js
- packages/cli/src/api/utils.js
- packages/cli/src/lingui-extract.js
- packages/cli/test/index.js
- scripts/build/results.json
> Handle duplicate filenames of intermediate catalogs

- CHANGELOG.md
- docs/ref/cli.rst
- docs/tutorials/react.rst
- packages/cli/package.json
- packages/cli/src/lingui-init.js
- packages/cli/src/lingui-init.test.js
- packages/cli/src/lingui.js
- packages/cli/src/mocks.js
- yarn.lock
This command installs all required packages based on project type (e.g. React vs VanillaJS). In future it should also support bootstrapping config, adding patterns to `.gitignore`, etc.
> Add lingui init command

- packages/cli/src/api/compile.js
- packages/loader/test/__snapshots__/loader.test.js.snap
This change improves support for non-ejected `create-react-app` apps by effectively disabling eslint in generated build artefacts (`.js` catalog files).
> Disable eslint in generated message catalog files

- packages/cli/package.json
- packages/cli/src/api/__snapshots__/utils.test.js.snap
- packages/cli/src/api/utils.js
- packages/cli/src/api/utils.test.js
- packages/cli/src/lingui.js
- yarn.lock
> fix #271 - give feedback for unrecognized commands

- docs/guides/plurals.rst
I'm not sure how these doc links are supposed to work, but I'm guessing the bracket types should be flipped :sweat_smile:.
> Fix Markdown link

- CONTRIBUTING.md
- docs/tutorials/react-native.rst
hi! I have noticed there were some changes to the RN docs and noticed some minor problems. This should fix them. If you're updating the docs in the future, I can do a review for them if you like.
also, does js-lingui provide an easy way to migrate from "i18n.t`mark messages as read`" to "i18n._(t`mark messages as read`)"? I didn't notice this change happening, what was the reason for it? (the old api is nicely compact). Thanks!
> fixes to react native docs

- docs/tutorials/react-patterns.rst
the diff looks big, but it's just because I moved things around a little
edit: there is a lot of talk about automatic message ids (taken from the translations) vs custom message IDs. What I'm missing is a discussion about why I would like to use one over the other..? Listing some pros and cons would be nice.
> Review react-patterns for v3

- packages/cli/src/api/extract.js
Hello! Thanks so much for this project. It's been a pleasure to integrate so far. However, my project has an unconventional use case that would benefit from symlinks in srcPathDirs being followed so I'm wondering if we can make a minor change to the extract api.
My understanding is that `lstatSync` only differs from `statSync` in that it does not follow symlinks. This change would allow symlinked directories to be read since isDirectory() would now return true and readdirSync already works for symlinks.
> Allow symlinks in srcPathDirs config for extract cli

- packages/cli/package.json
- packages/cli/src/api/extractors/babel.js
Should fix #359 by emphasis on documentation and peer dependencies rather than forcing babel plugin macros which should already be present
> Remove "macros" from the list of cli babel plugins

- packages/macro/src/js.js
- packages/macro/test/fixtures/select/actual.js
- packages/macro/test/fixtures/select/expected.js
Babel macros generates invalid ICU messages for nested select/plural.
Example source code:
```js
select('id', {
value: "male",
male: select({
value: true,
true: "He invites guests",
other: "He does not invite guests"
}),
female: `She is ${gender}`,
other: `They is ${gender}`
});
```
Expected message:
```
{0, select, male {{1, select, true {He invites guests} other {He does not invite guests}}} female {She is {gender}} other {They is {gender}}}
```
Actual message (missing brackets after `male`):
```
{0, select, male {1, select, true {He invites guests} other {He does not invite guests}} female {She is {gender}} other {They is {gender}}}
```
`lingui complie` throws error for this message:
```
Error: Can't parse message. Please check correct syntax: "{0, select, male {1, select, true {He …
```
> fix: macros generates invalid ICU message for nested selects

- packages/babel-plugin-extract-messages/src/index.js
- packages/babel-plugin-extract-messages/test/__snapshots__/index.js.snap
- packages/babel-plugin-extract-messages/test/fixtures/js/macro.js
`lingui extract` ignores messages with leading space in description comment.
Example source code:
```js
/* i18n: description */t`Message`
```
Expected messages:
```
{
"Message": {
"translation": "Message",
"description": "description",
"origin": [
[
"test.js",
1
]
]
}
}
```
Actual messages:
```
{}
```
> fix: allow leading space in i18n description comments

- docs/guides/typescript.rst
`@types/lingui__macro` exists, but is not listed in the docs. Not sure, but I'd guess it's safe to add it. Review much appreciated.
> Typescript docs: @types/lingui__macro installation

- docs/tutorials/react.rst
I was bitten by the context caveat as described in the official react docs: https://reactjs.org/docs/context.html#caveats.
Quote from the docs:
> Because context uses reference identity to determine when to re-render, there are some gotchas that could trigger unintentional renders in consumers when a provider’s parent re-renders.
I understand that in the original example, the `<App>` can never rerender, so the context caveat actually doesn't apply. However, there's a significant performance hit when users of the lib copy/paste the `<I18nProvider>` snippet into a component that _does_ update. This will cause **all** `<Trans>` components in the entire app to rerender.
> Update docs to account for Context caveat

- packages/cli/src/api/compat.js
- packages/cli/src/api/extractors/babel.js
- packages/cli/src/api/extractors/typescript.js
I use this approach in `next` branch and it works fine. In `next` branch I would probably make `@babel/core` the default one.
> Show hint for missing babel-core package

- packages/cli/index.js
- packages/cli/src/api/compat.js
- packages/cli/src/lingui-add-locale.js
I encountered a problem where lingui thought I needed to install `babel-core` version 6 however the actual problem was being obscured because the error message which prompts lingui to log these instructions is not itself shared with the developer.
The actual problem I was having was that the lib `babel-preset-react-app` was not up-to-date, so the instructions to "please install missing Babel 6 core package" were misleading.
This PR makes the Babel compat. messages also print the original error in order to help people debugging cases like this.
Thanks for a great library!
Edit: Let me know what needs to be done re: tests and I will fix up the PR accordingly.
> Log original error with Babel compatibility info

- packages/cli/src/api/pseudoLocalize.js
- packages/cli/src/api/pseudoLocalize.test.js
Updated pseudolocale regex in order to take into account variable names. 
Previously the string: ```replace {count}``` would have been replaced with ```ŕēƥĺàćē  {ćōũńţ}```.
This would introduce an issue at runtime when the interpolator tries to find the variable ```ćōũńţ``` in the current variables context which does not exists.
With this change the variable names remain intact and the translation message is created as such: ```ŕēƥĺàćē {count}```
> fix: made pseudolocales to take into account variable names

- packages/cli/src/api/pseudoLocalize.js
- packages/cli/src/api/pseudoLocalize.test.js
Fixes issue #427.
Depends on PR #419 - the test added here will fail on this branch until that PR is incorporated.
This fix will still fail in the case that a variable placeholder in a template string inside a `plural` macro is followed by a single word which matches one of the plural rules, e.g. `{count, plural, one {{countString} other} other {{countString} others}}`.
This is a much more extreme edge case, though - it must be
1. A template string
1. Inside a `plural` expression
1. With a variable placeholder
1. Followed by `zero|one|two|few|many|other`
1. With no other words or punctuation after that word
1. With pseudolocalization enabled
IMO this is an acceptable tradeoff for a more readable regular expression.
> Issue #427: fix edge case bug in plural pseudolocalization

- docs/guides/testing.rst
Hey there,
The current testing example is a little bit problematic, especially when you want to mount and test stateful components.
Enzyme's mount gives you access only to the root component's state. That means that by doing: `<I18nProvider><YourComponent /></I18nProvider>` you can't access `YourComponent`'s state for testing.
In `react-intl`, we were using a higher order component [taken from this gist](https://gist.github.com/mirague/c05f4da0d781a9b339b501f1d5d33c37/), which extracts the context from the provider and passes it down to the component tree. That solves the issue, and makes testing great again (:yikes:).
We have adapted that solution for the I18nProvider and it works great for us.
I updated the documentation, and I hope you also find it useful.
Cheers 🍻
> Update testing example

- docs/tutorials/javascript.rst
Otherwise, you'll get an error:
```
Metro Bundler ready.
Loading dependency graph, done.
error: bundling failed: ReferenceError: Unknown plugin "macro" specified in
{{ a bunch of line errors }}
...
```
> Fix typo on macro Babel plugin config

- packages/conf/src/index.js
Currently, lingui complains with option validation issues if you attempt to use the `extends` or `rootMode` babel options. In a monorepo, with Babel 7, you often want message extraction to happen in each module, but using a common babel configuration that exists in a top level "workspace"
We should allow these options without throwing warnings. I'm not sure we should actually have any validation on the babel options (since whats allowed depends on babel version, and theres not much need to limit he feature set) so potentially, this validation could be removed entirely.
> Don't prevent babel options to help setup lingui in monorepos

- packages/macro/src/js.js
- packages/macro/test/fixtures/t/actual.js
- packages/macro/test/fixtures/t/expected.js
To use a literal backtick in a template string (such as for markdown code blocks), it needs to be escaped (```const str = `\``;```).
Unfortunately, this gets picked up as ``\\` `` due to `value.raw`, which ends up as a literal ``\` `` in the translation string.
In turn, this leads to final translation strings ending up with the literal ``\` ``, which is broken syntax, throwing a `Error: Can't parse message. Please check correct syntax"`.
This PR provides a quick fix for the issue, allowing backticks to be used.
> Fix escaped backticks in macro-transformed template strings

- docs/ref/cli.rst
- packages/cli/src/api/pseudoLocalize.test.js
- packages/cli/src/lingui-add-locale.js
- packages/cli/src/lingui-compile.js
- packages/cli/src/lingui-extract.js
- packages/conf/src/index.js
- packages/conf/src/index.test.js
I have an advanced configuration scenario that requires multiple locale targets and with multiple source directories. I want to end up with multiple catalogs that are loaded in different circumstances.
Presently, I work around the obvious config issue by swapping out my .linguirc file in between runs of `lingui extract` and `lingui compile`. This isn't ideal and I thought lingui might benefit from a CLI  option to specify a configuration file.
This change allows a `--config <path>` option on add-locale, compile, and extract commands. If the path exists, I use `cosmiconfig#loadSync` instead of the normal config file probe.
If you find this change welcome, I can work more to add details to the docs.
- Adding a new option could make each command to be perceived as slightly more complex
> Optional --config argument for advanced configuration scenarios

- packages/cli/src/api/extractors/typescript.js
This fixes an issue where 'babel-plugin-syntax-jsx' cannot be resolved
when using strict package managers such as pnpm or yarn pnp:
```
> project@1.0.0 lingui:extract /path/to/project
> lingui extract
/path/to/project/temp/node_modules/.registry.npmjs.org/@lingui/cli/2.7.4/27dd1e49dd60dcd69cab3f50f64bc261/node_modules/@lingui/cli/api/compat.js:56
throw e;
^
Error: Cannot find module 'babel-plugin-syntax-jsx' from '/path/to/project'
at Function.module.exports [as sync] (/path/to/project/temp/node_modules/.registry.npmjs.org/resolve/1.10.1/node_modules/resolve/lib/sync.js:58:15)
at resolveStandardizedName (/path/to/project/temp/node_modules/.registry.npmjs.org/@babel/core/7.4.3/node_modules/@babel/core/lib/config/files/plugins.js:101:31)
at resolvePlugin …
```
> Resolve babel-plugin-syntax-jsx relative to the @lingui/cli package

- packages/cli/src/api/__snapshots__/extract.test.js.snap
- packages/cli/src/api/extract.js
- packages/cli/src/api/extract.test.js
I couldn't run test on my PC so I'll use this CI for this now.
Fixes #490
> Don't warn about duplicate default message if it's empty

- packages/cli/src/lingui-add-locale.js
- packages/cli/src/lingui-compile.js
- packages/cli/src/lingui-extract.js
- packages/conf/src/index.js
- packages/conf/src/index.test.js
- packages/loader/package.json
- packages/loader/src/index.js
- packages/loader/test/compiler.js
- packages/loader/test/customconfig
- packages/loader/test/loader.test.js
Processing process.argv inside getConfig can cause problems when used in conjunction with @lingui/loader since the --config arg is also used by webpack
Instead of processing process.argv, getConfig now accepts the path to a custom config file. Each command now passes the config option from commander into getConfig. Webpack loader now accepts an option "config" that can be used to specify a config file.
Should all lingui options be allowed via webpack loader options? loader could be modified to assign all options to getConfig output.
I think I fixed an unrelated bug with lingui/loader. compileNamespace and pseudoLocale config options  were not being passed to createCompiledCatalog, so I assume that all loader compiled output was being exported as cjs.
I smoke tested the fix by implementing …
> Fixes --config option processing

- packages/cli/src/api/compile.test.ts
- packages/core/src/i18n.test.ts
Syntax escaping is supported by ICU MessageFormat by using apostrophes http://userguide.icu-project.org/formatparse/messages#TOC-Quoting-Escaping
The bug that caused #457 has already been fixed in the `next` branch.
This PR adds some tests to prevent regressions.
> test: Add tests to check for escape apostrophes

- docs/misc/tooling.rst
A few days ago I published a storybook addon for lingui to support the dev experience 
And as requested from https://github.com/lingui/js-lingui/issues/413
[storybook-addon-linguijs](https://www.npmjs.com/package/storybook-addon-linguijs) in now listed under`docs/misc/tooling.rst`.
i hope it helps
> (docs:misc/tooling) Added storybook-addon within docs/misc/tooling.rst

- packages/cli/src/lingui-compile.ts
This PR for `next` branch (v3.0.0).
Something strange happens with my setup:
```txt
$ yarn compile                 
yarn run v1.15.2
$ lingui compile
/Users/nodkz/www/_npm/lingui-express-middleware/examples/simple/node_modules/@lingui/cli/lingui-compile.js:30
if (noMessages(catalogs)) {
^
TypeError: noMessages is not a function
at command (/Users/nodkz/www/_npm/lingui-express-middleware/examples/simple/node_modules/@lingui/cli/lingui-compile.js:30:7)
at Object.<anonymous> (/Users/nodkz/www/_npm/lingui-express-middleware/examples/simple/node_modules/@lingui/cli/lingui-compile.js:115:17)
at Module._compile (internal/modules/cjs/loader.js:689:30)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
at Module.load (internal/modules/cjs/loader.js:599:32)
at tryModuleLoad …
```
> fix(cli): noMessages is not a function

- docs/ref/conf.rst
- packages/cli/src/api/__snapshots__/extract.test.js.snap
- packages/cli/src/api/extract.js
- packages/cli/src/api/extract.test.js
- packages/cli/src/api/types.js
- packages/cli/src/lingui-extract.js
- packages/conf/src/index.js
This is a proposal to add a config option `sorting` to expose a new sort by origin feature.
Unfortunately, `master` is in a rather bad state with a bunch of failing tests. Let me know what I can do to help.
Context https://github.com/lingui/js-lingui/issues/562
> Add optional sort by origin/filename

- packages/cli/package.json
With TS 3.7 the new syntax for optional chaining and nullish coalescing is added. Because cli depends on TS 2.9.2, it's not able to parse it. I think that moving TS as peer dependency is a safe option here. I did not dare to update in devDependencies, but it's unlikely it would break anything.
> [cli] Move typescript dependency to peer

- packages/react/src/format.js
- packages/react/src/format.test.js
#593 Adds support for reusing the same tag multiple times in the same line in the same scope.
Given a message: `"msg": "<0>first</0> second <0>third</0>"`, used with `<Trans id="msg" components=[{<sup />}] />`
We expect: `<sup>first</sup> second <sup>third</sup>`
In practice we get: `<sup>first&lt;/0&gt; second &lt;0&gt;third</sup>`
Current: https://regex101.com/r/LHoVEP/2
New: https://regex101.com/r/LHoVEP/1
> #593: lazily split messages by value tags

- packages/core/index.js
- packages/react/src/I18nProvider.js
- packages/react/src/I18nProvider.test.js
- packages/react/src/Select.js
- packages/react/src/Select.test.js
Currently, `Flow` isn't actually checking any type imported from `core` due to its root-level `index.js` file missing a `@flow` header. Fixing this revealed a few more errors which I also included fixes for in this branch.
Not all tests are passing in this branch; however all failing tests also fail on `master`, so I'm just ignoring them for now.
> Fix issues with Flow type checking

- docs/ref/conf.rst
- packages/cli/src/api/catalog.js
- packages/cli/src/api/formats/lingui.js
- packages/cli/src/api/types.js
- packages/conf/src/index.js
- scripts/build/results.json
Adds configuration object `formatOptions` with key `origins`. The object is passed to the format's `write()` in the third param.
To turn off line numbers in catalogue files, configure `.linguirc` as follows:
```
"formatOptions": {
"origins": false
}
```
> #587: Optional line numbers for lingui format

- packages/cli/src/api/extractors/typescript.js
Should solve the problem when there is no TS used, but `TypeScript` is required - #599
> Use lazy require to import TypeScript

- packages/react/src/withI18n.js
Hello guys,
I don't know how that works for others, but the existing flow types in withI18n throw a lot of errors in our project.
I figured out that the proposed change fixes this.
As far as I understand flowtype and the withI18n component, the return type is indeed `React.ComponentType<$Diff<P, withI18nProps>>` and not an intersection of `C` and the above.
Please take a look if it makes sense for you too.
> Fix flow types on withI18n

- docs/tutorials/cli.rst
Fixed typo in CLI example.
https://lingui.js.org/tutorials/cli.html
> docs: Fixed typo in CLI example

- docs/tutorials/react.rst
One of the code samples provided in the tutorials looks wrong:
```js
{
messagesCount === 1
? "There's {messagesCount} message in your inbox."
: "There're {messagesCount} messages in your inbox."
}
```
It seems that the `messageCount` variable was meant to be interpolated:
```patch
{
messagesCount === 1
-    ? "There's {messagesCount} message in your inbox."
+    ? `There's ${messagesCount} message in your inbox.`
-    : "There're {messagesCount} messages in your inbox."
+    : `There're ${messagesCount} messages in your inbox.`
}
```
> Fix a code sample

- docs/guides/excluding-build-files.rst
I was following this [document](https://lingui.js.org/tutorials/setup-cra.html) and `localeDir` is written as `locales`. 
so is `locales` better than `locale`?
> Is locales better?

- docs/tutorials/react-patterns.rst
I've introduced several people to Lingui, and I find they often have the same questions about what the docs describe as "lazy translations". Which I take to mean, use-cases where the default translation can _not_ be placed inline in a `<Trans>` or `i18n._()` in the code location where the message will be displayed.
So, I'm submitting some changes for this section of the docs. This includes:
* Changing the example to use the names of colors instead of languages. (I find that newcomers are often confused by the language names, into thinking the example has something to do with selecting a translation language catalog)
* Referring more explicitly to the "message descriptor" objects created by the `t` macro, so that it's more obvious what is being put into variables and passed around.
* Added …
> Expand and clarify "lazy translation" patterns

- packages/cli/package.json
Currently when using `next`, the user has to add `fs-extra` to their package.json since the CLI is using it (in `catalog.ts`), but it's not listed as a dependency.
> Add fs-extra to package.json for CLI which is using it.

- docs/ref/cli.rst
- docs/tutorials/cli.rst
- packages/cli/src/lingui.ts
Even though `add-locale` is deprecated, it's probably better to keep in the CLI so it can show deprecation message. I was fairly confused myself when I tried to run it and it was giving me rather cryptic error messages.
Also `init` command is some thing of the past, so I removed it from there.
> Enable add-locale with deprecation message

- packages/macro/index.d.ts
It bugged me that `plural` macro accepts `Object` instead of correct options. And I slightly improved small things around. Also removed `defineMessages` declaration which no longer exists, does it?
> Improve macro typings

- packages/core/src/i18n.ts
- packages/core/src/index.ts
This is required because we are [importing it in `@lingui/macro`](https://github.com/lingui/js-lingui/blob/next/packages/macro/index.d.ts#L2) but it wasn't exported in the `@lingui/core` package, causing it to be treated as `any` and forcing users to use the `skipLibCheck` compiler option in their `tsconfig.json`.
> Export MessageDescriptor interface in core package

- packages/cli/src/lingui-compile.ts
`AllMessages` is a map from locale to messages, but this is the type for an individual, compiled locale.
> fix: type of compiled messages

- packages/macro/src/macroJsx.ts
- packages/macro/test/jsx-trans.ts
The JSX attributes contain expressions which contain literals. The current accessor is missing the expression dereference,
Fixes #604
> Fixes maybeNodeValue

- packages/macro/src/icu.ts
- packages/macro/test/jsx-trans.ts
- this adds explicit handling of JSXEmptyExpression within
packages/macro/src/icu.ts, where the token is skipped over entirely
- Fixes #684
> fix: Support comments inside JSX macros by ignoring empty jsx expressions

- packages/cli/package.json
- packages/cli/src/api/formats/__snapshots__/csv.test.ts.snap
- packages/cli/src/api/formats/csv.test.ts
- packages/cli/src/api/formats/csv.ts
- packages/cli/src/api/formats/fixtures/messages.csv
- packages/cli/src/api/formats/index.ts
- yarn.lock
I don't actually like the csv format, however in my current situation, the translators only accept csv files for convenience, and I have to convert the po file into csv and convert it back when the translation is ready. I'm not familiar with ramda, not sure if some of the code can be replaced by using ramda.
> Feature: add csv support

- packages/cli/src/api/extract.ts
When reading the files in a directory in order to extract translation strings, the order in which the files are returned varies based on OS, sometimes resulting in unnecessary diffs when extraction is performed on different operating systems.
(Basically the same thing as pull request #694 but for the `next` branch)
> CLI: Explicitly sort directory listings

- docs/tutorials/react.rst
`setupI18n` isn't exported by the react module, so it has to be imported from core. I'm not sure if this is an issue with the lib or with the docs, though.
> Fix import of setupI18n in @next React docs.

- docs/misc/react-intl.rst
`react-intl` supports [rich text formatting](https://formatjs.io/docs/react-intl/components#rich-text-formatting) that is very similar to the way `LinguiJS` does. This updates the doc's to correctly show that.
> Update react-int's rich text formatting example

- packages/loader/src/index.js
Adding support for webpack 5 based builds
fix: #713
> feat: Webpack 5: Loader Support

- docs/ref/react.rst
Package 'babel-plugin-lingui-transform-react' is deprecated and '@lingui/babel-plugin-transform-react' should be used in react doc.
> Update deprecated ref in react doc

- packages/cli/package.json
Fixes #728.
TypeScript 4 was recently released but has very few backwards-incompatible changes.  I recently migrated to it on my open-source LinguiJS-based project (https://github.com/JustFixNYC/tenants2/pull/1659) and everything seems to work fine for me. This PR adds support for TypeScript 4 to the `package.json` so no peer dependency warning is logged.
> Support typescript 4 in package.json

- packages/cli/src/lingui-compile.ts
Hi,
once you have the time, please have a look at this one as well.
Works with multiple catalogues, but the `command` function is not exported, therefore I did not write any tests.
#657
> Add back support for pseudo-locale.

- packages/core/npm/esm/index.js
- packages/core/npm/esm/package.json
- packages/core/package.json
With this wrapper, a Node.js based ES module can use the *named import* syntax. E.g. `import {i18n} ...`
This PR belongs to this issue: #736
> Add an ES module wrapper

- docs/releases/migration-3.rst
Starting from v3.0.0-4, package `@lingui/react` apparently does not export the function `setupI18n` anymore
> Update migration-3.rst - `setupI18n` is not exported by @lingui/react anymore

- packages/react/src/format.test.tsx
- packages/react/src/format.ts
Every few times we pull translation updates it turns out that translators do typo or miss-use either element or ICU formats.
Some of these mistakes can cause severe issues. It happens once that broken translation was released to prod and total break our application for customers.
I heard that there are other teams in my company that face similar issues with js-lingui.
We internally created a translation validator and as discussed in the issue https://github.com/lingui/js-lingui/issues/591 I'll try to rise a PR with that feature to the original library.
However, I still believe that any typo or mistake in the translation should not cause the page to break.
In this PR I tried to address the issue with errors caused by wrong use of react components.
- I introduced tests for the cases I …
> Fail gracefully for wrong use of elements in translation

- packages/macro/src/macroJsx.ts
- packages/macro/test/jsx-plural.ts
Fixes https://github.com/lingui/js-lingui/issues/747
This line `.replace(keepSpaceRe, " ")` is creating the whitespace, probably that regex could be reimplemented to don't do that change on this cases, but with the new regex this issue is fixed
> fix: trailing whitespace

- packages/core/src/context.ts
- packages/core/src/dev/compile.ts
- packages/core/src/i18n.ts
Fixes #764 
**Screenshots**
Not need to type anything, and autocompletes messages list :)
> fix: i18n.load typescript inference

- packages/react/src/format.test.tsx
- packages/react/src/format.ts
Fixes #757 
It's using a simpe lodash uniqueId function, just a const to keep the past id's 👍🏻 
I've introduced a little test to avoid a regression to this
> fix: fix children with same key, uniqueId

- packages/macro/index.d.ts
> Allow number properties in plurals macro

- docs/releases/migration-3.rst
I have wrongly tried to apply changes from this document to my code, as I assumed that the latest version is v3.
Ideally there should be a operate site for the v2 and v3 documentation.
> Make clear that v3 migration pre-release

- packages/core/src/i18n.ts
We add optional params to date and number cuz they aren't required in the native functions.
> fix: required options to date, number macro

- docs/ref/conf.rst
- docs/ref/macro.rst
I've updated [`ref/macro`](https://js-lingui-git-feature-docs-macro.lingui-js.now.sh/ref/macro.html) docs to reflect latest changes in v3. @semoal, I noticed there were lot of wrong examples (especially macros wrapped in `i18n._`). Could you please review changes just in case it affects your codemod?
Here's the preview: https://js-lingui-git-feature-docs-macro.lingui-js.now.sh/ref/macro.html
> Update macro reference to latest version

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/__snapshots__/stats.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/stats.test.ts
- packages/cli/src/api/stats.ts
- packages/cli/src/lingui-extract.ts
- packages/conf/index.d.ts
- packages/jest-mocks/index.ts
I'm not sure what's the correct way of handling this, I think the problem of users using lingui in a monorepo where "en" appears by each catalog it's solved in this way, we log for every catalog his stats
Feel free to rquest any changes or some improvements, i'm still pretty noobie about core aspects.
> fix: refactored stats logs 

- packages/react/src/Trans.test.tsx
- packages/react/src/Trans.tsx
the docs state that `render={null}` or `component={null}` should override the `defaultComponent` prop. (https://github.com/lingui/js-lingui/blame/v3.0.0/docs/ref/react.rst#L88)
suppose I had this
```ts
const Span = ({ children }) => {
return <span>{children}</span>;
};
const App = () => {
return (
<I18nProvider i18n={i18n} defaultComponent={Span}>
<Trans id='Hello' render={null} />
</I18nProvider>
);
};
```
current behaviour: `<App /> === <span>Hello</span>`
expected behaviour:`<App /> === 'Hello'`
> Allow null override for default component

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
Closes #809 
Added mark: true to node-glob because internally node-glob needs an slash at the end, will be the same of running normalizeRelativePaths to exclude array
I want to (if you are agree of course) migrate node-glob to fdir that is significantly more faster, will work on it with some benchmarks this week 👍🏻
> fix: accept catalog paths without ending slash

- packages/cli/src/api/catalog.test.ts
The missing `mockFs.restore()` in #812 broke snapshot tests rather badly. Existing tests did not fail, but no new snapshots were written, and every test run created new ones (in some temp location).
> Fix test environment

- docs/ref/macro.rst
- packages/macro/src/macroJs.ts
- packages/macro/test/js-t.ts
Closes #800
Couldn't update the docs because i'm shit writing tables with RST.. any suggerence? haha
> feat: accept t as function

- packages/core/src/context.ts
- packages/core/src/formats.test.ts
- packages/core/src/formats.ts
Will close #472
I've added to format functions a third param to disable/enable the memoize function for testing purposes in that way we can be 100% sure that the cache is working properly.
Some results (1000x renders of `date`)
```
┌──────────────────────┬────────────────────┐
│       (index)        │       Values       │
├──────────────────────┼────────────────────┤
│  memoizedDateResult  │  6.58090500000003  │
│ withoutMemoizeResult │ 263.14999799999987 │
└──────────────────────┴────────────────────┘
```
Some results (1000x renders of `number`)
```
┌──────────────────────┬────────────────────┐
│       (index)        │       Values       │
├──────────────────────┼────────────────────┤
│ memoizedNumberResult │ 2.9453200000002653 │
│ withoutMemoizeResult │ 45.79147499999999  │ …
```
> fix: improved performance of formatters

- packages/macro/index.d.ts
Totally forgot the type 🤕 
Will fix @Bertg comment of #807
> fix: t macro as function typed

- packages/core/src/context.ts
Will close #798
The app doesn't crash if loadLocaleData is not called, but logs a console.error warning about.
> fix: dx on plurals not called

- examples/next-js/lingui.config.js
- examples/next-js/package.json
- examples/next-js/yarn.lock
I have added typescript to dependencies as I think it is better developer experience than assume that they have correct version installed globally. 
This error is shown when running extract without typescript installed
```
Extracting messages from source files…
✖ Cannot find module 'typescript'
Require stack:
- /Volumes/sites/lingui/examples/next-js/node_modules/@lingui/cli/api/extractors/typescript.js
- /Volumes/sites/lingui/examples/next-js/node_modules/@lingui/cli/api/extractors/index.js
- /Volumes/sites/lingui/examples/next-js/node_modules/@lingui/cli/api/catalog.js
- /Volumes/sites/lingui/examples/next-js/node_modules/@lingui/cli/lingui-extract.js
✖ Cannot find module 'typescript'
Require stack:
```
> Add typescript to next example dependencies

- packages/react/src/I18nProvider.tsx
This is related to #834
This PR solves 2 issues:
* Making sure the component gets re-rendered when needed
* Provide a warning to the developer
Some more thoughts about this PR and problem:
* It is perfectly possible for the warning to appear even if the component will render. 
* It would be better to always render. We can add a warning to the developer that only defaults will be rendered. This requires the developer to make sure a language is activated before they render the component. We could even choose to completely throw if i18n is not activated yet, unless the developer set a prop indicating they are OK with defaults.
* ```forceRenderOnLocaleChange``` should be separated from ```dontRenderIfNoLocaleIsActivated```
* ideally there should be a ```i18n.on("activated" ``` which also …
> Ensure render of I18nProvider in async scenarios

- docs/ref/conf.rst
- docs/tutorials/cli.rst
- packages/cli/src/api/compile.test.ts
- packages/cli/src/api/extract.test.ts
- packages/cli/src/lingui-compile.ts
- packages/cli/src/lingui-extract.ts
This PR utilises standard getTranslation eg. we first try to get translation from locale folder, then from fallback, and then keys, etc...
This will allow us to set text that is going to be pseudolocalized and it will close #744 
I do not think there is a reason to change to pseudolocalizing on extract, but it will solve the issue @nathanforce is having.
> Enable pseudolocalization from pseudolocale folder

- .github/workflows/release.yml
We'll try with secrets.GH_TOKEN that is the LinguiBot Account, if that doesn't work we'll change to GITHUB_TOKEN.. that should work properly.
> chore: added token to deploy

- packages/babel-plugin-extract-messages/test/__snapshots__/index.ts.snap
- packages/babel-plugin-extract-messages/test/fixtures/js-with-macros.js
- packages/macro/src/constants.ts
- packages/macro/src/macroJs.ts
- packages/macro/test/js-t.ts
Will close https://github.com/lingui/js-lingui/issues/844
> fix: t macro as function not extracting

- docs/releases/migration-3.rst
This remark is misleading. Core does not export date or number
> docs: fix location of date/number formatters

- packages/core/src/formats.ts
I know this is kinda unnecessary but saw this and thought I'd remove that extra access to `dateFormats` and `numberFormats`, since the original PR was about perf :)
> refactor: hit formatter's cache only once

- docs/guides/testing.rst
We should add plural loading, testing library will log warnings about that to the console otherwise.
P.S. Thanks for adding a page about testing to the documentation!
> docs: add loading plurals to testing.rst

- packages/babel-plugin-extract-messages/src/index.ts
- packages/babel-plugin-extract-messages/test/__snapshots__/index.ts.snap
- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/fixtures/collect/componentA/componentA.js
- packages/cli/src/api/fixtures/collect/componentA/index.js
- packages/cli/src/api/formats/__snapshots__/lingui.test.ts.snap
- packages/cli/src/api/formats/__snapshots__/po.test.ts.snap
- packages/cli/src/api/formats/lingui.test.ts
- packages/cli/src/api/formats/po.test.ts
- packages/cli/src/api/formats/po.ts
This PR resolves #845 
On par file level is collects multiple ```extractedComments``` (using the same name as ```pofile``` package)
This - just like origins - gets merged together to build the catalogue.
Some refactoring was done to use the ```extractedComments``` name throughout.
**Possible issues**
This change should just work for PO file users.
However if users are using lingui file type thing might break. Namely the ```description (string)``` is replaced with ```extractedComments (string[])```. Either some backwards compatibility should be built on top of these changes, or sufficient change information should be provided.
**What can be improved***
Currently the PO file gets built like with ```extractedComments``` and ```references``` grouped: 
```po
#. Comment in code
#. Other comment …
```
> feat: extract multiple comments per translation ID

- docs/releases/migration-3.rst
I just noticed that TypeScript definition files are included now! Thanks for that.
We should encourage people to keep their dependency list short, so I suggest adding that to the "new features" section.
> docs: suggest removal of types in migration docs

- packages/macro/src/macroJs.ts
- packages/macro/test/js-defineMessage.ts
- packages/macro/test/js-t.ts
> fix: parse template strings in t and defineMessage macros

- docs/ref/react.rst
Correct syntax error in I18nProvider example
> docs: correct syntax error in I18nProvider example

- docs/tutorials/setup-react.rst
- packages/cli/src/lingui-extract.ts
Removes information about running deprecated add-locale command from React documentation
> docs: remove add-locale from documentation

- docs/guides/testing.rst
I've tried to use the testing guide and didn't worked properly, so I ended up using our integration tests
> docs: testing guide improved

- docs/guides/pseudolocalization.rst
- docs/index.rst
- docs/tutorials/cli.rst
I have moved psedulocalization to guides from cli tutorials
This closes #838 as the documentation now specifies `fallbackLocales`
> docs: create pseudolocalization guide

- packages/react/src/index.ts
Fixing this error 
```
⋊> /V/s/t/web on master ⨯ npx tsc                                                                                                                                                                                                                                             16:24:19
node_modules/@lingui/macro/index.d.ts:3:15 - error TS2305: Module '"../react/cjs"' has no exported member 'TransRenderProps'.
3 import type { TransRenderProps } from "@lingui/react"
~~~~~~~~~~~~~~~~
Found 1 error.
```
How can I verify index.d.ts is correctly setup? In my IDE I only see `Could not find a declaration file for module '@lingui/react'`
> Export TransRenderProps from @lingui/react

- .github/workflows/release-test.yml
- docs/ref/cli.rst
- examples/create-react-app/package.json
- examples/create-react-app/yarn.lock
- examples/js/package.json
- examples/js/yarn.lock
- examples/next-js/package.json
- examples/next-js/yarn.lock
- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/help.ts
- packages/cli/src/lingui-extract-template.ts
- packages/cli/src/lingui-extract.ts
Will close #510
I've adjusted also the help.ts function because when running `yarn extract src/ --verbose` was leading to confusion because params were passed also to `yarn compile` command.
On create-react-app example of Lingui projects results are really good:
`yarn extract src/ 1.47s user 0.26s system 111% cpu 1.709 total`
`yarn extract 4.19s user 0.33s system 135% cpu 3.345 total`
> feat: extract accepts files as cli option

- packages/macro/index.d.ts
> fix: macro underscore type

- packages/macro/index.d.ts
Getting error if using example from documentation
```
<Select value={gender} male="His book" female="Her book" other="Their book" />
```
```
Type '{ value: "male"; male: string; female: string; other: string; }' is not assignable to type 'IntrinsicAttributes & { value?: string | undefined; other?: ReactNode; } & TransProps & { children?: ReactNode; }'.
Property 'male' does not exist on type 'IntrinsicAttributes & { value?: string | undefined; other?: ReactNode; } & TransProps & { children?: ReactNode; }'
```
> fix: select props typescript

- packages/cli/src/api/pseudoLocalize.test.ts
- packages/cli/src/api/pseudoLocalize.ts
I have improved RegEx for plurals. It now correctly escapes plural with offset. This is fix for #743, but it does not close it as there is need to escape other React components like Select, SelectOrdinal & DateFormat
I was not able to test the code because of this #886
> fix: plural pseudolocalization with offset

- docs/tutorials/setup-react.rst
Option `localeDir` and `srcPathDirs` are deprecated.
Documentation changed to use `catalogs` instead.
> Update deprecated srcPathDirs in Setup React docs

- docs/ref/conf.rst
- packages/conf/src/index.ts
- packages/macro/src/index.ts
The `runtimeConfigModule` setting cannot be used to transform the hardcoded `import {Trans} from '@lingui/react'` statements, which is problematic when the `Trans` symbol is expected to be provided by an intermediary layer (#822).
This diff addresses that by adding support for `runtimeConfigModule` being an object, in which case the key is the symbol name (either `i18n` or `Trans`), and the value is the symbol name and from where to import it. This change is completely backward compatible, only adding syntax.
The test framework doesn't seem to allow for testing `runtimeConfigModule` (its current implementation doesn't seem tested) so I couldn't add relevant tests.
> feat: add support for runtimeConfigModule w/ Trans

- packages/cli/src/api/pseudoLocalize.test.ts
- packages/cli/src/api/pseudoLocalize.ts
It correctly pseudolocalize SelectOrdinal. I have also tried to fix Select
```
<Select value={gender} male="His book" female="Her book" other="Their book" />
```
After extraction the message is:
```
{gender, select, other {Their book}}
```
It looks to me like a bug. I would expect `male` and `female` to be in the message as well.
> fix: accept pseudolocalization in SelectOrdinal

- docs/ref/conf.rst
- examples/create-react-app/package.json
- packages/cli/src/api/__snapshots__/compile.test.ts.snap
- packages/cli/src/api/compile.test.ts
- packages/cli/src/api/compile.ts
- packages/cli/src/lingui-compile.ts
- packages/conf/index.d.ts
- packages/conf/src/__snapshots__/index.test.ts.snap
- packages/conf/src/index.ts
- scripts/verdaccio-integration.js
Will close #902 
We won't break babel 6 users, but babel 7 could use this to modify that ASCII configuration :)
> feat: config accepts compilerBabelOptions

- packages/babel-plugin-extract-messages/src/index.ts
- packages/babel-plugin-extract-messages/test/fixtures/js-with-macros.js
Changes in `babel-plugin-extract-messages` packages:
- added reproduction test case where undefined msgid is being generated
- added a fix for that test case
- refactored related function a bit
Closes #905
> fix: prevent adding undefined msgid to messages

- docs/ref/macro.rst
This file corresponds to this page https://lingui.js.org/ref/macro.html
> docs: fix typo in macro doc

- docs/ref/core.rst
option catalogs was replaced with option messages
also clearer example to use compiled messages rather than the inconsistent use of catalogs/messages
> docs: update core javascript docs for setupI18n

- packages/cli/src/lingui-extract.ts
Tiny fix where `macro` package is using the `LINGUI_CONFIG` env while extract command isn't. In the case of different config locations, this is causing problems. I know there is `--config` for extract, but that means having a path specified in two different ways.
Only thing I am not sure of if the env variable should take precedence over CLI arg. I chose not, but let me know.
> fix: Use LINGUI_CONFIG env as fallback for extract

- packages/core/src/context.ts
Should fix issue #921 i18n._ now shows a string return type according to typescript tooltips in vscode
> fix: added return types to functions returned by interpolate and context in core/cjs/context.ts

- packages/conf/package.json
- packages/conf/src/index.ts
- yarn.lock
Fixes #940 
In the end, I've included `@endemolshinegroup/cosmiconfig-typescript-loader` as a dependency to consume the Error class from it so it doesn't need to be copied too. In case the https://github.com/EndemolShineGroup/cosmiconfig-typescript-loader/pull/132 gets merged & published, the code here can be simplified.
> Support for TS based Lingui configuration

- packages/cli/src/api/compile.ts
- packages/conf/index.d.ts
- packages/conf/src/__snapshots__/index.test.ts.snap
- packages/conf/src/index.ts
Will close #935 
unfortunately jest-validate doesn't work if in the example config we set an empty object, we must strict declare the values we accept. I'll setup the default values that we're using and probably the only ones that the final user should be able to change.. Dunno
> fix: compilerBabelOptions jest-validate

- docs/tutorials/setup-react.rst
React and macro links was mixed up
> docs(setup-react): correct links to react and macro pages

- packages/macro/index.d.ts
The `component` prop of `<Trans/>` macro is incorrect, which should be consistent of https://github.com/lingui/js-lingui/blob/main/packages/react/src/Trans.tsx#L19.
This code will raises TS error without fix:
```tsx
import { Plural, Trans } from '@lingui/macro'
const Div = () => <div />
function Index() {
return (
<div>
<Trans component={Div}>go back</Trans>
{/*  Type Error:  ↑↑↑ */}
<Plural
id="message"
value={1}
_0="no messages"
one="# message"
other="# messages"
component={Div}
{/*   Type Error:  ↑↑↑ */}
/>
</div>
)
}
```
> fix: wrong prop type of Trans macro

- packages/cli/src/api/pseudoLocalize.test.ts
- packages/macro/src/macroJs.test.ts
- packages/macro/src/macroJsx.test.ts
- packages/macro/src/macroJsx.ts
#919 Will close this issue
Also will close #959
> fix: <Select /> macro not extracted properly

- packages/cli/src/api/pseudoLocalize.test.ts
- packages/cli/src/api/pseudoLocalize.ts
> fix: <Select /> pseudolocalization

- packages/cli/src/api/catalog.ts
Hello, 
I stumble upon this issue quite frequently, sometimes someone at team accidentally deletes a string in one of translations files and it throws a generic error. 
Error:
I saw your if check few lines before the crashing point, hovewer that if won't catch it so I moved it to correct scope. 
My fix results into this:
> No message when translations are missing

- packages/cli/src/api/catalog.ts
As discussed in - https://github.com/lingui/js-lingui/issues/966
> fix: obsolete flag disable when using extract [files]

- packages/loader/package.json
npm 7 mandates matching peer dependencies. See RFC 25.
Fixes "Could not resolve dependency: npm ERR! peer webpack@"^4.0.0" from @lingui/loader"
@lingui/loader works perfectly fine with Webpack 5.x and a medium-size project.
> fix(@lingui/loader): accept webpack 5.x as a peer dependency

- packages/conf/src/index.ts
It seems like the validation got stricter, and `runtimeConfigModule` alternative syntax (#895) wasn't covered.
> fix: runtimeConfigModule config validation

- docs/misc/tooling.rst
We've created simpleen and support LinguiJS as a preconfigured translator. We handle and translate ICU messages as well.
It would be great to be listed in the docs and help more LinguiJS users translating their projects. 
Really appreciate it
> docs: Added simpleen.io to tooling section

- docs/misc/react-intl.rst
- docs/ref/macro.rst
- docs/tutorials/cli.rst
- docs/tutorials/react-patterns.rst
I found several internal links are broken in docs. This PR fixes them.
> docs: fix broken links

- docs/ref/cli.rst
- packages/cli/package.json
- packages/cli/src/lingui-compile.ts
- packages/cli/src/lingui-extract.ts
- yarn.lock
https://github.com/lingui/js-lingui/issues/966
I've added 2 functionalities:
1. `--watch` for `lingui extract`
2. `--watch` for `lingui compile` - I think in some implementations of Lingui it can be useful.
> feat: --watch mode for extract and compile

- docs/tutorials/react-patterns.rst
- docs/tutorials/react.rst
[React common patterns](https://lingui.js.org/tutorials/react-patterns.html) is very helpful but its content seems to be a little old. This PR update the content to use `useLingui` hook instead of `I18n` render-prop component.
This PR also add link from react tutorial to common i18n patterns as a further reading.
> docs: Update react patterns

- packages/cli/src/lingui-compile.ts
There are two problems about the report of missing translations of `lingui compile --strict`:
1. The command reports the total number of translations not as the number of missing ones.
2. With `--verbose` option, missing values, which are always `undefined`, are reported. It is less useful.
This PR fixes the above problems. Under the following situation:
```
$ npx lingui extract
Catalog statistics for src/locales/{locale}/messages:
┌─────────────┬─────────────┬─────────┐
│ Language    │ Total count │ Missing │
├─────────────┼─────────────┼─────────┤
│ en (source) │      4      │    -    │
│ cs          │      4      │    3    │
└─────────────┴─────────────┴─────────┘
(use "npm run extract" to update catalogs with new messages)
(use "npm run compile" to compile catalogs for production)
``` …
> fix: Report correct number of missing messages in strict mode

- docs/tutorials/react-patterns.rst
After reading https://github.com/lingui/js-lingui/pull/980#issuecomment-784097758, I learned about the `defineMessage` macro and understood that it is the best way for lazy translations.
This PR updates the react common patterns document to use  `defineMessage` instead of `t` for lazy translations.
> docs: Use defineMessage macro for lazy translations

- packages/cli/package.json
- packages/cli/src/api/detect.ts
- yarn.lock
This will help detect the correct project type in situations where you want to have multiple lingui configs in a project with a shared package.json. 
For example having backend and frontend in separate folders.
I haven't tested this.
> fix: use pkgUp.sync to localize package.json

- packages/cli/src/api/catalog.ts
- some formatting-seems like the codebase was not formatted when prettier was upgraded to major version 2
- fixes this type error:
```
> cd back-end && lingui compile
Compiling message catalogs…
/home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/api/catalog.js:236
if (!catalogs[locale].hasOwnProperty(key)) {
^
TypeError: Cannot read property 'hasOwnProperty' of undefined
at getTranslation (/home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/api/catalog.js:236:31)
at getMultipleFallbacks (/home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/api/catalog.js:272:18)
at Catalog.getTranslation (/home/capaj/work-repos/looop/project-alpha/node_modules/@lingui/cli/api/catalog.js:278:9)
at /home/capaj/work-repos/looop/project-alpha/node_modules/@lingui …
```
> fix: @lingui/cli type error when catalog is missing

- docs/tutorials/react.rst
A new user has no idea how the configuration file should be, so writing "After fixing configuration" in the tutorial is not helping anything.
And actually just putting the locales in the config will make lingui scan the /node_modules/ directory, which will throw a lot of errors. 
So a minimal working .linguirc/config example would be great.
> docs: explain locales config in the Setup tutorial

- packages/core/package.json
- packages/detect-locale/package.json
- packages/macro/package.json
React Native's Metro bundler expects all imports to be declared in the `exports` attribute when there is one defined. 
Lingui imports it (to get the version I guess?) and Metro refuses it as it was not defined as a valid export.
See https://github.com/eemeli/make-plural/issues/15 for a similar issue on the `make-plural` package
The `main` field for `@babel/macro` was also incorrect as there is no `index.ts` in this project.
These 2 changes allowed me to successfully use Lingui on a React Native project.
> fix: exports attribute on package.json, expo compat

- docs/tutorials/javascript.rst
I was wondering why `plural` wasn't working in my project:
```
@lingui/macro: Cannot read property 'properties' of undefined Learn more: https://www.npmjs.com/package/@lingui/macro
at Array.forEach (<anonymous>)
```
Actually it's due to a typo in the docs, related to an old version of LinguiJS.
I think:
```javascript
plural({
value: count,
one: "# book",
other: "# books"
})
```
should be updated to:
```javascript
plural(count, {
one: "# book",
other: "# books"
})
```
> docs: Fix syntax of `plural` in docs

- packages/cli/package.json
- packages/macro/package.json
- yarn.lock
Will close #1023 
It isn't a breaking change for us because we already dropped Node 8 on the v3 release :)
> chore(deps): updated babel-plugin-macros peer to v3

- packages/babel-plugin-extract-messages/src/index.ts
- packages/babel-plugin-extract-messages/test/__snapshots__/index.ts.snap
- packages/babel-plugin-extract-messages/test/fixtures/js-with-macros.js
- packages/macro/test/js-t.ts
This PR closes issue #957 macro `t` with template string id.
> fix: extract works with template string id's

- packages/macro/src/macroJs.test.ts
- packages/macro/src/macroJs.ts
- packages/macro/src/macroJsx.ts
Will unblock the migration of #1022
> fix: respect unicode chars in t macro

- packages/macro/src/macroJs.test.ts
- packages/macro/src/macroJs.ts
- packages/macro/src/macroJsx.ts
Re-fixes the unicode error we found migrating the passCulture application to v3.
I went for a walk and start to think about this and saw that we weren't extracting correctly the unicodes.
`\\unicode` is not correct => `\unicode`this is correct 
**probably with this adjustment we fix the wrong behaviour when we built the application to production**
About the string failing in development about not being processed as a string, we'll see tomorrow debuggin the node_modules which is the root cause 
#1022
> fix: unicode chars were extracting with double slashes

- docs/misc/react-intl.rst
> docs: Comparison with react-intl docs missing  quotes

- docs/ref/conf.rst
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/extract.test.ts
- packages/cli/src/api/extract.ts
- packages/cli/src/api/extractors/index.ts
- packages/cli/src/lingui-extract.ts
- packages/conf/index.d.ts
- packages/conf/src/index.ts
Now with this pull request users can create his own extractors:
```
type ExtractorType = {
match(filename: string): boolean
extract(filename: string, targetDir: string, options?: any): void
}
```
Before we had two extractors `[babel, typescript]`, the typescript step it's useless since babel support typescript practically out of the box, since this compiling it's done twice first by babel and then by typescript was causing a lot of failures on Typescript projects with bad origin's and strange errors about NODE_ENV.
Related issues: 
https://github.com/lingui/js-lingui/issues/1058
https://github.com/lingui/js-lingui/discussions/1047
Now if your package it's pure Typescript and doesn't contain Babel, you could just use typescript extractor instead of using the babel one.
```js
extractors: [ …
```
> feat: configurable and extendable extractors with Lingui config

- packages/core/npm/esm/dev.js
- scripts/build/rollup.js
Resolves #1003 and #1063 and probably some other's which I closed because didn't know this happened.
> fix: ESM dev entrypoint was causing unexpected behaviors

- packages/cli/src/api/formats/index.ts
- packages/cli/src/api/formats/po-gettext.ts
I noticed two issues with the `po-gettext` format option:
1. The `disableSelectWarning` flag is not part of the `CatalogFormatOptions` type, and so it is reported as being invalid by the CLI:
2. The `po-gettext` format does not properly support the use of `lineNumbers` format option that the standard `po` format option supports.
> fix: po-gettext format issues with CLI

- packages/cli/src/api/formats/index.ts
- packages/conf/src/index.ts
@semoal I believe I placed this in the wrong file, the validation of the config object actually happens within the `conf` package, so that was a bit of misreading on my part. I tested this on locally and it suppresses the issue I was describing in #1073
> fix: Move property def into `conf` package

- packages/core/src/i18n.ts
This adds a cast to the call to `JSON.parse` which allows the `_` function to properly infer the `string` return type.
My only concern is the feat/fix/breaking level of this commit, which changes an `any` to a `string`. For the most part this should be ok, especially given the expected usages of `i18n._` but I want to bring it up in any case.
I love lingui, thanks!
> fix(core): add string return type to i18n._

- packages/cli/src/lingui-compile.ts
Currently the `--watch` option for `compile` only works for `po` format. This is because the file extension matches the format.
For other format options like `minimal` then currently the watcher is looking for files with a `.minimal` extension rather than a `.json` extension.
> fix: 'compile --watch' not watching for correct file based on format

- packages/cli/src/api/catalog.ts
The previous implemented of `lingui extract-template` command does not work with po-gettext format because of hard-coded `po`. This change support any further `po-xyz` format in the future.
> fix: add extract-template for po-gettext format

- packages/cli/src/api/formats/po-gettext.ts
The previous logic is wrong because a language like Vietnamese, Indonesian, Malaysian... does not support plural form, so gettext tools does not allow these kind of to have multiple msgstr. Therefore detecting a plural translation through number of msgstr is not true. As consequence, that causes plural macro can not be replaced with proper translation.
Ex:
```
#. js-lingui:icu=%7BmonthNumber%2C+plural%2C+one+%7B%2F+%23+th%C3%A1ng%7D+other+%7B%2F+%23+th%C3%A1ng%7D%7D&pluralize_on=monthNumber
msgid "/ # tháng"
msgid_plural "/ # tháng"
msgstr[0] "/ # bulan"
```
> fix: wrong detect whether a translation is plural

- docs/tutorials/react.rst
Currently, source codes in [the react tutorial](https://lingui.js.org/tutorials/react.html) do not work as described. This PR fixes several problems and makes it work as described. This PR partially fixes https://github.com/lingui/js-lingui/issues/977, which is closed but not fixed.
> docs: Improve react tutorial

- packages/cli/src/api/catalog.ts
When catalogs.include contains an array of > 1 globs they are joined together into one expression. This expression is missing an end curly brace } and this fix adds it.
> fix: no files being found when catalogs.include has more than one entry

- docs/ref/cli.rst
- packages/cli/src/lingui-compile.ts
- packages/cli/src/lingui-extract.ts
This adds support for debounce, avoiding multiple subsequent file saves from also resulting in subsequent extraction/compilation.
I noticed that the files, according to the `.prettierrc` in the repo, were formatted even though they weren't touched to add this feature. If this is undesirable, I can revert those changes. Let me know.
Thanks!
> feat: Add debounce option to compile and extract CLI

- packages/conf/index.d.ts
- packages/conf/src/index.ts
- packages/core/src/context.ts
- packages/core/src/i18n.ts
- packages/macro/src/macroJs.test.ts
- packages/macro/src/macroJs.ts
- packages/macro/src/macroJsx.ts
> fix(): unicode chars were removed from .po files when extracting

- packages/cli/src/api/__snapshots__/compile.test.ts.snap
- packages/cli/src/api/compile.test.ts
- packages/cli/src/api/compile.ts
> fix(): keys with leading number was generating bad object keys

- packages/cli/package.json
- packages/cli/src/lingui-extract.ts
- packages/cli/src/services/translationIO.ts
- packages/conf/index.d.ts
- packages/conf/src/__snapshots__/index.test.ts.snap
- packages/conf/src/index.ts
Hello LinguiJS team,
This is a PR proposal that is open for suggestions.
I'm the founder of [Translation.io](https://translation.io), a cloud service provider that helps localize applications and smooth the syncing process with translators. We decided to push best practices to keep developers and translators happy in the long run. We already support the [Ruby on Rails](https://translation.io/rails) and [Laravel](https://translation.io/laravel) stacks with a decent success.
We tried several times to support JS/React but we didn't like the existing solutions back then. Then we found LinguiJS, and it was exactly what we were looking for all that time: GetText-like easy syntax with simple source code extraction and PO format.
You really did an amazing job! 😄
We have decided to add Lingui as a …
> feat: Cloud service providers & Translation.io

- packages/conf/src/index.ts
`targets` `browserslistconfigfile` `browserslistenv` `assumptions` was missing in validation, fixes #1133
> Add missing babel properties to config validation

- docs/ref/macro.rst
- packages/macro/global.d.ts
- packages/macro/index.d.ts
- packages/macro/src/index.ts
- packages/macro/src/macroJs.test.ts
- packages/macro/src/macroJs.ts
- packages/macro/test/js-t.ts
This allows developers that work in concurrent rendering environments
to use a Lingui instance that is locale-specific, without risking global
Lingui to be switched to another locale.
In React, `<I18nProvider>` may be used to provide a locale-specific
Lingui instance, and it can be retrieved by using `useLingui`. After
that, the instance can be passed as argument to the `t` macro and
it will be used instead of the global instance, ensuring deterministic
behaviour.
This addresses concerns raised in https://github.com/lingui/js-lingui/issues/901, https://github.com/lingui/js-lingui/issues/578
Documentation, TypeScript definition changes and (more) tests are 
left to do,  but the main goal of this PR is to receive feedback on the 
approach and to see if this is on the right track. …
> feat(macro): Add support for passing custom i18n instance

- packages/babel-plugin-extract-messages/src/index.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/extract.ts
- packages/cli/src/api/extractors/babel.ts
- packages/cli/src/api/extractors/index.ts
- packages/cli/src/api/extractors/typescript.ts
- packages/cli/src/lingui-extract-template.ts
- packages/cli/src/lingui-extract.ts
- packages/cli/src/tests.ts
> fix(#1137): configPath is passed through babel-plugin-extract-messages

- docs/ref/macro.rst
- packages/macro/global.d.ts
- packages/macro/index.d.ts
- packages/macro/src/macroJs.ts
- packages/macro/test/js-t.ts
This PR fixes an issue introduced in #1139, that would cause a type error to be raised, even if the usage was correct.
I'm not sure how I didn't notice this before, but I guess it's because either type checking was disabled while I tested it, or because the files were JS only.
The issue is that for TypeScript, doing ```t(x)`template ${string}`;```, is seen as two individual calls (`result = t(x)` and ```result`template ${string}`;```), so it also needs to be typed like that, even though the macro itself will never let it be executed as such.
> fix(types): correct types for  macro with custom i18n instance

- packages/cli/src/api/catalog.ts
- packages/cli/src/api/formats/po-gettext.ts
- packages/cli/src/api/formats/po.test.ts
- packages/cli/src/api/formats/po.ts
Given config with `lineNumbers: false`, if you run extract, and then subsequently run extract with the watcher on the entire origin is stripped.
Line 30 in `po.ts` was slicing regardless of the length of the array.
Modified this to destructure the array and remove the unnecessary joinOrigin call.
Added a new test as I wasn't quite sure how to modify the existing one to include this case 🤔
> fix: stripping origin if line numbers already strippped

- packages/macro/global.d.ts
- packages/macro/test/types.ts
- packages/react/src/Trans.test.tsx
- tsconfig.json
Now types.ts inside macro/test/ will be checked before each release: `yarn type:check`, if we introduce any breaking change related to these macros tsc will warn us
> chore: Added tsconfig paths for type-checking any issues on macro types

- packages/cli/src/services/translationIO.ts
I honestly haven't tested this change but hopefully this will fix an issue where having a pseudo locale configured in lingui prevents the translation.io sync from working with:
```
Synchronization with Translation.io failed: Invalid 'target_languages': pseudo. Please use existing language codes (https://translation.io/docs/languages) or custom languages (https://translation.io/blog/custom-languages).
```
> fix: don't push pseudoLocale to translation.io provider

- packages/babel-plugin-extract-messages/src/index.ts
- packages/babel-plugin-extract-messages/test/__snapshots__/index.ts.snap
- packages/babel-plugin-extract-messages/test/fixtures/js-without-macros.js
Hello! Once again thanks for lingui. We're using it more and more at Smartsheet.
I ran into this after my translation comments were quite verbose. I wanted to break them into multiple lines and concatenate them:
...
comment: "first long line" + 
"second long line",
...
1 question, if you'd like to go forward with this PR: should this concatenation extraction be applied to the id as well?
> feat: add the ability to extract concatenated comments

- docs/misc/react-intl.rst
In `Comparison with react-intl / Macros for component-based message syntax`, it shows a sample where the message id is `msg.docs`, then adds a note that says it's optional. In the explanation the previous message id is mentioned after the generated message id. The previous message id is mistakenly called out as `msg.id`.
> docs: the mentioned message id should be "msg.docs"

- packages/cli/src/api/compile.ts
@lingui/loader uses strict mode when it's not running in production.  This is turn means that `compileSingleKey` always gets passed an empty string as `translation` for the pseudo locale to translate.  This seems to defeat the purpose of using pseudo localization.
With this change, you can use @lingui/loader and also get dynamically generated pseudo locale string.
> fix: Allow pseudoLocalize to work in @lingui/loader

- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/formats/__snapshots__/po-gettext.test.ts.snap
When we run `lingui extract --overwrite` only translations with a custom id + message were working properly.
However, if there is no default `message` but only the `id`, `--overwrite` option was resetting the translation to empty string instead of using `key` as default
This was working properly when a "new" key was added, but not when we update the key (on merge)
Also update snapshot `go-gettext.test.ts.snap` because it fails on master
Fixes #1162 
See [this repository](https://github.com/ardeois/lingui-extract-overwrite-bug) to reproduce the issue
> fix(cli): extract with --overwrite should fallback to key

- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/extract.test.ts
- packages/cli/src/api/extract.ts
- packages/cli/src/api/extractors/index.ts
- packages/cli/src/lingui-extract.ts
Some [custom extractors](https://lingui.js.org/ref/conf.html#extractors) are required to have async execution. For instance, in order to extract messages from Svelte+Typescript you need to preprocess svelte files before compilation. Preprocessing is an async operation in Svelte (see [doc](https://svelte.dev/docs#svelte_preprocess)). But lingui-cli extract command doesn't support async extract method from custom extractor – see `catalog.make` method in `packages/cli/src/lingui-extract.ts` and all function calls down to `extract` method of a particular extractor.
This PR adds support for async extractors by awaiting for `extract` is finished before calling `traverse` function in `Catalog.collect` method
> feat(cli): make extract cmd asynchronous execution

- packages/cli/package.json
Pins [cli-table](https://github.com/Automattic/cli-table#readme) to version 0.3.6, as version 0.3.7 brings a breaking change that prevents `npm extract` from working as expected (see #1169).
> fix: pin cli-table to 0.3.6

- packages/cli/src/lingui-extract.ts
We found an issue on case sensitive systems where the cloud service (if one was present) was not loading correctly.
We made sure to lowercase the first letter so that it works on both case-sensitive and case-insensitive systems.
> fix: cloud service `import()` on case-sensitive filesystems

- packages/macro/global.d.ts
- packages/macro/index.d.ts
- packages/macro/src/index.ts
When working in a TypeScript environment, the typings suggest that a function called `defineMessages` (note the plural) should be available. However, this function is not actually available in the code, and its use will cause errors at runtime. It appears that this function was removed as obsolete a while back, so it should also be removed from the typings.
The only other place this function was referenced was in the switch statement in `getMacroType()`, which is also cleaned up in this change.
I found these related changes:
- https://github.com/lingui/js-lingui/commit/9ea2f2ed8446a7a44679809e480ac03605300e68 removed the `defineMessages` function from the API reference, saying it's obsolete
- https://github.com/lingui/js-lingui/pull/651 states the intention to remove the `defineMessages` …
> fix: remove the obsolete `defineMessages` function from the typings.

- packages/macro/package.json
When @lingui/macro generates code, it could create imports using `@lingui/core`
or `@lingui/react`
With PNPM dependency manager, we need those peer dependencies, otherwise the build
could fail as we'll have missing or wrong dependencies.
Currently in one of our monorepo using different versions of lingui (v2 and v3),
typescript gets confused when we use `@lingui/macro@v3`. It sometimes resolves
`@lingui/core@v2` even if our `package.json` dependencies declare `@lingui/core@v3`.
By setting `@lingui/macro` peer dependencies, the problem disappears
> fix(macro): add lingui peer dependencies

- docs/guides/dynamic-loading-catalogs.rst
The name of the plugin contains duplication that might confuse
> docs: Fix a typo in a babel plugin name

- packages/macro/index.d.ts
- packages/react/src/I18nProvider.tsx
- packages/react/src/Trans.tsx
After some changes in react v18, the `FunctionComponent` type no longer implicitly passes `children` as part of the props. This means that the `children` prop needs to be declared explicitly.
> fix: specify children for react v18 types

- docs/ref/react.rst
I noticed two places where example JSX code is invalid because of a missing `</span>` tag. This PR fixes it.
> docs: Fix missing closing tag in jsx example

- docs/ref/macro.rst
- docs/ref/message-format.rst
- packages/cli/src/api/formats/po-gettext.test.ts
- packages/cli/src/api/pseudoLocalize.test.ts
- packages/core/src/dev/compile.test.ts
- packages/macro/global.d.ts
- packages/macro/index.d.ts
- packages/macro/test/types.ts
Currently, the following example is used in the [selectOrdinal's documentation](https://lingui.js.org/ref/macro.html#jsmacro-selectOrdinal). However, this code may return a wrong result for larger numbers. For example, it returns `"1st"` when `count` is `21` . Expected behavior is to return `"21st"`. 
```ts
const message = selectOrdinal(count, {
one: "1st",
two: "2nd",
few: "3rd",
other: "#th",
})
```
This is not a problem of the Lingui itself, but a problem of the documentation. I think the document should suggest proper use of placeholders as follows:
```ts
const message = selectOrdinal(count, {
one: "#st",
two: "#nd",
few: "#rd",
other: "#th",
})
```
This code returns `"21st"` when `count` is `21` as expected.
This PR fixes selectOrdinal's examples and test cases to use placeholders. …
> docs: Use placeholder in selectOrdinal's examples and test cases

- packages/macro/src/macroJsx.ts
- packages/macro/test/jsx-trans.ts
- Fixes https://github.com/lingui/js-lingui/issues/1225 
This was the least intrusive way I could come up with by wrapping the relevant `jsxAttribute` string literal value in a `jsxExpressionContainer`. 
This is currently done conditionally in case the message includes a double quote. Note that I believe this could safely be done unconditionally, but it requires updating a lot of tests. I happily do this if we like the suggested solution.
This has been tested out on a fairly big codebase.
> fix: JSX attribute parsing issue when using double quotes

- docs/ref/react.rst
- packages/react/src/I18nProvider.tsx
- packages/react/src/Trans.test.tsx
- packages/react/src/Trans.tsx
The reason for that PR is to have more control inside defaultComponent.
I'm using your awesome library with nextjs and loading translations asyncronically on a client side, but for the first render I'd like to be able to display some kind of skeleton.
The possibilities with this change are huge: we can even make some kind of i18n-WYSIWYG.
> feat: Pass props to I18nProvider.defaultComponent in Trans.render style

- packages/core/npm/esm/dev.js
- packages/core/npm/esm/index.js
- packages/core/npm/esm/package.json
- packages/detect-locale/npm/esm/package.json
- packages/react/npm/esm/package.json
Add `package.json` with `{"type": "module"}` under `/esm`.
Fixes https://github.com/lingui/js-lingui/issues/1254
> fix: Add extra package.json under `/esm`

- packages/cli/src/lingui-compile.ts
For languages that don't have plurals such as "mi", "kr" and "ht", lingui compiler exits when plurals are not found despite the language not having plural rules. 
This allows the compiler to complete for these languages. 
Related PR for lingui loader:
https://github.com/lingui/js-lingui/pull/824
> fix: allow lingui compile to compile for languages without plural rules

- packages/conf/package.json
- packages/conf/src/__snapshots__/index.test.ts.snap
- packages/conf/src/fixtures/valid/custom.config.ts
- packages/conf/src/index.test.ts
- yarn.lock
Switch from unmaintained [@endemolshinegroup/cosmiconfig-typescript-loader] to [cosmiconfig-typescript-loader].
I’ve run into a problem in one of my projects where running `jest` gave errors.
<details>
```
Error: Jest: Failed to parse the TypeScript config file …/jest.config.ts
Error: Debug Failure. False expression: Non-string value passed to
`ts.resolveTypeReferenceDirective`, likely by a wrapping package
working
with an outdated `resolveTypeReferenceDirectives` signature. This is
probably not a problem in TS itself.
at readConfigFileAndSetRootDir
(…/node_modules/jest-config/build/readConfigFileAndSetRootDir.js:136:13)
at readConfig
(…/node_modules/jest-config/build/index.js:233:18)
at readConfigs
(…/node_modules/jest-config/build/index.js:420:26)
at runCLI …
```
> feat: Switch to cosmiconfig-typescript-loader

- packages/cli/src/lingui-extract-template.ts
Hello!
I noticed a [bug](https://github.com/lingui/js-lingui/issues/1284) where I got a TypeError when running the extract-template command.
I added a simple null and undefined check, so that it would just run.
> fix: add null undefined check

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/fixtures/pot-template/messages.pot
- packages/cli/src/api/fixtures/pot-template/pl.po
- packages/cli/src/lingui-extract-template.ts
- packages/cli/src/lingui-extract.ts
- packages/loader/package.json
- packages/loader/src/webpackLoader.ts
This PR brings full e2e support for gettext *.pot files into linguijs. 
Template is a file where all messages extracted from sourcecode is stored. It doesn't have any translations. It treated as build artifact and could be added to gitignore. 
Short version: 
They are not taken into account during compiling messages.
Long version:
Standard gettext flow looks like the following
- Change source code and potentially change messages
- Run extractor and produce *.pot file
- Send *.pot file together with translations (en.po, pl.po) to the translators. 
- Translators upload .pot and *.po files into theirs translation software which merges them
- Translators translate
- Translators return translated files. 
There are few things which important to notice. 
Merging new messages to the translations …
> feat: Support GetText template files support during compile

- packages/core/src/context.ts
Fix for https://github.com/lingui/js-lingui/issues/1203
In some cases is needed to pass the format function to `_` method, but it doesn't work if pluralization is applied. 
For instance, I don't need to use Arabic "[Hindi](https://en.wikipedia.org/wiki/Hindu%E2%80%93Arabic_numeral_system)" numbers, hence I want to pass `NumberFormatOptions` to the pluralization function 
```
{
numberingSystem: 'latn'
}
```
In recap, consumer code will look something like this
```
const translation = this.lingui._(value, options, {
formats: {
number: {
numberingSystem: 'latn',
},
},
});
```
> fix: Pass formatter to pluralization function

- packages/cli/src/api/__snapshots__/compile.test.ts.snap
- packages/cli/src/api/compile.test.ts
- packages/cli/src/api/compile.ts
- packages/cli/src/api/pseudoLocalize.test.ts
This is fixing this issue: https://github.com/lingui/js-lingui/issues/1213
I'm not sure why in this PR (https://github.com/lingui/js-lingui/pull/1165) there was a change from the message to the key, but I hope I don't mess anything
Also, I wonder if we should remove the `addDelimitersVariables` & `addDelimitersMacro` and keep only the handling of HTML inside the `pseudoLocalize.ts` code
> fix: Make pseudolocal use the message AST instead of the key

- packages/macro/index.d.ts
Sometimes you need to force the `i18n` instance used by `<Trans>`. In my case, it is to have a server-side render of a React PDF document, where I do not have a global `i18n` instance but several global ones (one per language).
The macro seems to properly handle this, and this patch works fine locally with our app.
For example:
```tsx
component Test = () => {
const i = useLingui()
return <Text><Trans i18n={i.i18n}>Test String</Trans></Text>
}
```
> fix(types): `<Trans>`can have an `i18n` props

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/extractors/index.ts
- packages/cli/src/lingui-extract.ts
`lingui extract` prints extraction failures (such as `Cannot process file [path]: Different defaults for the same message ID.`) to the console but then finishes with a zero exit code. When run unattended in a CI job, this means files with failures are skipped during extraction and their messages may then be missing in a production build.
This PR propagates the `boolean` result(s) from the extractor all the way up into the CLI command. There was already code to handle it and do `process.exit(1)` when the result is `false`.
> feat: `lingui extract` should fail with a non-zero exit code when there are extraction failures

- packages/babel-plugin-extract-messages/src/index.ts
- packages/babel-plugin-extract-messages/test/__snapshots__/index.ts.snap
- packages/babel-plugin-extract-messages/test/fixtures/js-without-macros-or-comments.js
- packages/babel-plugin-extract-messages/test/index.ts
This change updates babel-plugin-extract-messages so that it will pick up usages of the i18n._ method from @lingui/core directly.
This solves the issues mentioned in https://github.com/lingui/js-lingui/issues/1178 and https://github.com/lingui/js-lingui/issues/1224#issuecomment-1317265270 without needing the workaround listed in 1178 (prefixing the id with `/*i18n*/`).
The main driver for this is to allow use of Lingui without macros, so that sites running on Next.js can use the SWC compiler instead of babel.
Aware that this is effectively adding back extract behavior that was removed previously, but hopefully this isn't too big of a deal - let me know if you have any feedback.
> feat: allow extract to work with i18n._ calls not created from macro

- packages/conf/index.d.ts
- packages/macro/src/index.ts
https://lingui.js.org/ref/conf.html#id12
runtimeConfigModule should accepts or tuple or object with properties, this PR fixing typings to reflect this
> fix(conf): proper typings for LinguiConfig['runtimeConfigModule']

- packages/macro/package.json
- packages/macro/src/icu.test.ts
- packages/macro/src/icu.ts
- packages/macro/src/index.ts
- packages/macro/src/macroJs.test.ts
- packages/macro/src/macroJs.ts
- packages/macro/src/macroJsx.test.ts
- packages/macro/src/macroJsx.ts
- packages/macro/src/utils.ts
- packages/macro/test/index.ts
- packages/macro/test/js-arg.ts
- packages/macro/test/js-defineMessage.ts
- packages/macro/test/js-plural.ts
- packages/macro/test/js-select.ts
- packages/macro/test/js-selectOrdinal.ts
- packages/macro/test/js-t.ts
- packages/macro/test/jsx-plural.ts
- packages/macro/test/jsx-select.ts
- packages/macro/test/jsx-selectOrdinal.ts
- packages/macro/test/jsx-trans.ts
- packages/macro/tsconfig.json
- yarn.lock
No logic changes. Added types wherever possible and fix issues. Also added few more tests for "black zones".
> refactor(macro): make code strongly typed

- packages/macro/src/index.ts
This PR fixes #1300 and #1301.
The original PR #1298 fixing #1297 moved the `alreadyVisitedCache` cache and `alreadyVisited` function into the body of `macro` function thus resulting in incorrect behavior. I have moved these back to the root of `macro/src/index.ts` file with leaving the original change from array to WeakSet intact.
| English | Translation |
| ------------- | ------------- |
| #: App.js:10<br>msgid "Test string using Trans macro"<br>msgstr "Test string using Trans macro"  | #: App.js:10<br>msgid "Test string using Trans macro"<br>msgstr "" |
| #: App.js:11<br>msgid "Test string using t macro"<br>msgstr "Test string using t macro" | #: App.js:11<br>msgid "Test string using t macro"<br>msgstr "" |
| #: App.js:9<br>msgid "form.friend.name.label"<br>msgstr …
> fix(macro): Extraction not working correctly

- package.json
- yarn.lock
All bundlers actually consume ESM version of packages. CJS version is usually used by nodejs. So it's make more sense to test ESM versions for the size because it will bundled and shipped to the browser. 
I had to rise the limit for `@lingui/core package` to 5.5kb. It's not related to CJS/ESM change, it's related to `size-limit` dependecy update. It uses fresher bundlers which generate a slightly bigger results for both targets (CJS/ESM) i've tested it both with esbuild and webpack bundlers.
> chore(size-limit): test esm packages and update size-limit dep

- packages/cli/src/lingui-compile.ts
This PR fixes #1233.
Previously, the catalogs were not merge even if `catalogsMergePath` option was provided in the configuration. The `getCatalogForMerge()` function was never called from the code (it was used only in tests).
> fix(cli): catalogsMergePath doesn't merge catalogs

- .github/workflows/size-limit.yml
The previous PR #1333 probably was a bit incorrect, reverting it back (added the `reopened` type also)
> ci: fix the 'size-limit' workflow (2)

- packages/cli/package.json
This PR fixes the incorrect `main` entry in `package.json` of `@lingui/cli`. This was [causing Bundlephobia to report ](https://bundlephobia.com/package/@lingui/cli@3.16.0) `EntryPointError` on the new 3.16.0 version of the package.
> fix(cli): incorrect main entry in package.json

- package.json
- packages/cli/package.json
- yarn.lock
This PR reverts the update of the Typescript package made in #1357 which caused the following error in the `create-react-app` example when running the `react-scripts start` command:
> `TypeError: Cannot assign to read only property 'jsx' of object **'#<Object>'`
This shows we need to have stronger integration tests put in place.
> fix(build): Revert typescript update

- .github/workflows/release-test.yml
- scripts/verdaccio-release.js
Using trial & error approach found that if we version & publish in one command we can completely remove manipulation with git state. 
I also enabled this WF for pull requests because it's very nice to have e2e tests run automatically. 
And i'm going in next iterations to extend this script to run tests not only in CRA project but also in rest examples as well
> chore(verdaccio): setup verdaccio integration test on PR + fix execution

- CONTRIBUTING.md
I've found that with yarn it's possible to update by scope + with custom registry in one command without a necessity to rollback registry. 
Added this to the contribution guide.
Fell free to change wording or improve formatting if you have any ideas. I'm bad at writing docs.
> chore(): improve contributing guide

- packages/babel-plugin-extract-messages/test/index.ts
- packages/macro/test/index.ts
During working on latest PRs i noticed that macro in tests resolved from './build' instead of "./src" that makes development tricky. This PR fixes this behaviour.
> test(): properly resolve path to macro in tests

- packages/macro/src/macroJs.ts
- packages/macro/test/js-defineMessage.ts
- packages/macro/test/js-t.ts
- website/docs/ref/macro.md
This PR fixes #1379.
The current implementation of macros was stripping non-essential props (`message` and `comment`) only in JSX macros, not in JS macros. This PR brings the stripping of these props in JS macros on par with JSX macros.
There are several changes to the `macroJs.js` file, but most of them are changes from Prettier. The only change to code relating to this bug is the implementation at the end of the `processDescriptor()` function.
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for …
> fix(macro): JS macros don't strip non-essential props in production

- packages/cli/package.json
- packages/macro/package.json
This is a partial fix for undeclared dependencies.  https://github.com/lingui/js-lingui/issues/1385
- `@messageformat/parser` is used in `packages/cli/src/api/formats/po-gettext.ts` but was not declared for `@lingui/cli`
- `@babel/types` used in macro but was not declared. 
But: 
```yaml
yarnPath: .yarn/releases/yarn-3.3.1.cjs
packageExtensions:
"@lingui/cli@*":
dependencies:
"@messageformat/parser": "*"
"@lingui/macro@*":
dependencies:
"@babel/types": "*"
"@lingui/conf@*":
dependencies:
"@types/node": "*"
typescript: "*"
"@lingui/loader@*":
dependencies:
"@babel/core": "*"
typescript: "*"
```
Yarn complaining about few other dependencies as well. These are peer dependencies of a transitive dependencies and i didn't find an explainer what should we do in this case. 
Take for example …
> fix(build): undeclared dependencies

- package.json
- packages/cli/package.json
- test/typescript-nodenext-resolution/package.json
- yarn.lock
> chore: update typescript

- packages/react/src/Trans.test.tsx
- packages/react/src/format.test.tsx
- packages/react/src/format.ts
- website/docs/misc/react-intl.md
- website/docs/ref/react.md
This PR fixes #1400 by allowing the tag names to be not only digits, but letters as well.
For more information, please visit the original issue #1400.
> fix: Named components not working in Trans in @lingui/react

- packages/conf/package.json
- packages/conf/src/index.ts
This PR is attempt to fix: https://github.com/lingui/js-lingui/issues/1401
[cosmiconfig-typescript-loader](https://github.com/Codex-/cosmiconfig-typescript-loader/blob/main/lib/loader.ts) written in the way that it doesn't matter do you really load a Typescript file in config or not, once this loader is added to cosmiconfig it requires ts-node and typescript. This is indeed unwanted behavior because some of the users may not have them and may not want to use them at all. 
This PR changes 2 things: 
1. Lazy load the loader, once cosmiconfig discovered a config with ts extension
2. Add peerDependecies on `typescript` and `ts-node` for the `@lingui/conf` package. And also i marked them as optional. 
Why this happened? Why our test didn't catch this? 
It's because node modules resolution …
> fix(conf): lazy load cosmiconfig's TypeScriptLoader

- jest.config.js
By default Jest collect coverage only from files which included in compilation. This produce inaccurate coverage. This change brings collecting coverage from all files.
> chore(tests): collect coverage from all files, not only included in tests

- website/docs/tools/introduction.md
- website/docs/tutorials/react.md
- website/docs/tutorials/setup-cra.md
- website/docs/tutorials/setup-react.md
JS Config is better than json in almost every aspect. Let's encourage user's to use this type of configs instead of `.linguirc`
**Benefits:**
1. Syntax highlighting out of the box, without need to setup your IDE (`.linguirc` has a custom extension, so it would be plain text by default, not a json)
2. Autocomplete, thanks to typescript types and jsdoc comment
3. Support comments
4. Can be dynamically produced. For example list of locales could be reused from nextjs config. 
5. It's flexible for every setup. 
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
> docs(config): encourage user to use js config instead of json

- packages/cli/src/lingui-extract-template.ts
- packages/cli/src/lingui-extract.ts
I am not sure what are the conventional of using the `console.log` vs `console.error` here, but I think `log` is better in these cases.
> refactor: no `console.error` on informational output

- packages/cli/package.json
- packages/cli/src/api/formats/index.ts
- packages/cli/src/api/formats/po-gettext.test.ts
- packages/cli/src/api/formats/po-gettext.ts
- packages/cli/src/api/formats/po.test.ts
- packages/cli/src/api/formats/po.ts
- packages/cli/src/api/utils.ts
- yarn.lock
I want to clean up code and have full typings coverage in the cli before i can start to work on new features.
Rewrite formats to the typescript.  Reduced code duplication between po / po-gettext formats.
No changes in logic.
> refactor(cli): add TS typings remove code duplication in po / po-gettext formats

- packages/cli/src/lingui-extract.ts
This avoids a racing when run extract with `--watch` (no debounce) when multiple files changed together (or in a very short period of time)
Fixes [# 1434](https://github.com/lingui/js-lingui/issues/1434)
> fix: chain extract on watched file changes

- packages/macro/src/index.ts
- packages/macro/src/macroJsx.test.ts
- packages/macro/src/macroJsx.ts
- packages/macro/test/jsx-trans.ts
- packages/macro/tsconfig.json
This PR adding syntax support for `ConditionalExpressions` in JSX Macro: 
```ts
import { Trans } from '@lingui/macro'
<Trans>Hello, {props.world ? <Trans>world</Trans> : <Trans>guys</Trans>}</Trans>
```
To make reviewing easier, i split changes into 2 commits.
- First  commit refactoring JSX macro to operate with babel's `path` instead of `node`
- Second commit fix actual issue. 
We need `path` because babel doesn't allow traversing over plain `node`. And manual traversing wasn't a case here because there might be a syntax which we didn't expect. (multiple nested ternaries or function call which accepts jsx node, etc)
Also issue in SWC version repo: https://github.com/lingui/swc-plugin/issues/16
[//]: # (Describe the big picture of your changes here to communicate to the maintainers why …
> feat(macro): support JSX macro inside conditional expressions

- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/extractors/babel.ts
- packages/cli/src/api/extractors/index.ts
- packages/cli/src/api/extractors/typescript.ts
- packages/cli/src/api/stats.ts
- packages/cli/src/lingui-extract-template.ts
- packages/cli/src/lingui-extract.ts
- packages/cli/src/tests.ts
- packages/conf/src/__snapshots__/index.test.ts.snap
- packages/conf/src/makeConfig.ts
- packages/conf/src/migrations/normalizeRuntimeConfigModule.test.ts
- packages/conf/src/migrations/normalizeRuntimeConfigModule.ts
- packages/conf/src/migrations/setCldrParentLocales.ts
- packages/conf/src/types.ts
- packages/conf/tsconfig.json
- packages/macro/src/index.ts
Extracted non-related changes from https://github.com/lingui/js-lingui/pull/1440
Before this change config was reading separately in cli and macro. Read issue: https://github.com/lingui/js-lingui/issues/1416
Now config passed down to the macro from cli. This greatly helps in testing, because you can pass config to command and everything work just fine.
Other changes: 
- I extracted normalization for `runtimeConfigModule` into `conf` package and wrote a separate test. So now macro is not responsible for this normalization.
Fixes https://github.com/lingui/js-lingui/issues/1416
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If …
> refactor: pass config directly to macro

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/getTranslationsForCatalog.test.ts
- packages/cli/src/api/getTranslationsForCatalog.ts
- packages/cli/src/lingui-compile.ts
- packages/cli/src/test/__snapshots__/compile.test.ts.snap
- packages/cli/src/test/compile.test.ts
- packages/conf/src/types.ts
- packages/snowpack-plugin/src/index.ts
- packages/vite-plugin/src/index.ts
https://github.com/lingui/js-lingui/pull/1440#issuecomment-1434353740
> Yesterday I thought that i was close to finish this task, but inverting logic with explicit-id flag revealed many issues in the other part of code which should be fixed to get this merged.
>
> Many of them due to the fact that while compiling catalogs lingui operates with only key and translation, where key is a natural language string. Many places in the code works based on that assumptions, and in many places there is a fallback to the "key" if no translation found.
>
> With new hashbased id, key is always a hash, and this fallback just doesn't work. Instead, i should change the logic to operate with id, source string, translation, and in case there are no translation fallback to source string first and to id as …
> refactor: getTranslations, prepare for hash-based ids

- packages/cli/src/services/translationIO.ts
Looks like we only exclude pseudo while `init` but not `sync`, might be just an oversight, as I was touching it, so I also added the types for the config object.
Fixes https://github.com/lingui/js-lingui/issues/1454
> fix: exclude pseudo locale during sync 

- packages/vite-plugin/README.md
- packages/vite-plugin/index.js
- packages/vite-plugin/package.json
- packages/vite-plugin/src/index.ts
- packages/vite-plugin/test/index.ts
- packages/vite-plugin/tsconfig.json
- website/docs/ref/vite-plugin.md
I don't see a way to fix that other than change default export to named.
if i make vite-plugin package true ESM, it requires other packages also being ESM (lingui/conf + lingue/cli/api)
and that's not possible for many different reasons
Usually, when you use transpires, they insert an "interop" for all default imports. That interop actually checking if there a "default" property.
Native nodejs ESM loader obviously doesn't have it. So commonjs modules transpiled from ESM source is not supported by node in aspects of default exports. 
it's a common issue in other packages as well. So to normally work with native ESM you either should be fully ESM itself, or not use default export as a workaround.
Now package exports both, default and named exports. I also updated documentation to use named …
> fix(vite-plugin): change default export to named export

- packages/babel-plugin-extract-messages/src/index.ts
- packages/cli/package.json
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/extractors/babel.ts
- packages/cli/src/api/fixtures/collect-inline-sourcemaps/componentB.jsx
- packages/conf/src/types.ts
- yarn.lock
Babel doesn't support inputSourceMaps in parse. It means all location reported in extractor plugin is a source location, not a mapped. In other words sourcemaps have no effect. 
This PR adds support for inlined and explicticly passed (from custom extractor for ex.) sourcemaps. 
> feat(extractor): respect sourcemaps

- packages/macro/src/index.ts
- packages/macro/src/macroJs.test.ts
- packages/macro/src/macroJs.ts
- packages/macro/src/macroJsx.test.ts
- packages/macro/src/macroJsx.ts
- packages/macro/test/js-defineMessage.ts
- packages/macro/test/js-plural.ts
- packages/macro/test/js-t.ts
- packages/macro/test/jsx-plural.ts
- packages/macro/test/jsx-trans.ts
Support for all macros.: 
```ts
import { t as t2 } from '@lingui/macro';
const a = t2`Message`;
```
Looks like this is a rare case, because no one has raised the issue so far. But that is quite common case if code after other transpiler would be passed to lingui (custom extractor case)
> feat(macro): support renamed identifiers in macro

- packages/vite-plugin/src/index.ts
Tell Vite to not trying to bundle macro code which is not supposed to be in browser anyway
Fixes: https://github.com/lingui/js-lingui/issues/1464
> fix(vite): externalize macro imports.

- packages/cli/src/api/catalog.ts
- packages/cli/src/api/formats/index.ts
- packages/cli/src/api/formats/po-gettext.ts
- packages/cli/src/api/formats/po.ts
Currently extract to template supported only for "po" format. This is limited only by extension ".pot" which is hard-coded. This PR allows formatters to define their own extension for the template file. 
Extracting to template differs from usual extraction only in the absence of merge existing catalogs with incoming. 
So you can extract template in json format, such as `messages.json`
> refactor(catalog): read template extension from formatter

- packages/conf/package.json
- packages/conf/src/getConfig.ts
- yarn.lock
As i mentioned: 
> i've found very promising https://github.com/unjs/jiti and https://github.com/unjs/c12 we should give them a try. These packages powering a Nuxt framework.
Unfortunately we can't use `c12` because it load asynchonously but we can incorporate `jiti` instead of `cosmiconfig-typescript-loader` / `ts-node`. 
Looks like jiti was created for such usecases, where `ts-node` is not. The benefit of using jiti over `ts-node`: 
1. Supports cache (v8, require and hard cache on the file system of transpiled files)
2. Executes only this require in "context" of transpilation. 
The problem with ts-node is that once it registered it starts processing all require calls in the current VM. That caused that not only config with it's dependecies get transpiled but also other code running in …
> chore: use jiti for ts config loading

- packages/macro/src/macroJs.ts
- packages/macro/test/js-t.ts
Currently passing a custom i18n instance to the `t` macro only supports passing identifier, although any expression should be valid.
For example this currently crashes during extraction:
```ts
t(context.intl)`Hello`;
```
This changes the check from `isIdentifier` to `isExpression` so we can support function calls or member properties.
> fix: allow passing any expression as custom i18n instance

- packages/babel-plugin-extract-messages/src/index.ts
- packages/babel-plugin-extract-messages/test/index.ts
Actually, this bug is a bit wider: 
https://github.com/lingui/js-lingui/issues/1432
The extractor don't rise warning only if `Identifier` is used as first argument. But user may pass `foo.bar` (MemeberExpression) or even function call. 
This PR fixes this cases by actually disabling this check entirely. Because any syntax could be used for translation. 
The check of empty ID is still works with other usaceases, such as Macro, ObjectExpression, etc
I also refactored extracting an id from `i18n._()` and now it supports template literals as well as string concatenation. 
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the …
> fix(extractor): allow i18._(foo.bar) without warning.

- packages/core/src/compile/compileMessage.test.ts
- packages/core/src/formats.ts
It's a corner case but I think the test case explains it
> fix: do not ignore empty plural values

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/conf/src/types.ts
- website/docs/ref/conf.md
SInce the hash id support is in, the `messageId` now becomes the `linguiId` when custom id is absent. This is a change of behavior compared to v3, so its worth clarifying in the doc.
And to preserve the v3 behavior as much as we can, I am adding a new orderBy (`message`), so when no custom id is used, the order by `message` should match what `messageId` is expected in v3.
Fixes # (issue) https://github.com/lingui/js-lingui/issues/1514
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …
> feat: clarify the order by `messageId` in v4 and support order by message

- packages/cli/test/extract-po-format/expected/en.po
- packages/cli/test/extract-po-format/expected/pl.po
- packages/cli/test/extract-template-po-format/expected/messages.pot
- packages/conf/src/__snapshots__/index.test.ts.snap
- packages/conf/src/makeConfig.ts
- website/docs/ref/conf.md
- website/docs/releases/migration-4.md
more context in https://github.com/lingui/js-lingui/pull/1515#issuecomment-1468275117, in short, we want to switch default orderBy to the newly added `message` (source message) to match (more) with the behavior in v3.
Fixes # (issue) n/a
> feat: change default orderBy to `message`

- packages/macro/src/macroJs.test.ts
- packages/macro/src/macroJs.ts
- packages/macro/test/js-plural.ts
- packages/macro/test/js-select.ts
- packages/macro/test/jsx-plural.ts
- packages/macro/test/jsx-select.ts
to fix https://github.com/lingui/js-lingui/issues/1522
Fixes # (issue) https://github.com/lingui/js-lingui/issues/1522
> fix: expression only choices / select options

- packages/macro/__typetests__/index.test-d.tsx
- packages/macro/index.d.ts
`other` should be required for choice macros, and looks like we do have it as required for `SelectOptions`, `SelectChoiceProps`  and `PluralChoiceProps`, just not `ChoiceOptions` which is probably not intended.
and ICU message without `other` may be invalid:
> fix(macro types): mark `other` as required for ChoiceOptions

- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/catalog/__snapshots__/getCatalogs.test.ts.snap
- packages/cli/src/api/catalog/getCatalogs.test.ts
- packages/cli/src/api/catalog/getCatalogs.ts
- packages/cli/src/api/formats/index.ts
- packages/cli/src/api/formats/po.ts
- packages/cli/src/api/stats.test.ts
- packages/cli/src/extract-experimental/getExperimentalCatalogs.ts
- packages/cli/src/lingui-compile.ts
- packages/cli/src/lingui-extract-experimental.ts
- packages/cli/src/lingui-extract-template.ts
- packages/cli/src/lingui-extract.ts
- packages/cli/src/tests.ts
- packages/loader/src/webpackLoader.ts
- packages/vite-plugin/src/index.ts
- packages/vite-plugin/tsconfig.json
to be able to `import('format')` getFormat() function should be async
> refactor(cli): make getFormats asynchronous, prepare for ESM

- packages/react/src/I18nProvider.test.tsx
- packages/react/src/I18nProvider.tsx
- packages/react/src/index.ts
- website/docs/ref/react.md
- website/docs/releases/migration-4.md
- website/sidebars.ts
fixes #1136 
While working on #1426 I noticed the issue reported in #1136. Using a custom key in the I18nProvider results in remounting of the whole app which is not a standard practice in React providers.
If someone needs to do remounting, I would suggest they implement this themselves, but the lingui/react library should not do this out of the box. The PR removes the usage of `key` prop altogether.
Breaking changes:
Previously the whole app would re-mount when calling `activate()` or `load()` and this will no longer be the case. If someone uses translations in their components using just 
```
t`some string` 
```
then those occurrences will not re-render. This, I believe, is correct behavior. We need to document how to make those places re-render - ~~I'm not really sure myself~~ using …
> fix: do not remount children of I18nProvider

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/test/extract-po-format/expected/en.po
- packages/cli/test/extract-po-format/expected/pl.po
- packages/cli/test/extract-template-po-format/expected/messages.pot
- packages/cli/test/extractor-experimental-clean/expected/about.page.en.po
- packages/cli/test/extractor-experimental-clean/expected/about.page.pl.po
- packages/cli/test/extractor-experimental-clean/expected/index.page.en.po
- packages/cli/test/extractor-experimental-clean/expected/index.page.pl.po
- packages/cli/test/extractor-experimental-template/expected/about.page.messages.pot
- packages/cli/test/extractor-experimental-template/expected/index.page.messages.pot
- packages/cli/test/extractor-experimental/expected/about.page.en.po
- packages/cli/test/extractor-experimental/expected/about.page.pl.po
- packages/cli/test/extractor-experimental/expected/index.page.en.po
- packages/cli/test/extractor-experimental/expected/index.page.pl.po
- packages/format-po-gettext/src/__snapshots__/po-gettext.test.ts.snap
- packages/format-po/README.md
- packages/format-po/src/__snapshots__/po.test.ts.snap
- packages/format-po/src/po.test.ts
- packages/format-po/src/po.ts
Newly introduced `js-lingui-id` creates a lot of noise in po files and may cause merge conflicts. This PR makes it optional and disabled by default. All tests snapshots got updated.
> refactor(formatter-po): ability to disable lingui-id, make it false by default

- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog/getCatalogs.test.ts
- packages/cli/src/api/catalog/getCatalogs.ts
- packages/cli/src/api/formats/formatterWrapper.test.ts
- packages/cli/src/api/formats/formatterWrapper.ts
- packages/cli/src/api/formats/index.ts
- packages/cli/src/extract-experimental/getExperimentalCatalogs.ts
- packages/cli/src/lingui-compile.ts
- packages/cli/src/lingui-extract-experimental.ts
- packages/cli/src/tests.ts
- packages/conf/src/types.ts
- packages/format-json/src/json.test.ts
- website/docs/guides/custom-formatter.md
Pass sourcelang to the formatters
> refactor(cli): extend formatters api with source lang

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog/extractFromFiles.ts
- packages/conf/src/types.ts
- packages/format-json/src/__snapshots__/json.test.ts.snap
- packages/format-json/src/json.test.ts
- packages/format-po-gettext/src/__snapshots__/po-gettext.test.ts.snap
- packages/format-po-gettext/src/po-gettext.test.ts
- packages/format-po/src/__snapshots__/po.test.ts.snap
- packages/format-po/src/po.test.ts
- packages/format-po/src/po.ts
While working on a new xliff formatter realized that current shape of CatalogType and ExtractedMessage are tightly coupled to shape of the message of Pofile. There some properties which is related to po formatter only and should not be in the core type. 
The same with other formatters. For example xliff may have additional attributes such as `state=final` which we also should store somewhere to not lost when extracting.  So there should be a way to add some `extra` fields which would be preserved by cli and returned back to formatter. 
In scheme it something like
formatter.parse -> extra: {special field} -> cli catalog processing -> formatter.serialize (get the same extra: {special field}) 
Notes: 
i renamed extractedComments -> comments.  this naming was because Pofile has it. When it's …
> refactor(cli/catalog): decouple catalog type from Po message shape

- website/docs/tutorials/setup-vite.md
Since #1465 changed the default export from `@lingui/vite-plugin` to a named export, [the setup guide for vite](https://lingui.dev/tutorials/setup-vite) is outdated and can't be used without knowledge that you need to rewrite the import statement.
This PR updates the setup guide to correctly reflect this change.
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …
> docs: Update lingui import statement in setup-vite.md

- website/docs/tutorials/setup-vite.md
> docs(vite-setup): add missing dependencies and show ts configuration

- website/docs/tutorials/react-patterns.md
noticed from here https://github.com/lingui/js-lingui/discussions/1479#discussioncomment-5411700
> docs(): fix react pattern docs

- packages/core/src/i18n.ts
- packages/react/package.json
- packages/react/src/Trans.test.tsx
- packages/react/src/Trans.tsx
- yarn.lock
The `Trans` component accepts `component` and `render` props that have pretty much the same purpose.
However, when you use the `render` callback, the callback receives 
```
export type TransRenderProps = {
id: string
translation: React.ReactNode
message?: string | null
isTranslated: boolean
}
```
and when you use `component`, it only receives `{ children: React.ReactNode }` (where `children = translation`).
To me, it makes sense that these two approaches are unified, and you receive the same information when you use `render` and `component` props.
This PR does just that, without introducing another TS type, which means that the `translation` and `children` are duplicated in the `i18nprops: TransRenderProps` object. I don't think it's a huge deal but we could also introduce separate types …
> fix(trans): align render callback and 'component' prop

- packages/core/src/i18n.ts
- packages/macro/global.d.ts
https://github.com/lingui/js-lingui/discussions/1479#discussioncomment-5443272
Historically, MessageDescriptor was used in macro and in the underlying runtime functions. Because for macro it wasn't required to specify all properties for MessageDescriptor they all was marked as optional. 
Since we have now more clarified typings for macro which have it's own MessageDescriptor type we can make core's MessageDescriptor is more strict and reflecting real runtime structure. 
MessageDescriptor is returned from defineMessage macro or used in i18n._ methods. They both always returns and requires id to be set. 
[//]: # (_Put an `x` in the boxes that apply. You can also …
> fix(core): improve MessageDescriptor typings. id is always present

- examples/js/src/locale/cs/messages.po
- examples/js/src/locale/en/messages.po
- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/fixtures/messages.po
- packages/cli/test/extract-po-format/expected/en.po
- packages/cli/test/extract-po-format/expected/pl.po
- packages/cli/test/extract-template-po-format/expected/messages.pot
- packages/format-po-gettext/src/__snapshots__/po-gettext.test.ts.snap
- packages/format-po-gettext/src/fixtures/messages_plural-4-letter.po
- packages/format-po-gettext/src/fixtures/messages_plural.po
- packages/format-po-gettext/src/po-gettext.test.ts
- packages/format-po-gettext/src/po-gettext.ts
- packages/format-po/src/__snapshots__/po.test.ts.snap
- packages/format-po/src/fixtures/messages.po
- packages/format-po/src/po.test.ts
- packages/format-po/src/po.ts
fixes https://github.com/lingui/js-lingui/issues/1573
> fix(po-formatter): save explicit id flag in comments instead of flags

- packages/detect-locale/package.json
this is breaking our jest as the default jest resolver ([`resolve.exports`](https://github.com/lukeed/resolve.exports/) with default conditions (`['require', 'default' ...]`)) will try to pull in asset listed in the package, and the mapping on `require` for detect-locale was pointing to `mjs` instead of `cjs`.
I have double checked and this seems to be the only one across all lingui packages ;)
Fixes https://github.com/lingui/js-lingui/issues/1575
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look …
> fix: require should use cjs instead of mjs

- packages/react/src/Trans.test.tsx
- packages/react/src/Trans.tsx
- packages/react/src/format.ts
fix https://github.com/lingui/js-lingui/issues/1592
Fixes https://github.com/lingui/js-lingui/issues/1592
> fix: support array of react components in values

- packages/cli/package.json
- test/cli-version/index.js
- test/cli-version/package.json
- test/node-api-esm/index.js
- test/node-api-esm/package.json
- yarn.lock
- Remove stricter `require` export condition to be able to import `@lingui/cli` from ESM context.  See conversation https://discord.com/channels/974702239358783608/974704045346394172/1097863445459783750
- Add tests for this case, as well for the `lingui --version` command
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is …
> fix(cli): allow import from ESM context, add tests

- jest.config.js
- lerna.json
- packages/extractor-vue/README.md
- packages/extractor-vue/package.json
- packages/extractor-vue/src/__snapshots__/extractor.test.ts.snap
- packages/extractor-vue/src/extractor.test.ts
- packages/extractor-vue/src/fixtures/test.vue
- packages/extractor-vue/src/index.ts
- packages/extractor-vue/src/vue-extractor.ts
- tsconfig.json
- website/docs/tutorials/extractor-vue.md
- website/sidebars.ts
- yarn.lock
> feat: add new package with vue extractor

- packages/cli/src/api/index.ts
- packages/extractor-vue/README.md
- packages/extractor-vue/src/vue-extractor.ts
- tsconfig.json
- website/docs/guides/custom-extractor.md
- website/docs/tutorials/extractor-vue.md
https://github.com/lingui/js-lingui/pull/1623#discussion_r1178935388
If you have a ESM project and will try to use `vue-extractor` the import inside vue-extractor: 
```ts
import babel from "@lingui/cli/api/extractors/babel"
```
Will fail. This is happened because `@lingui/vue-extractor` is a  dual package code.
In ESM context nodejs picking `.mjs` file (following `import` condition in package.json) which tries to import  `@lingui/cli/api/extractors/babel` which is cjs downleveld from ESM and the way how typescript compiles to cjs is not compatible with native ESM modules (additional .default appears) 
This all is a big non-solvable headache, which simply could be avoided by banning `export default`
> fix(vue-extractor): fix default export burden with /api/extractors/babel

- packages/macro/src/index.ts
To simplify identifying  problematic code, show a code frame where the macro was unable to process code.  This makes issues like that https://github.com/lingui/js-lingui/issues/1616 much easier to solve. 
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging …
> refactor(macro): show codeframe when error happened in macro

- packages/macro/package.json
- yarn.lock
Lerna can't automatically bump package versions for `peerDependencies`. https://github.com/lerna/lerna/issues/2402
So I decided to use the `^` for the version specifying. This will allow continuing using the Lerna version bumping without the need to bump the `peerDependencies` versions.
> chore: use ^version notation for peerDependencies

- packages/cli/src/api/catalog.ts
- packages/cli/src/api/catalog/getCatalogDependentFiles.test.ts
- packages/cli/src/api/catalog/getCatalogDependentFiles.ts
- packages/cli/src/api/catalog/getFallbackListForLocale.test.ts
- packages/cli/src/api/catalog/getFallbackListForLocale.ts
- packages/cli/src/api/catalog/getTranslationsForCatalog.ts
- packages/cli/src/api/index.ts
- packages/loader/src/webpackLoader.ts
- packages/vite-plugin/src/index.ts
Catalog compiler operates on a bunch of files when compiling one catalog (template + fallbacks + source language). Loaders in bundlers expecting deterministic results, meaning for the same source it should always produce the same result. 
Currently, implementation of webpack loader / vite plugin does not respect catalog dependencies. That breaks caching in Webpack and watch mode (catalog will not be rebuilt if one of the dependencies changed)
This PR brings tracking of all catalog dependencies and should resolve mentioned issues. 
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of …
> feat(webpack + vite): Ensure that bundlers respect catalog dependencies

- packages/message-utils/compileMessage.js
- packages/message-utils/generateMessageId.js
Previously, I wrote something non-workable. This time it should work.
Fixes: https://github.com/lingui/js-lingui/issues/1633
> fix(message-utils): workaround package.json exports field for older runtimes

- packages/cli/package.json
- packages/cli/src/api/catalog/getCatalogDependentFiles.test.ts
- packages/cli/src/api/catalog/getCatalogDependentFiles.ts
- packages/loader/src/webpackLoader.ts
- packages/loader/test/json-format/lingui.config.ts
- packages/loader/test/po-format/.linguirc
- packages/vite-plugin/src/index.ts
- packages/vite-plugin/test/json-format/lingui.config.ts
- packages/vite-plugin/test/po-format/.linguirc
- yarn.lock
Fixing a bug introduced in https://github.com/lingui/js-lingui/pull/1654 
Closes: https://github.com/lingui/js-lingui/issues/1661
Vite's `addWatchFile` does not have a file existance check as webpack has, so i have to add check it manually before. 
Also, we need an e2e tests for /example projects. Because this kind of things really hard to test from build side.
> fix(webpack + vite): fix dependency watching in loader

- packages/core/src/interpolate.test.ts
- packages/core/src/interpolate.ts
fix https://github.com/lingui/js-lingui/issues/1664
Fixes https://github.com/lingui/js-lingui/issues/1664
> fix: fallback to `other` only when undefined

- examples/create-react-app/package.json
- examples/create-react-app/yarn.lock
- examples/js/package.json
- examples/js/yarn.lock
- examples/nextjs-babel/package.json
- examples/nextjs-babel/yarn.lock
- examples/nextjs-swc/package.json
- examples/nextjs-swc/yarn.lock
- examples/react-native/package.json
- examples/react-native/yarn.lock
- examples/vite-project-react-babel/package.json
- examples/vite-project-react-babel/yarn.lock
Use the newest version in the example projects
> chore: bump version in examples

- packages/format-po/README.md
- packages/format-po/src/po.test.ts
- packages/format-po/src/po.ts
- website/docs/releases/migration-4.md
- website/docs/tutorials/react-patterns.md
- website/docs/tutorials/react.md
As was raised few time on github issues and discord, people experiencing troubles while migrating catalogs with explicit IDs. This PR adds documentation as well as a new option for `po-format` which is aimed to make migration smoother. 
Related: https://github.com/lingui/js-lingui/issues/1667
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're …
> feat(po-format): add `explicitIdAsDefault` for po-format for easier migration

- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/extractors/babel.ts
- packages/cli/src/api/fixtures/collect-typescript-jsx/jsx-in-js.js
It seems it's quite common to have JSX in *.js files (not *.jsx)
https://github.com/lingui/js-lingui/issues/1638#issuecomment-1567093390
> fix(extractor): support jsx in js files

- .github/verdaccio/config.yaml
- .github/workflows/release-test.yml
- scripts/verdaccio-integration.ts
it seems that Verdaccio integration script doesn't work properly. It tests against latest published version to NPM instead of locally published to Verdaccio. Yarn Berry does not respect `npm config set registry` instead specific to yarn commands should be used.
> test(verdacio-integration): use yarn berry command to update lingui deps

- website/docs/ref/swc-plugin.md
It seems it would be easier to spot this in the docs rather in the package readme.
> docs(swc-plugin): add compatibility note

- website/docs/releases/migration-4.md
Hi, the v4 migration page specifies a recommended pattern with "msg" but the associated import is still the old "t".
> docs: fix import in migration v4

- packages/format-po-gettext/src/__snapshots__/po-gettext.test.ts.snap
- packages/format-po-gettext/src/fixtures/messages_plural.po
- packages/format-po-gettext/src/po-gettext.test.ts
- packages/format-po-gettext/src/po-gettext.ts
In v4 this formatter can return `undefined` when passing a non-plural message to the `serializePlurals` function, which will throw later when serializing the PO file. The original item should be returned instead.
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …
> fix(format-po-gettext): bad return during mapping with `serializePlurals`

- packages/react/src/Trans.tsx
- website/docs/ref/react.md
Tested by publishing to Verdaccio and installing in a project of mine. Worked like a charm. The React Trans tests even use comment in `jsx-without-macros.js`.
https://github.com/lingui/js-lingui/issues/1713
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging …
> feat: allow comment prop on react Trans component

- packages/cli/src/api/extractors/babel.ts
- packages/cli/src/api/index.ts
This PR brings improvement for those who wants more flexibility in what files extractor could understand. It's covering https://github.com/lingui/js-lingui/issues/1717
When user has a Ecmascript feature which is not enabled in the parser by default there is only thing it could do about it.  Override extractor completely and pass all needed plugins manually. This is not future-proof solution, as user have to copy-paste lingui's default implementation and adjust it by its needs. 
Solution: I extracted from the default implementation a low level function `extractFromFileWithBabel` which is now a part of a public api and could be used in the userland.  I choosed this approach among others, because `parserPlugins` is not a static list and could vary depending on a file passed for extractor. So …
> feat(extractor): expose extractFromFileWithBabel function for better flexibility

- packages/core/src/index.ts
- packages/react/src/I18nProvider.test.tsx
- packages/react/src/I18nProvider.tsx
- packages/react/src/Trans.test.tsx
- packages/react/src/Trans.tsx
- packages/react/src/format.test.tsx
- packages/react/src/format.ts
- packages/react/tsconfig.json
This PR makes small changes to the react package: it makes the TS config stricter by enabling
```
"strict": true,
"noUncheckedIndexedAccess": true
```
nothing has really changed in terms of features. There is a small bug fix in TS typings for `Trans` that was caught by the stricter settigns.
> chore: strict ts config for react package

- packages/detect-locale/package.json
Fixes a bug where typescript types for the detect-locale package aren't being exported.  Currently using detect-locale in a TS project throws the following error:
```
Could not find a declaration file for module '@lingui/detect-locale'. '.../@lingui+detect-locale@4.3.0/node_modules/@lingui/detect-locale/dist/index.mjs' implicitly has an 'any' type.
There are types at '.../node_modules/@lingui/detect-locale/dist/index.d.ts', but this result could not be resolved when respecting package.json "exports". The '@lingui/detect-locale' library may need to update its package.json or typings.ts(7016)
```
[//]: # (_Put an `x` in the boxes that apply. You can also fill …
> fix: export ts types from detect-locale

- packages/react/package.json
- packages/react/src/I18nProvider.test.tsx
- packages/react/src/I18nProvider.tsx
- yarn.lock
this refactors the change subscription mechanism used in Lingui React Provider to use the `useSyncExternalStore` hook, which according to [this](https://github.com/reactjs/rfcs/blob/main/text/0214-use-sync-external-store.md#summary) offers better support for "concurrent rendering features like selective hydration and time slicing". That being said, I'm not sure how exactly this should be better. Maybe someone will chime in and add more insight.
Everything should work the same except:
Previously, when the Provider was re-rendered with different i18n instance of different `defaultComponent`, it would ignore them. This likely never was an issue, but technically speaking, it was a bug. Now that is fixed. 
What I removed is detection of the cases when i18n.change would happen (catalog update, …
> refactor: use useSyncExternalStore to subscribe for i18n updates

- packages/core/package.json
- yarn.lock
This bumps unraw to version 3.0.0. It fixes source map warnings found in https://github.com/iansan5653/unraw/issues/33.
After upgrading to newer version of `@lingui/core`, I started getting warnings like these due to unraw 2.0.1:
```bash
WARNING in ./.yarn/cache/unraw-npm-2.0.1-5ecb408b75-af9a9d2f6e.zip/node_modules/unraw/dist/index.js
Module Warning (from ./.yarn/__virtual__/source-map-loader-virtual-27a3af5d08/0/cache/source-map-loader-npm-3.0.1-4faa2e7eac-6ff27ba933.zip/node_modules/source-map-loader/dist/cjs.js):
Failed to parse source map from '.yarn\cache\unraw-npm-2.0.1-5ecb408b75-af9a9d2f6e.zip\node_modules\unraw\src\index.ts' file: Error: ENOENT: no such file or directory, open '/node_modules/unraw/src/index.ts'
```
Fixes https://github.com/iansan5653/unraw/issues/33.
> chore: bump unraw from 2.0.1 to 3.0.0

- packages/react/src/TransNoContext.tsx
- website/docs/ref/react.md
Small maintenance PR: this prop is not really documented and it's buggy, as seen in https://github.com/lingui/js-lingui/pull/1643#discussion_r1186893179
I tried to print a console warning when user accesses the prop so they get a message. However, React itself reads the props when calling createElement and so even if users don't use the prop, the warning would be logged. We'd need to do some heuristic on the stack trace to determine when to not print the warning and it wouldn't be pretty.
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to …
> chore: deprecate isTranslated prop

- website/docs/ref/macro.md
- website/docs/tutorials/explicit-vs-generated-ids.md
- website/docs/tutorials/react-patterns.md
- website/sidebars.ts
The main goal was to remove inconsistency in string-only macro usage (`t` and etc) 
Because of historical reasons we have many different ways to achieve the same result. Some of these approaches a considered harmful and it's better to avoid them and not advertise in the docs. 
For example these are gives mostly the same result: 
```ts
t`Hello`
t(i18n)(`Hello`)
i18n.t(msg`Hello`)
i18n._(msg`Hello`)
// in react context
const { _ } = useLingui();
_(msg`Hello`)
const { i18n } = useLingui();
i18n.t(msg`Hello`)
i18n._(msg`Hello`)
```
Where usage of global `t` is very confusing and bring "delayed" issues, which then hard to fix. 
So I propose to gradually removing global usage from docs, and encourage developers to always use i18n methods on a particular instance. 
While working on achieving …
> docs: add explicit vs generated id doc. Move to non-global string-only translations

- website/docs/introduction.md
Fixed inconsistency in docs related to bundle size
The small bundle size of 3kb is an important feature of the package. Therefor I believe it's important to leave out a possible missunderstanding in the example code blocks where it is stated that the bundle size is 5kb.
> docs: suggestive improvements on introduction

- packages/cli/src/lingui-compile.ts
This patch removes the following warning when I build my Project (TypeScript/Svelte/SvelteKit/svelte-i18n-lingui):
```
src/locales/en.d.ts (1:9) "Messages" is not exported by "node_modules/@lingui/core/dist/index.mjs", imported by "src/locales/en.d.ts".
```
> fix(cli): import type as type

- examples/nextjs-swc/src/utils.ts
Updated the assertion in `useLinguiInit` function to avoid double render in Next.js SWC example as per the suggestion given in #1814 
Fixes #1814 
> fix: double render due to wrong assertion

- packages/cli/src/api/catalog/getCatalogs.test.ts
- packages/cli/src/api/catalog/getCatalogs.ts
Escape parentheses in the pathname pattern according to the following issue: https://github.com/micromatch/micromatch/issues/123
The solution uses the simplest possible approach: the String#replace method. I considered the `escape-string-regexp` package, but it seems that `parentheses` are the only problematic characters.
Fixes #1819
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't …
> fix: allow parentheses in catalog pathnames

- packages/loader/src/webpackLoader.ts
The build emits warnings on Windows as described in detail at https://discord.com/channels/974702239358783608/974704045346394172/1141002196398391436.
This PR contains the fix described here https://discord.com/channels/974702239358783608/1136285611087626250/1141022716237987980.
Fixes https://github.com/lingui/js-lingui/issues/1705.
After this fix, Windows no longer emits the warnings. 
Tests are not affected.
[//]: # (_Put an `x` in the boxes that apply. You can also …
> fix: warnings about invalid dependencies on Windows

- packages/core/src/interpolate.test.ts
- packages/core/src/interpolate.ts
> fix: don't replace octothorpe coming from variable

- packages/cli/src/api/__snapshots__/compile.test.ts.snap
- packages/cli/src/api/compile.ts
- packages/cli/src/lingui-compile.ts
- website/docs/ref/cli.md
- website/docs/tutorials/react.md
- website/docs/tutorials/setup-react.md
Currently, running `lingui compile --typescript` produces a `.ts` (which contains javascript code) file along with `.d.ts` file with typings.
However, TypeScript, at least on my machine, ignores the typings file - which kinda makes sense given that the source file already has `.ts` extension. 
So it looks like this:
AFAICT, we should not mix `.ts` with `.d.ts`. What this PR does is that it removes the generation of the `d.ts` file and instead puts the types into the generated `.ts` file. I believe this should not have any unintended side effects. If it does, we should keep the `.d.ts` file but change the `.ts` file extension.
Additionally, I made some docs changes to "promote" the `--typescript` flag more. I think most users are not aware of it, yet it's nice to have.
[//]: # (What types …
> fix: compile should generate a TS file

- examples/create-react-app/package.json
- examples/nextjs-babel/package.json
- examples/nextjs-babel/src/components/Layout.tsx
- examples/nextjs-babel/yarn.lock
- examples/nextjs-swc/package.json
- examples/nextjs-swc/src/pages/index.tsx
- examples/nextjs-swc/yarn.lock
> docs(examples): update examples with useLingui macro

- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/lingui-extract.ts
- website/docs/ref/cli.md
Adds multiple locales support for `--locale` option, similar to the experimental extract implementation.
> feat(cli): support multiple locales in extract command

- website/docs/ref/conf.md
Include `catalogsMergePath` in [Lingui Configuration](https://lingui.dev/ref/conf) reference section in docs
Fixes #1879 
> docs: add `catalogsMergePath` in Lingui Configuration

- examples/nextjs-swc/package.json
Currently, the `package.json` has a small typo in build script. In my opinion, instead of `"build": yarn lang:extract && next build`
the build script should be `yarn lingui:extract && next build`.
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
> fix(typo): Correct typo in build script of nextjs-swc example

- examples/create-react-app/src/App.test.tsx
- examples/create-react-app/src/locales/cs.po
- examples/create-react-app/src/locales/en.po
- packages/babel-plugin-lingui-macro/src/index.ts
- packages/babel-plugin-lingui-macro/src/macroJs.test.ts
- packages/babel-plugin-lingui-macro/src/macroJs.ts
- packages/babel-plugin-lingui-macro/src/macroJsx.test.ts
- packages/babel-plugin-lingui-macro/src/macroJsx.ts
- packages/babel-plugin-lingui-macro/src/utils/cleanJSXElementLiteralChild.ts
- packages/babel-plugin-lingui-macro/test/fixtures/jsx-keep-forced-newlines.expected.js
- packages/babel-plugin-lingui-macro/test/fixtures/jsx-keep-forced-newlines.js
- packages/babel-plugin-lingui-macro/test/jsx-trans.ts
related discussion: https://github.com/lingui/js-lingui/discussions/1873
Found much better way to process whitespacing. 
Instead of merging all different types of JSX nodes (JSXText, JSXExpressionContainer -> StringLiteral, etc) into one big string and then trying to normalize whitespacing  in that string i instead utilize nodes information to understand what whitespacing rules should be applied. 
In other words: 
Before:
```ts
<Trans>Hello◦{"◦"}◦world</Trans> 
// -> normalizeWhitespace("Hello◦◦◦world")  we lost here information that middle space came from explicit `{"◦"}` 
```
After
```ts
<Trans>Hello◦{"◦"}◦world</Trans>
// there are strict rules how whitespaces processed in JSXText, 
// use `cleanJSXElementLiteralChild` function which follows this rules (taken from babel's sources) …
```
> refactor(macro): robust whitespace handling according to jsx spec

- packages/cli/package.json
- packages/format-po/package.json
- yarn.lock
This PR upgrades date-fns dependency from 2.16.1/2.29.3 to 3.6.0.
Our project has migrated to date-fns 3 recently, but we also use js-lingui extensively and it would be nice to have only one version of date-fns. Having both if flaky in our setup for some reason.
> chore: bump date-fns from 2.16.1/2.29.3 to 3.6.0

- packages/macro/index.d.ts
- packages/react/macro/index.d.ts
Make IDE to show them as deprecated
> refactor(macro): explicitly mark symbols as deprecated

- packages/babel-plugin-lingui-macro/src/macroJs.ts
- packages/babel-plugin-lingui-macro/src/macroJsx.ts
- packages/babel-plugin-lingui-macro/test/fixtures/js-t-continuation-character.js
- packages/babel-plugin-lingui-macro/test/js-t.ts
As other developers noted, whitespace trimming is in JS macro redundant and counterintuitive. 
If i write: 
```ts
t`Hello 
world`
```
I'm expecting to get a message with a line break in the middle, and don't expect this to be trimmed. 
Another example:
```ts
t`Label: ` + value
```
Note the space after ":", it's expected to be there, but "normalization" will remove it.
Other example would be a markdown, or just a whatever purpose user want to have an original formatting. 
This PR completely remove whitespace trimming from JS macro, and left the value as-is. 
There was an unclear logic around unicode escaping in template literals, which I also removed in favor of always "cooked" value.
The template literal has 2 values, [raw and cooked](https://exploringjs.com/impatient-js/ch_template-litera …
> refactor(macro): remove whitespace cleaning from js macro

- packages/react/src/Trans.test.tsx
- packages/react/src/TransNoContext.tsx
The `isTranslated` prop is undocumented and buggy.
> chore: remove the deprecated 'isTranslated' property

- packages/react/src/Trans.test.tsx
- packages/react/src/TransNoContext.tsx
Fixes https://github.com/lingui/js-lingui/issues/1904
Despite this is not marked as breaking change, but i expect this may start to behave differently for some users, that's why base of this PR is "next"
> fix(react): process falsy values with JSX semantics

- website/docs/tutorials/react.md
> docs: change the unnecessarily mocking tone of the React docs

- packages/core/src/i18n.ts
- packages/react/package.json
- packages/react/src/TransRsc.tsx
- packages/react/src/index-rsc.ts
- packages/react/src/server.ts
Bring to the React package primitives for comfortable work with RSC 
Related discussion: https://github.com/lingui/js-lingui/pull/1903#issuecomment-2049629831
Here is example using it: https://github.com/thekip/nextjs-lingui-rsc-poc/pull/3
> feat(react): native support react RSC

- packages/core/src/i18n.test.ts
- packages/core/src/i18n.ts
- packages/react/src/Trans.test.tsx
> fix: escaped curly-braces doesn't preserve in development mode 

- packages/core/src/interpolate.test.ts
- packages/core/src/interpolate.ts
Fixes #1927
Added appropriate test
> fix(core): pound symbol being replaced outside plural and selectordinal

- packages/cli/src/extract-experimental/bundleSource.ts
Prevents esbuild from erroring on `.scss` files during `lingui extract-experimental`. Although this can be solved locally with `experimental.extractor.excludeExtensions`, I figured the `.scss` extension is common enough that this PR may help someone else further on.
Below is the error I got when running the build:
```
✘ [ERROR] No loader is configured for ".scss" files: someStyle.scss
someJSFile.js:7:19:
7 │ import styles from './someStyle.scss';
╵                    ~~~~~~~~~~~~~~~~~~~~
```
When I add `.scss` to the excluded extensions, message extraction proceeds as expected. …
> fix: exclude .scss files from extract-experimental build

- packages/format-po/README.md
- packages/format-po/src/po.test.ts
- packages/format-po/src/po.ts
Support adding custom header attributes to the PO message catalog via the PO formatter config
This is particularly useful for localization tools that require custom PO file headers. For instance, CrowdIn requires the addition of a custom header attribute to enable a specific PO file parsing setting (more [here](https://store.crowdin.com/gnu-gettext#translating-gnu-gettext-po))
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the …
> feat(format-po): configure header attributes in PO file formatter

- packages/core/src/interpolate.test.ts
- packages/message-utils/src/compileMessage.test.ts
- packages/message-utils/src/compileMessage.ts
Current version of lingui will not handle following pluralisation correctly: `{count, plural, one {One} other {#} =13 {thirteen}}`. This PR fixes that.
I also added some tests, but maybe some dedicated test should be made, I'm not sure what the maintainer expect here.
Did not report the issue separately, as I already had the fix.
> fix(message-utils): correctly handle multi-digit complex argument cases

- packages/babel-plugin-extract-messages/src/index.ts
- packages/babel-plugin-lingui-macro/src/constants.ts
- packages/babel-plugin-lingui-macro/src/macroJs.ts
- packages/babel-plugin-lingui-macro/src/macroJsx.ts
- packages/babel-plugin-lingui-macro/src/messageDescriptorUtils.ts
- packages/babel-plugin-lingui-macro/test/__snapshots__/js-defineMessage.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/js-t.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/js-useLingui.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/jsx-plural.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/jsx-select.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/jsx-selectOrdinal.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/jsx-trans.test.ts.snap
- packages/babel-plugin-lingui-macro/test/fixtures/jsx-keep-forced-newlines.expected.js
- packages/babel-plugin-lingui-macro/test/fixtures/jsx-plural-select-nested.expected.js
- packages/babel-plugin-lingui-macro/test/js-t.test.ts
- packages/babel-plugin-lingui-macro/test/jsx-trans.test.ts
Use the same message descriptor with `/* i18n */` extraction mark in `<Trans>` component so extractor will support `TransNoContext` or [runtimeConfigModule](https://lingui.dev/ref/conf#runtimeconfigmodule) without explicit knowledge about them. 
Take the input: 
```ts
<Trans>Hello World</Trans>
```
Before
```tsx
<Trans id={"mY42CM"} message={"Hello World"} />;
```
After
```tsx
<Trans
{
/*i18n*/
...{
id: "mY42CM",
message: "Hello World",
}
}
/>
```
Where 
```ts
/*i18n*/
...{
id: "mY42CM",
message: "Hello World",
}
```
Is standard message descriptor used in `t` transformation. 
A side effect of this change is reduced code duplication between js and jsx macro.  …
> refactor(macro): use message descriptor for Trans

- packages/core/src/i18n.test.ts
- packages/core/src/i18n.ts
Lingui Core - i18n._(id) throws error if id param passed as undefined
Fixes #1926 
- Added id check before checking its object values
> fix: (lingui/core) i18n error if id is undefined

- website/docs/tutorials/react.md
When following the tutorial, I encountered an issue where the messages compiled with Lingui used the default CommonJS syntax, while the rest of my Vite React project used ES modules. To resolve my import issues, I edited `lingui.config.js` accordingly. However, I'm unsure about removing the JSDoc string.
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to …
> docs: update lingui.config.js to use ES modules for consistency and specify namespace

- packages/cli/src/services/translationIO.ts
- website/docs/tools/translation-io.md
We noticed that our Translation.io service, in the CLI package, did not handle the new `context` attribute (introduced in v4 of Lingui). This PR updates the functions that convert PO items to our API segments and back, now handling this `context` attribute and thus resolving JS catalog issues.
This change ensures retro-compatibility for existing Translation.io users that already have an active Lingui project.
This PR has no impact for developers not using the Translation.io service.
N.B. we also updated the documentation page describing the Translation.io tool (missing image + new …
> fix(cli): update translationIO service in CLI package (to handle context)

- packages/cli/src/api/__snapshots__/compile.test.ts.snap
- packages/cli/src/api/compile.ts
In typescript projects which are using [ts-reset](https://github.com/total-typescript/ts-reset) and `compileNamespace: "ts"`, the compiled output is invalid because the type of `JSON.parse` is changed to `unknown` from the normal `any`, meaning that you cannot just use a type annotation and must use an explicit cast. There doesn't seem to be any simple configuration that could fix this issue, so this PR with an explicit type cast seems to be a logical answer. 
It doesn't affect anyone who is not using `ts-reset`, and expands compatibility for those who are.
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about …
> fix: include type cast on ts compilation

- packages/babel-plugin-extract-messages/src/index.ts
- packages/babel-plugin-extract-messages/test/__snapshots__/index.ts.snap
- packages/babel-plugin-extract-messages/test/fixtures/js-message-descriptor.js
- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog/extractFromFiles.ts
- packages/cli/test/extract-po-format/expected/en.po
- packages/cli/test/extract-po-format/expected/pl.po
- packages/cli/test/extract-po-format/fixtures/placeholders.ts
- packages/cli/test/index.test.ts
- packages/conf/src/types.ts
- packages/extractor-vue/src/__snapshots__/extractor.test.ts.snap
- packages/format-po/README.md
- packages/format-po/src/__snapshots__/po.test.ts.snap
- packages/format-po/src/__snapshots__/utils.test.ts.snap
- packages/format-po/src/po.test.ts
- packages/format-po/src/po.ts
- packages/format-po/src/utils.test.ts
- packages/format-po/src/utils.ts
This feature serves similar purpose as in this PR https://github.com/lingui/js-lingui/pull/1874.
If the message contains unnamed placeholders, such as `{0}` print theirs values into PO comments, so translators got an idea what this placeholder is about. 
```js
t`Hello ${user.name} ${value}`
```
This will be extracted as
Before: 
```po
msgid "Hello {0} {value}"
```
After: 
```po
#. ph: {0} = user.name
msgid "Hello {0} {value}"
```
This benefit of this solution is that developers can reuse more translations, because different placeholder name will not create different translations keys. 
Also now placeholder metadata is available for formatters, so users can implement theirs own logic for placeholders (for example replace them to values)
[//]: # (What types of changes does your code …
> feat: collect and print placeholders in Po files for better translation context

- packages/cli/src/extract-experimental/linguiEsbuildPlugin.ts
- packages/cli/test/extractor-experimental/fixtures/pages/index.page.ts
Because we use babel to process only macro in esbuild plugin and left rest of the syntax (including typescript) as-is we have to specify correct loader for esbuild.
I choosed tsx loader because it's a superset and do everything what js and ts and jsx loaders could do without relying on file extension
Fixes https://github.com/lingui/js-lingui/pull/1958#issuecomment-2212951631
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. …
> fix(experimental-extractor): change default loader to tsx

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/fixtures/collect/$componentE/index.js
- packages/cli/src/api/fixtures/collect/(componentC)/index.js
- packages/cli/src/api/fixtures/collect/[componentD]/index.js
- packages/cli/src/api/utils.test.ts
- packages/cli/src/api/utils.ts
We recently migrated to [TanStack Router](https://github.com/TanStack/router), which uses file-based routing with several [file naming conventions](https://tanstack.com/router/latest/docs/framework/react/guide/file-based-routing#file-naming-conventions). The `lingui extract --watch` command stopped working on any routes with these special characters. However, `lingui extract` continued to work.
Debugging revealed that `--watch` sets `options.files`, and these paths are formed into a regular expression. If any of these paths contains a character with special regex meaning, like `$`, then `paths` won't be correctly filtered.
```
if (options.files) {
options.files = options.files.map((p) =>normalize(p, false))
const regex = new RegExp(options.files.join("|"), "i")
paths = paths.filter((path: …
```
> fix(extract): escape special regex characters used in file-based routing systems

- packages/cli/src/api/catalog/getCatalogDependentFiles.test.ts
- packages/cli/src/api/catalog/getCatalogs.test.ts
- packages/cli/src/api/extractors/babel.ts
- packages/cli/src/api/utils.ts
- packages/cli/src/extract-experimental/bundleSource.ts
- packages/cli/src/extract-experimental/resolveTemplatePath.test.ts
- packages/cli/src/lingui-compile.ts
- packages/cli/src/lingui-extract-experimental.ts
- packages/cli/src/lingui-extract-template.ts
- packages/cli/src/lingui-extract.ts
- packages/cli/test/index.test.ts
- packages/loader/test/loader.test.ts
- packages/vite-plugin/test/index.ts
i installed Windows ARM on my Mac, and fixed all compatibility issues which were marked as "skipOnWindows" in tests.
> fix: windows compatibility

- packages/cli/package.json
- yarn.lock
4.0.2 contains a vulnerability that most likely doesn't affect @lingui/cli, but there should be no reason to depend on an exact version which prevents consumers from upgrading the package without a version conflict.
I've kept the version at 4.0.2 to prevent a breaking change (in the sense that bumping it to ^4.0.8 might also cause a version conflict for consumers). Let me know if you'd rather bump it to ^4.0.8. Ref: https://github.com/advisories/GHSA-952p-6rrq-rcjv …
> fix(cli): use caret range for `micromatch` dependency

- packages/react/src/Trans.test.tsx
- packages/react/src/format.test.tsx
- packages/react/src/format.ts
Fixes an issue where `<Trans>` didn't work as expected when using `asChild`, which is most commonly used with [Radix](https://www.radix-ui.com/primitives) (and [shadcn/ui](https://ui.shadcn.com/), which is based on it).
Fixes https://github.com/lingui/js-lingui/issues/2015
Fixes #2015
> fix: return a single node when applicable

- packages/core/src/i18n.test.ts
- packages/core/src/interpolate.test.ts
- packages/core/src/interpolate.ts
In`js-lingui/packages/core/src/interpolate.ts` there is a regular expression to test if the string has unicode values inside, it has the `g` flag which makes that Regexp stateful. If you render the same string twice in a row, Lingui will not parse the string a second time, because the `lastIndex` for that string will be after the Unicode symbol at that point. And since there is no need to keep the `lastIndex` state, no need for a `g` flag here.
The bug is reproducible, for example, in React with the [StrictMode](https://react.dev/reference/react/StrictMode) enabled.
[//]: # (What …
> fix: unicode parsing

- .github/workflows/main-suite.yml
- .github/workflows/release-test.yml
- package.json
- packages/babel-plugin-extract-messages/package.json
- packages/babel-plugin-lingui-macro/package.json
- packages/cli/package.json
- packages/cli/src/lingui-compile.ts
- packages/cli/src/lingui-extract.ts
- packages/conf/package.json
- packages/core/package.json
- packages/detect-locale/package.json
- packages/extractor-vue/package.json
- packages/format-csv/package.json
- packages/format-json/package.json
- packages/format-po-gettext/package.json
- packages/format-po/package.json
- packages/jest-mocks/package.json
- packages/loader/package.json
- packages/macro/package.json
- packages/message-utils/package.json
- packages/react/package.json
- packages/remote-loader/package.json
- packages/vite-plugin/package.json
- website/docs/releases/migration-5.md
- yarn.lock
- Set Node 20 engine for packages
- CI: Remove Node 16, 18, 19 and add 22 to the test matrix
- Fix linting issues
> chore: set the minimum required node version to 20

- packages/babel-plugin-extract-messages/package.json
- packages/cli/package.json
- packages/cli/src/api/__snapshots__/compile.test.ts.snap
- packages/cli/src/api/extractors/babel.ts
- packages/macro/package.json
- yarn.lock
Enable `importAttributes` and `explicitResourceManagement` parser plugins, because they are stage3 now and should be supported out of the box by lingui extractor
Fixes https://github.com/lingui/js-lingui/issues/2003
> feat: enable importAttributes and explicitResourceManagement for extractor

- packages/babel-plugin-lingui-macro/src/index.ts
webpack (and nextjs) for some reason doesn't read message from error but instead rethrow the first frame of the stacktrace
So this fix will turn error from this
```
wait  - compiling /examples (client and server)...
error - ./src/pages/examples.tsx
TypeError: Cannot read properties of undefined (reading 'find')
```
to this: 
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of …
> fix: Improve macro error

- packages/babel-plugin-lingui-macro/src/macroJs.ts
- packages/babel-plugin-lingui-macro/test/__snapshots__/js-t.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/js-useLingui.test.ts.snap
- packages/babel-plugin-lingui-macro/test/js-t.test.ts
- packages/babel-plugin-lingui-macro/test/js-useLingui.test.ts
- packages/babel-plugin-lingui-macro/test/jsx-plural.test.ts
Support 
```js
import { t } from '@lingui/core/macro'
const msg = t(msg)
```
+ add more tests. 
> fix: correctly handle a variable passed to the `t` macro

- packages/cli/src/api/extractors/index.ts
- packages/conf/__typetests__/index.test-d.tsx
- packages/conf/src/types.ts
- website/docs/releases/migration-5.md
I believe it wasn't used, because it was even not documented. 
I removed this ability for simplicity and future ESM support. Related migration notice added.
> refactor: remove strings support from `LinguiConfig.extractors`

- website/docs/introduction.md
Slightly improved the feature descriptions and added a workflow overview.
> docs: improve introduction

- packages/cli/src/api/catalog/mergeCatalog.ts
- packages/cli/test/extract-partial-consistency/existing/en.po
- packages/cli/test/extract-partial-consistency/expected/en.po
- packages/cli/test/extract-partial-consistency/fixtures/file-a.ts
- packages/cli/test/extract-partial-consistency/fixtures/file-b.tsx
- packages/cli/test/index.test.ts
When using `lingui extract <...files>` all translations in catalog that are not in the listed file get their obsolete flag to false, regardless if the obsolete flag was not set or already set to true.
#1963
> fix(extract): when files are used, don't overwrite obsolete

- website/docs/releases/migration-5.md
> docs: improve the v5 migration guide

- packages/babel-plugin-lingui-macro/src/index.ts
- packages/babel-plugin-lingui-macro/src/macroJs.ts
- packages/babel-plugin-lingui-macro/src/macroJsAst.test.ts
- packages/babel-plugin-lingui-macro/src/macroJsAst.ts
- packages/babel-plugin-lingui-macro/src/macroJsx.test.ts
- packages/babel-plugin-lingui-macro/src/macroJsx.ts
- packages/babel-plugin-lingui-macro/src/messageDescriptorUtils.ts
- packages/babel-plugin-lingui-macro/test/__snapshots__/js-t.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/jsx-trans.test.ts.snap
- packages/babel-plugin-lingui-macro/test/js-t.test.ts
- packages/babel-plugin-lingui-macro/test/jsx-trans.test.ts
Make it possible to configure whether the `message` prop should be stripped or not from the transpiled output. I have added a new option called `stripMessageField` that can be set from the Babel config to control the behaviour.
This does not change any of the default behaviour in the macro. Message (and other props like comment / context) will be kept in development mode, but removed in production mode (`NODE_ENV ===" production"`) by default. But it is now possible to override this behaviour by setting `stripMessageField` option in Babel config:
<details>
<summary>Example babel.config.js</summary>
```javascript
// babel.config.js
module.exports = {
plugins: [
"macros",
{
// ...
// Other macros config
lingui: {
// message field will be removed in both dev and prod mode
stripMessageField: …
```
> feat(macro): make message stripping configurable via Babel options

- packages/core/macro/index.d.ts
- website/docs/ref/macro.mdx
- website/docs/releases/migration-5.md
As stated in the migration doc. There few ways to achieve the same result, it's better to stick with the one for consistency. As a benefit we can remove significant layer of complexity from SWC / babel / Eslint integrations. 
I've created a GritQL migration and test in the studio only. I don't know how to correctly run this migration in the users codebase, once i figure it out i will update gist or the doc. 
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your …
> feat(macro): deprecate custom i18n instance on `t` macro

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [Lingui JS Guru](https://gurubase.io/g/lingui-js) to Gurubase. Lingui JS Guru uses the data from this repo and data from the [docs](https://lingui.dev) to answer questions by leveraging the LLM.
In this PR, I showcased the "Lingui JS Guru", which highlights that Lingui JS now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution.
Additionally, if you want …
> docs: introducing Lingui JS Guru on Gurubase.io

- packages/cli/package.json
- packages/cli/src/index.ts
- packages/conf/src/defineConfig.ts
- packages/conf/src/index.test.ts
- packages/conf/src/index.ts
- website/docs/guides/custom-extractor.md
- website/docs/guides/custom-formatter.md
- website/docs/guides/pseudolocalization.md
- website/docs/installation.mdx
- website/docs/misc/i18next.md
- website/docs/ref/catalog-formats.md
- website/docs/ref/conf.md
- website/docs/ref/extractor-vue.md
It seems, having a `defineConfig` type helper become a community standard for cli tools and other runners. 
This PR brings this function and update a documentation to use it. This function is just a type helper. Both JS and TS users could benefit from it. 
I re-exported this method from `@lingui/cli` because `@lingui/cli` should be installed in every project, but `@lingui/conf` is an internal package and users should not have it installed.
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going …
> feat: add defineConfig method

- packages/vite-plugin/package.json
- yarn.lock
This PR widens the range of accepted peer dependency versions for vite in the vite-plugin to add support for vite@6.
We've been using `vite@6` with the lingui vite-plugin without any issues since `vite@6` was released. 
I also updated the `vite` dev dependency to ensure that the type imported in the source code matches a newer version than v4 and ran yarn dedupe to clean up the lock file after the vite upgrade.
Fixes #2103
> feat(vite-plugin): add support for vite@6

- package.json
Temporarily raise the limit to avoid failed pipeline jobs. This should be investigated more, maybe we even need to find a better solution for size checking.
> ci: fix size testing failing

- packages/cli/src/lingui-compile.ts
- packages/cli/src/test/compile.test.ts
`lingui compile --strict` shouldn't fail with pseudo language missing translations.
Fixes #2128
> fix: Allow empty translations for pseudo locale in compile --strict

- packages/core/src/i18n.test.ts
- packages/core/src/i18n.ts
- packages/vite-plugin/test/macro-usage/entrypoint.js
Related to https://github.com/lingui/js-lingui/issues/2095
There might be the cases where locale is not set. To avoid frustration and long debugging sessions it is better to fail earlier with a meaningful error message. 
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for …
> feat: add meaningful error when locale is not set

- packages/babel-plugin-lingui-macro/src/constants.ts
- packages/babel-plugin-lingui-macro/src/index.ts
- packages/babel-plugin-lingui-macro/src/macroJsAst.ts
- packages/babel-plugin-lingui-macro/src/macroJsx.test.ts
- packages/babel-plugin-lingui-macro/src/macroJsx.ts
- packages/babel-plugin-lingui-macro/test/__snapshots__/js-plural.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/js-t.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/jsx-plural.test.ts.snap
- packages/babel-plugin-lingui-macro/test/__snapshots__/jsx-trans.test.ts.snap
- packages/babel-plugin-lingui-macro/test/js-defineMessage.test.ts
- packages/babel-plugin-lingui-macro/test/js-plural.test.ts
- packages/babel-plugin-lingui-macro/test/js-select.test.ts
- packages/babel-plugin-lingui-macro/test/js-selectOrdinal.test.ts
- packages/babel-plugin-lingui-macro/test/js-t.test.ts
- packages/babel-plugin-lingui-macro/test/jsx-plural.test.ts
- packages/babel-plugin-lingui-macro/test/jsx-select.test.ts
- packages/babel-plugin-lingui-macro/test/jsx-selectOrdinal.test.ts
- packages/babel-plugin-lingui-macro/test/jsx-trans.test.ts
- packages/core/macro/__typetests__/index.test-d.tsx
- packages/core/macro/index.d.ts
- packages/react/macro/__typetests__/index.test-d.tsx
- packages/react/macro/index.d.ts
Adds a way to give an explicit name for placeholders in the messages. There are two syntaxes supported: 
```js
import {t} from "@lingui/core/macro";
t`Hello ${{name: getUsername()}}`
```
And with explicit `ph` helper:
```js
import {ph, t} from "@lingui/core/macro";
t`Hello ${ph({name: getUsername()})}`
```
Shortcut syntax is also supported: 
```js
import {t} from "@lingui/core/macro";
const name = "World"
t`Hello ${{name}}`
```
plural / select / selectOrdinal:
```js
import {t, plural} from "@lingui/core/macro";
t`We have ${plural({count: getDevelopersCount()}, {one: "# developer", "# developers"})}`
```
In the JSX
```js
import {Trans} from "@lingui/react/macro";
<Trans>Hello {{name: getUsername()}}</Trans>;
```
```jsx
import { Plural } from "@lingui/react/macro";
<Plural
value={{ count: …
```
> feat: add ph() and explicit labels for placeholders

- jest.config.js
- packages/core/src/formats.test.ts
- packages/core/src/formats.ts
- packages/core/src/i18n.test.ts
- packages/core/src/interpolate.test.ts
- packages/core/src/interpolate.ts
- packages/message-utils/build.config.ts
- packages/message-utils/package.json
- packages/message-utils/src/compileMessage.test.ts
- packages/message-utils/src/compileMessage.ts
- yarn.lock
Adding support for `short/default/long/full`full compatible with a reference implementation from here:
https://messageformat.github.io/messageformat/guide/#date-and-time
Only `date` and `time` are supported for now. 
Fixes https://github.com/lingui/js-lingui/issues/2116
> feat(core,message-utils): support date,time format with short/default/long/full and skeleton

- website/docs/tutorials/javascript.md
- website/docs/tutorials/react.md
> docs: better communicate macro usage restrictions

- packages/react/src/TransNoContext.tsx
Trans from `@lingui/react` doesn't accept children but has it in props definition. This is a bug which lead a confusion for users. 
This PR drops incorrect property from TransProps
After this change, user would be informed by typescript about incorrect usage of a Trans component. 
> fix(react): remove children property from runtime Trans

- package.json
- packages/cli/package.json
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/catalog/mergeCatalog.ts
- packages/cli/src/api/pseudoLocalize.ts
- packages/cli/src/extract-experimental/writeCatalogs.ts
- packages/format-json/package.json
- packages/format-json/src/json.ts
- packages/remote-loader/package.json
- packages/remote-loader/src/index.ts
- packages/remote-loader/src/minimalParser.ts
- yarn.lock
Remove ramda leftovers from the code. The new EcmaScript features perfectly replaces everything from it without much boilerplate. As an additional benefit, it's more friendly for typescript. 
> refactor: remove ramda

- packages/react/src/format.test.tsx
- packages/react/src/format.ts
In @lingui/react, newlines in translations are not preserved during formatting (rendering), when `<tags>` are present.
Please see this demo: https://codesandbox.io/p/devbox/infallible-cdn-y863cd 
This PR ensures that formatting is done the same way for both variants: with and without `<tags>`.
Fixes #2157 
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here …
> feat(react): preserve newlines during string formatting

- website/docs/guides/pseudolocalization.md
The documentation suggests using the `zu_ZA` locale if you want to use a valid locale for pseudolocalization. This value is however invalid and should be `zu-ZA` instead.
> docs: Use valid locale for proposed pseudo locale

- packages/core/src/i18n.test.ts
- packages/core/src/interpolate.test.ts
- packages/core/src/interpolate.ts
Remove whitespace trimming in runtime, as was promised in v5 release notes
Fixes https://github.com/lingui/js-lingui/issues/2167
> fix(core): remove runtime whitespace trimming aligned with v5

- website/src/components/Features.module.scss
This PR hides the background images for the Features section of the main page because they break the mobile layout.
> docs: fix mobile view of the main page

- website/docs/ref/swc-plugin.md
As discussed in https://github.com/lingui/swc-plugin/pull/137, we added an option to override the default behavior that strips fields in production builds
> docs: add strip non essential fields option to SWC plugin doc

- packages/babel-plugin-lingui-macro/src/macroJs.ts
- packages/babel-plugin-lingui-macro/test/__snapshots__/js-useLingui.test.ts.snap
- packages/babel-plugin-lingui-macro/test/js-useLingui.test.ts
Correctly process placeholder's indexes in `t` calls destructed from `useLingui` macro
fix: #2203
> fix: incorrect index for placeholders in useLingui macro

- packages/cli/package.json
- yarn.lock
Opening this PR as a draft to track a fix for #2181 
It seems the CLI is affected by https://github.com/evanw/esbuild/issues/4070
The source map at `babel.ts` with earlier versions of `esbuild` includes the path, but at `0.25.0` it only includes the file name. This breaks the mapping from the built bundle to the source in the experimental extractor, leading to the wrong file name in the extracted `.po` files.
https://github.com/lingui/js-lingui/blob/d36c323c2151f91b05305809bc9a6d291528aed2/packages/cli/src/api/extractors/babel.ts#L53-L55
Fixes #2181 
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of …
> fix(cli): update esbuild

- .prettierignore
- examples/tanstack-start/src/api.ts
- examples/tanstack-start/src/locales/en/messages.po
- examples/tanstack-start/src/locales/fr/messages.po
- examples/tanstack-start/src/modules/lingui/i18n.server.ts
- examples/tanstack-start/src/routes/api/users.$id.ts
- examples/tanstack-start/src/routes/users.$userId.tsx
- examples/tanstack-start/src/routes/users.route.tsx
- examples/tanstack-start/src/ssr.tsx
I noticed the translation in the API and some SSR requests were not working because of the macro not being applied in such cases.
- I replaced the macro with the `i18n._()` method
- I implemented a strategy for detecting the locale in the API (using a header, but can be anything)
> chore(examples): fix tanstack-start example on API & SSR requests

- packages/conf/package.json
- yarn.lock
Remove lodash.get dependency in conf package, it is unused and causes deprecation warnings during `npm install`.
```
> npm install
npm warn deprecated lodash.get@4.4.2: This package is deprecated. Use the optional chaining (?.) operator instead.
```
> build: Remove lodash.get dependency in conf package

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.test.ts
- packages/cli/src/api/catalog.ts
close #2241
When using catalog's input with file-base routing systems, `[]` is not escaped.
So `globSync` can't get path under the dynamic route, like `app/[lang]/page.tsx`
> fix: use makePathRegexSafe with globSync

- packages/cli/package.json
- yarn.lock
Removes some now unused dependencies from `@lingui/cli`, including `babel-plugin-macros` which caused some trouble for `npm ci` when `vite` was also installed.
Fixes #2264 
> fix(cli): remove unused dependency babel-plugin-macros

- .github/workflows/size-limit.yml
- README.md
- package.json
- packages/core/package.json
- packages/core/src/escapeSequences.test.ts
- packages/core/src/escapeSequences.ts
- packages/core/src/i18n.test.ts
- packages/core/src/i18n.ts
- packages/core/src/interpolate.ts
- website/docs/introduction.md
- yarn.lock
Replace the `unraw` library with a lightweight custom implementation for decoding escape sequences.
`unraw` functionality is too redundant and is not used in the code now. We use a regular expression that only finds valid escape sequences. So I propose to use a more lightweight and simple implementation and remove the unraw dependency. This will not change the behavior for the user.
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating …
> fix: remove unraw dependency

- website/docs/installation.mdx
While setting up Lingui in my Vite project, I noticed that the macros were unstable — some worked, others didn't. After several tests, I realized that my `macros` plugin was listed after the `babel-plugin-react-compiler`. Once I swapped the order of the plugins, everything worked perfectly.
> docs: Add note about react compiler

- examples/rspack/src/react-env.d.ts
- packages/react/macro/index.d.ts
- packages/react/src/I18nProvider.tsx
- packages/react/src/Trans.test.tsx
It's deprecated in `@types/react@^18` (current dev dependency) and completely removed in `@types/react@^19`, causing type errors.
> fix: remove `VFC` type usage

- packages/cli/src/api/__snapshots__/catalog.test.ts.snap
- packages/cli/src/api/catalog.ts
- packages/cli/src/api/catalog/extractFromFiles.ts
- packages/cli/src/api/compile.ts
- packages/cli/src/lingui-compile.ts
- packages/cli/src/lingui-extract.ts
- packages/cli/src/test/__snapshots__/compile.test.ts.snap
- packages/cli/src/test/compile.test.ts
- packages/cli/test/extractor-experimental-template/expected/about.page.en.js
- packages/cli/test/extractor-experimental-template/expected/about.page.pl.js
- packages/cli/test/extractor-experimental/expected/about.page.en.js
- packages/cli/test/extractor-experimental/expected/about.page.pl.js
- packages/metro-transformer/test/metroTransformer.test.ts
Closes https://github.com/lingui/js-lingui/issues/2253
This PR enables full concurrency execution for extract and compile comands.
Instead of 
```js
for (item of items) {
await doJob()
}
```
Using 
```js
Promise.all(items.map(async () => {
await doJob()
}))
```
[//]: # (_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a …
> feat: full concurrency for extract / compile commands

- .github/workflows/version-bump.yml
This PR introduces a few changes:
- Configured [Trusted publishing for npm packages](https://docs.npmjs.com/trusted-publishers)
- Split the release workflow into two separate workflows: one for version bumping and one for publishing to NPM.
> ci: trusted publishing
